//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class LASecureData, NSMutableArray;

@interface PinField : UIView
{
    NSMutableArray *_pinDashViews;	// 8 = 0x8
    NSMutableArray *_pinDotViews;	// 16 = 0x10
    struct CGSize _pinDashSize;	// 24 = 0x18
    struct CGSize _pinDotSize;	// 40 = 0x28
    double _slotHeight;	// 56 = 0x38
    double _slotWidth;	// 64 = 0x40
    id <PinFieldDelegate> _delegate;	// 72 = 0x48
    LASecureData *_pinValue;	// 80 = 0x50
    unsigned long long _pinLength;	// 88 = 0x58
}

@property(readonly, nonatomic) unsigned long long pinLength; // @synthesize pinLength=_pinLength;
@property(readonly, nonatomic) LASecureData *pinValue; // @synthesize pinValue=_pinValue;
@property(nonatomic) __weak id <PinFieldDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100018ac0
- (void)deleteLastPinCharacter;	// IMP=0x0000000100018a0c
- (void)appendPinCharacter:(id)arg1;	// IMP=0x0000000100018888
- (void)layoutSubviews;	// IMP=0x00000001000186f8
- (void)updateLayoutForWidth:(double)arg1;	// IMP=0x0000000100018488
- (id)initWithPinLength:(id)arg1;	// IMP=0x0000000100018098

@end

