//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PinFieldDelegate.h"
#import "UIKeyInput.h"

@class NSString, PinField, PinKeypad, UIButton, UILabel, UITextInputPasswordRules, UIViewController;

@interface PinView : UIView <UIKeyInput, PinFieldDelegate>
{
    UILabel *_titleLabel;	// 8 = 0x8
    PinField *_pinField;	// 16 = 0x10
    UIView *_dividerLine;	// 24 = 0x18
    double _scale;	// 32 = 0x20
    _Bool _autoKeyboard;	// 40 = 0x28
    _Bool _keypadActive;	// 41 = 0x29
    _Bool _pinEntered;	// 42 = 0x2a
    PinKeypad *_keypad;	// 48 = 0x30
    struct CGRect _keyboardDefaultFrame;	// 56 = 0x38
    UIViewController *_viewController;	// 88 = 0x58
    id <PinViewDelegate> _delegate;	// 96 = 0x60
    UIButton *_cancelButton;	// 104 = 0x68
    NSString *_title;	// 112 = 0x70
}

@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak id <PinViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;	// IMP=0x00000001000133e4
- (void)deleteBackward;	// IMP=0x0000000100013358
- (void)insertText:(id)arg1;	// IMP=0x0000000100013340
@property(readonly, nonatomic) _Bool hasText;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
@property(nonatomic) long long keyboardAppearance;
@property(nonatomic) long long keyboardType;
@property(nonatomic) long long autocorrectionType;
@property(nonatomic) long long spellCheckingType;
- (void)pinEntered:(id)arg1;	// IMP=0x00000001000131e4
- (void)_setKeyboardUserInteractionEnabled:(_Bool)arg1;	// IMP=0x0000000100013160
- (void)_dismissKeypad;	// IMP=0x0000000100013108
- (void)_deactivateKeypadView;	// IMP=0x00000001000130c0
- (void)_activateKeypadView;	// IMP=0x0000000100012fc8
- (_Bool)resignFirstResponder;	// IMP=0x0000000100012f24
- (_Bool)becomeFirstResponder;	// IMP=0x0000000100012e8c
- (_Bool)canBecomeFirstResponder;	// IMP=0x0000000100012e5c
- (struct CGRect)_roundRectToPixel:(struct CGRect)arg1;	// IMP=0x0000000100012dc8
- (double)_roundToPixel:(double)arg1;	// IMP=0x0000000100012dac
- (void)_layoutSubviewsWithKeyboard:(struct CGRect)arg1;	// IMP=0x0000000100012b10
- (void)layoutSubviews;	// IMP=0x00000001000128b8
- (void)keyboardDidShow:(id)arg1;	// IMP=0x0000000100012768
- (void)dealloc;	// IMP=0x00000001000126bc
- (id)initWithPinLength:(id)arg1;	// IMP=0x00000001000122fc

// Remaining properties
@property(nonatomic) long long autocapitalizationType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enablesReturnKeyAutomatically;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) UITextInputPasswordRules *passwordRules;
@property(nonatomic) long long returnKeyType;
@property(nonatomic) long long smartDashesType;
@property(nonatomic) long long smartInsertDeleteType;
@property(nonatomic) long long smartQuotesType;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

