//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BFFSplashController.h"

@class BFFPaneHeaderView, UIButton, UIStackView;

@interface CBOpeningViewController : BFFSplashController
{
    UIStackView *_deviceInformationView;	// 8 = 0x8
    _Bool _showingDeviceInformation;	// 16 = 0x10
    UIButton *_infoButton;	// 24 = 0x18
}

@property(nonatomic) _Bool showingDeviceInformation; // @synthesize showingDeviceInformation=_showingDeviceInformation;
@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
- (void).cxx_destruct;	// IMP=0x000000010000875c
- (void)infoButtonTapped:(id)arg1;	// IMP=0x00000001000083e4
- (void)_setupInfoButton;	// IMP=0x00000001000082bc
- (id)_deviceInformation;	// IMP=0x00000001000080c8
- (id)deviceInformationView;	// IMP=0x0000000100007b5c
- (void)dealloc;	// IMP=0x0000000100007ab4
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100007974
- (void)viewDidLoad;	// IMP=0x00000001000078a8
- (id)init;	// IMP=0x000000010000741c

// Remaining properties
@property(retain, nonatomic) BFFPaneHeaderView *headerView; // @dynamic headerView;

@end

