//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "CBWindowLike.h"
#import "CBWindowLikeInternal.h"

@class NSString, UIViewController;

@interface CBWindow : UIWindow <CBWindowLikeInternal, CBWindowLike>
{
    _Bool _presentViewControllerWithStatusBarShown;	// 8 = 0x8
    _Bool _statusBarHidden;	// 9 = 0x9
    _Bool _wallpaperTunnel;	// 10 = 0xa
    _Bool _dismissed;	// 11 = 0xb
    unsigned long long _windowManagerLayer;	// 16 = 0x10
    id <CBWindowDelegate> _windowManager;	// 24 = 0x18
    double _previousStatusBarWindowLevel;	// 32 = 0x20
    UIViewController *_presentedView;	// 40 = 0x28
}

@property(retain, nonatomic) UIViewController *presentedView; // @synthesize presentedView=_presentedView;
@property(nonatomic) _Bool dismissed; // @synthesize dismissed=_dismissed;
@property(nonatomic) _Bool wallpaperTunnel; // @synthesize wallpaperTunnel=_wallpaperTunnel;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden;
@property(nonatomic) double previousStatusBarWindowLevel;
@property(nonatomic) _Bool presentViewControllerWithStatusBarShown;
@property(nonatomic) __weak id <CBWindowDelegate> windowManager; // @synthesize windowManager=_windowManager;
@property(nonatomic) unsigned long long windowManagerLayer; // @synthesize windowManagerLayer=_windowManagerLayer;
- (void).cxx_destruct;	// IMP=0x00000001000180b0
- (void)viewControllerDidDismiss;	// IMP=0x0000000100017eec
- (void)dismissViewControllerAnimated:(_Bool)arg1;	// IMP=0x0000000100017c74
- (id)initWithWallpaperTunnel:(_Bool)arg1;	// IMP=0x0000000100017b4c
- (id)init;	// IMP=0x0000000100017b3c
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isHidden) _Bool hidden; // @dynamic hidden;
@property(readonly) Class superclass;
@property(nonatomic) double windowLevel;

@end

