//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DataActivationRequestFactory : NSObject
{
}

+ (void)requestWithURL:(id)arg1 method:(unsigned long long)arg2 parameterSources:(unsigned long long)arg3 overrideParameters:(id)arg4 urlEncode:(_Bool)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x0000000100010d80
+ (id)_postRequestWithURL:(id)arg1 jsonParameters:(id)arg2;	// IMP=0x0000000100010bf0
+ (id)_postRequestWithURL:(id)arg1 parameters:(id)arg2 urlEncode:(_Bool)arg3;	// IMP=0x0000000100010a78
+ (id)_formStringForParameters:(id)arg1 urlEncode:(_Bool)arg2;	// IMP=0x000000010001083c
+ (id)_getRequestWithURL:(id)arg1 parameters:(id)arg2;	// IMP=0x00000001000105fc
+ (void)_parameterDictionaryForSources:(unsigned long long)arg1 overrideParameters:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010000fe44
+ (void)_parametersForHandoffParametersWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010000fcac
+ (void)_handoffTokenAndPodIdentifierWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010000fb54
+ (void)_parametersForSequoiaDeviceInfoWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010000f924
+ (void)_sequoiaDeviceInfoWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010000f840
+ (void)_parametersForLegacyDeviceInfoWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010000f588
+ (id)_legacyDeviceInfo;	// IMP=0x000000010000f564

@end

