//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class CLGeocoder, NSDate, NSDictionary, NSString;

@interface _MPMeCardGeocoderAddress : NSObject <NSSecureCoding>
{
    _Bool _cancelingGeocode;	// 8 = 0x8
    int _tries;	// 12 = 0xc
    int _state;	// 16 = 0x10
    NSDictionary *_addressDictionary;	// 24 = 0x18
    NSString *_entityID;	// 32 = 0x20
    NSString *_label;	// 40 = 0x28
    CLGeocoder *_geocoder;	// 48 = 0x30
    NSDictionary *_locationDictionary;	// 56 = 0x38
    NSDate *_lastGeocodeAttempt;	// 64 = 0x40
    NSDate *_geocodeAfter;	// 72 = 0x48
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010003f780
@property(readonly) NSDate *geocodeAfter; // @synthesize geocodeAfter=_geocodeAfter;
@property(readonly) _Bool cancelingGeocode; // @synthesize cancelingGeocode=_cancelingGeocode;
@property(readonly) int state; // @synthesize state=_state;
@property(readonly) NSDate *lastGeocodeAttempt; // @synthesize lastGeocodeAttempt=_lastGeocodeAttempt;
@property(readonly) NSDictionary *locationDictionary; // @synthesize locationDictionary=_locationDictionary;
@property(readonly) int tries; // @synthesize tries=_tries;
@property(readonly) CLGeocoder *geocoder; // @synthesize geocoder=_geocoder;
@property(readonly, copy) NSString *label; // @synthesize label=_label;
@property(readonly, copy) NSString *entityID; // @synthesize entityID=_entityID;
@property(readonly, copy) NSDictionary *addressDictionary; // @synthesize addressDictionary=_addressDictionary;
- (void).cxx_destruct;	// IMP=0x0000000100040bfc
- (id)description;	// IMP=0x0000000100040a14
- (_Bool)expired;	// IMP=0x0000000100040950
- (id)nextGeocodeAttempt;	// IMP=0x00000001000407a0
- (void)cancelGeocode;	// IMP=0x0000000100040778
- (void)attemptGeocodeWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000401f4
- (void)recalculateGeocodeAfterDate;	// IMP=0x00000001000401b8
- (_Bool)checkGeocodeAfterDateForSanity;	// IMP=0x000000010003ff7c
- (id)createGeocodeAfterDate;	// IMP=0x000000010003fc64
- (void)dealloc;	// IMP=0x000000010003fc0c
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010003fab8
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010003f78c
- (id)initWithAddressDictionary:(id)arg1 entityID:(id)arg2 label:(id)arg3;	// IMP=0x000000010003f628

@end

