//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PHAudioCallControlsViewDelegate.h"
#import "TURouteControllerDelegate.h"

@class NSString, PHAudioCallControlArrangement, PHAudioCallControlsView, TUCallCenter;

@interface PHAudioCallControlsViewController : UIViewController <TURouteControllerDelegate, PHAudioCallControlsViewDelegate>
{
    _Bool _enabled;	// 8 = 0x8
    id <PHAudioCallControlsViewControllerDelegate> _delegate;	// 16 = 0x10
    PHAudioCallControlsView *_controlsView;	// 24 = 0x18
    PHAudioCallControlArrangement *_controlArrangement;	// 32 = 0x20
    TUCallCenter *_callCenter;	// 40 = 0x28
    id <TUCallContainerPrivate> _callContainer;	// 48 = 0x30
}

@property(retain, nonatomic) id <TUCallContainerPrivate> callContainer; // @synthesize callContainer=_callContainer;
@property(retain, nonatomic) TUCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(retain) PHAudioCallControlArrangement *controlArrangement; // @synthesize controlArrangement=_controlArrangement;
@property(retain) PHAudioCallControlsView *controlsView; // @synthesize controlsView=_controlsView;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property __weak id <PHAudioCallControlsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100022d84
- (void)routesChangedForRouteController:(id)arg1;	// IMP=0x00000001000ee35c
- (void)openMessagesForCall:(id)arg1;	// IMP=0x00000001000edb7c
@property(readonly, nonatomic) __weak PHAudioCallControlArrangement *currentArrangement;
- (_Bool)multipleCallsArePresent;	// IMP=0x00000001000ed9f8
- (_Bool)isEnabled;	// IMP=0x00000001000ed9ac
- (_Bool)controlTypeIsSelected:(unsigned long long)arg1;	// IMP=0x000000010001b910
- (_Bool)controlTypeIsEnabled:(unsigned long long)arg1;	// IMP=0x000000010001ae64
- (void)controlTypeLongPressed:(unsigned long long)arg1;	// IMP=0x00000001000ed638
- (void)controlTypeShortPressed:(unsigned long long)arg1;	// IMP=0x00000001000ed578
- (void)controlTypeTapped:(unsigned long long)arg1 forView:(id)arg2;	// IMP=0x00000001000ec840
- (id)titleForControlType:(unsigned long long)arg1;	// IMP=0x000000010001be18
- (id)imageForControlType:(unsigned long long)arg1;	// IMP=0x00000001000ec5f4
- (unsigned long long)controlTypeAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2;	// IMP=0x000000010001a2dc
- (unsigned long long)numberOfColumnsInControlsView:(id)arg1;	// IMP=0x0000000100018c60
- (unsigned long long)numberOfRowsInControlsView:(id)arg1;	// IMP=0x0000000100018c58
- (void)handleTUCallTTYTypeChangedNotification:(id)arg1;	// IMP=0x00000001000ec498
- (void)handleTUCallSupportsTTYWithVoiceChangedNotification:(id)arg1;	// IMP=0x00000001000ec33c
- (void)uplinkStateChangedNotification:(id)arg1;	// IMP=0x00000001000ec1e0
- (void)callModelChangedNotification:(id)arg1;	// IMP=0x00000001000ec084
- (void)faceTimeIDStatusChangedNotification:(id)arg1;	// IMP=0x00000001000ebf28
- (void)conferenceParticipantCallsChangedNotification:(id)arg1;	// IMP=0x00000001000ebdcc
- (void)callIsOnHoldChangedNotification:(id)arg1;	// IMP=0x00000001000ebc70
- (void)callStatusChangedNotification:(id)arg1;	// IMP=0x0000000100020d3c
- (void)loadView;	// IMP=0x0000000100018134
- (void)dealloc;	// IMP=0x0000000100022d0c
- (id)init;	// IMP=0x0000000100017e74

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

