//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PHAudioCallControlsViewController, UIImage, UIView;

@protocol PHAudioCallControlsViewControllerDelegate <NSObject>
- (UIImage *)frontmostCallProviderIconForAudioCallControlsViewController:(PHAudioCallControlsViewController *)arg1;
- (void)audioCallControlsViewControllerRequestedPunchOutPresentation:(PHAudioCallControlsViewController *)arg1;
- (void)audioCallControlsViewControllerRequestedVideoPresentation:(PHAudioCallControlsViewController *)arg1;
- (void)audioCallControlsViewControllerRequestedAudioRoutesPresentation:(PHAudioCallControlsViewController *)arg1;
- (void)audioCallControlsViewControllerRequestedAddCallPresentation:(PHAudioCallControlsViewController *)arg1 forView:(UIView *)arg2;
- (void)audioCallControlsViewControllerRequestedContactsPresentation:(PHAudioCallControlsViewController *)arg1 forView:(UIView *)arg2;
- (void)audioCallControlsViewControllerRequestedKeypadPresentationForFieldMode:(PHAudioCallControlsViewController *)arg1;
- (void)audioCallControlsViewControllerRequestedKeypadPresentation:(PHAudioCallControlsViewController *)arg1;
@end

