//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PHCallParticipantLabelDescriptor : NSObject
{
    _Bool _dynamic;	// 8 = 0x8
    NSArray *_strings;	// 16 = 0x10
    NSString *_secondaryString;	// 24 = 0x18
    unsigned long long _layoutState;	// 32 = 0x20
    NSString *_localizedSenderIdentity;	// 40 = 0x28
}

+ (id)organizationNameForCall:(id)arg1;	// IMP=0x000000010002ea4c
+ (id)labelDescriptorWithStringsForCall:(id)arg1 callCount:(long long)arg2 callCenter:(id)arg3;	// IMP=0x000000010002bfa4
+ (id)labelDescriptorWithStringsForCall:(id)arg1 callCount:(long long)arg2;	// IMP=0x000000010002bf04
+ (id)labelDescriptorWithArray:(id)arg1 secondaryString:(id)arg2 layoutState:(unsigned long long)arg3;	// IMP=0x000000010002be48
+ (id)labelDescriptorWithArray:(id)arg1;	// IMP=0x000000010002be34
+ (id)labelDescriptorWithFormat:(id)arg1;	// IMP=0x000000010002bd2c
@property(nonatomic, getter=isDynamic) _Bool dynamic; // @synthesize dynamic=_dynamic;
@property(copy, nonatomic) NSString *localizedSenderIdentity; // @synthesize localizedSenderIdentity=_localizedSenderIdentity;
@property(nonatomic) unsigned long long layoutState; // @synthesize layoutState=_layoutState;
@property(retain, nonatomic) NSString *secondaryString; // @synthesize secondaryString=_secondaryString;
@property(retain, nonatomic) NSArray *strings; // @synthesize strings=_strings;
- (void).cxx_destruct;	// IMP=0x0000000100016258

@end

