//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PHConferenceParticipantCellProtocol.h"
#import "UINavigationBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface PHConferenceParticipantsViewController : UIViewController <UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate, PHConferenceParticipantCellProtocol>
{
    _Bool _showingMultiwayParticipants;	// 8 = 0x8
    NSMutableArray *_conferenceParticipantCalls;	// 16 = 0x10
    NSMutableArray *_remoteParticipantHandles;	// 24 = 0x18
    UITableView *_conferenceTable;	// 32 = 0x20
}

@property(nonatomic, getter=isShowingMultiwayParticipants) _Bool showingMultiwayParticipants; // @synthesize showingMultiwayParticipants=_showingMultiwayParticipants;
@property(retain) UITableView *conferenceTable; // @synthesize conferenceTable=_conferenceTable;
@property(retain) NSMutableArray *remoteParticipantHandles; // @synthesize remoteParticipantHandles=_remoteParticipantHandles;
@property(retain) NSMutableArray *conferenceParticipantCalls; // @synthesize conferenceParticipantCalls=_conferenceParticipantCalls;
- (void).cxx_destruct;	// IMP=0x00000001000875a0
- (void)dismissAfterPrivate;	// IMP=0x00000001000874bc
- (void)conferenceParticipantCellRequestedTakeCallPrivate:(id)arg1;	// IMP=0x000000010008726c
- (void)conferenceParticipantCellRequestedEndCall:(id)arg1;	// IMP=0x00000001000870b8
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000870ac
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;	// IMP=0x00000001000870a4
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100087034
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100086dbc
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100086d40
- (void)removeCall:(id)arg1;	// IMP=0x0000000100086ac8
- (void)handleCallModelChangedNotification:(id)arg1;	// IMP=0x000000010008687c
- (void)callStatusChanged:(id)arg1;	// IMP=0x0000000100086690
- (void)dismissConferenceView;	// IMP=0x0000000100086644
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010008646c
- (void)loadView;	// IMP=0x0000000100086000
- (void)dealloc;	// IMP=0x0000000100085f88
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100085e34

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

