//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "DialerLCDFieldProtocol.h"
#import "PHLCDViewTextFieldDelegate.h"
#import "TPPillViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSArray, NSString, PHLCDViewTextField, TPPillView, UIButton, UILabel;

@interface PHHandsetDialerLCDView : UIView <PHLCDViewTextFieldDelegate, UITextFieldDelegate, TPPillViewDelegate, DialerLCDFieldProtocol>
{
    _Bool _addContactButtonVisible;	// 8 = 0x8
    _Bool _deleteButtonVisible;	// 9 = 0x9
    _Bool _highlighted;	// 10 = 0xa
    _Bool _inCallMode;	// 11 = 0xb
    int _dialerType;	// 12 = 0xc
    UIButton *_addContactButton;	// 16 = 0x10
    UILabel *_contactLabel;	// 24 = 0x18
    id <DialerLCDFieldDelegate> _delegate;	// 32 = 0x20
    PHLCDViewTextField *_numberTextField;	// 40 = 0x28
    NSArray *_numberLabelHorizontalConstraints;	// 48 = 0x30
    TPPillView *_pillView;	// 56 = 0x38
}

@property(retain, nonatomic) TPPillView *pillView; // @synthesize pillView=_pillView;
@property(copy) NSArray *numberLabelHorizontalConstraints; // @synthesize numberLabelHorizontalConstraints=_numberLabelHorizontalConstraints;
@property(retain, nonatomic) PHLCDViewTextField *numberTextField; // @synthesize numberTextField=_numberTextField;
@property(nonatomic) _Bool inCallMode; // @synthesize inCallMode=_inCallMode;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) __weak id <DialerLCDFieldDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) UILabel *contactLabel; // @synthesize contactLabel=_contactLabel;
@property(retain) UIButton *addContactButton; // @synthesize addContactButton=_addContactButton;
@property(nonatomic) int dialerType; // @synthesize dialerType=_dialerType;
- (void).cxx_destruct;	// IMP=0x0000000100026e18
- (void)textFieldDidEndEditing:(id)arg1;	// IMP=0x0000000100026ca8
- (void)textFieldDidBeginEditing:(id)arg1;	// IMP=0x0000000100026c60
- (_Bool)textFieldShouldBeginEditing:(id)arg1;	// IMP=0x0000000100026c04
- (void)addContactPressed:(id)arg1;	// IMP=0x0000000100026be8
- (void)textField:(id)arg1 didUpdateString:(id)arg2;	// IMP=0x0000000100026b68
- (void)textField:(id)arg1 didPasteString:(id)arg2;	// IMP=0x0000000100026a90
- (void)updateNumberLabelHorizontalConstraints;	// IMP=0x00000001000269ac
- (void)applyLayoutConstraints;	// IMP=0x000000010002649c
- (id)newAddContactButton;	// IMP=0x00000001000261e4
- (id)lcdColor;	// IMP=0x00000001000261d0
- (void)handleTapGesture:(id)arg1;	// IMP=0x00000001000260cc
- (void)paste:(id)arg1;	// IMP=0x0000000100025fe0
- (void)copy:(id)arg1;	// IMP=0x0000000100025f68
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x0000000100025ea0
- (_Bool)resignFirstResponder;	// IMP=0x0000000100025e40
- (_Bool)canBecomeFirstResponder;	// IMP=0x0000000100025e38
- (void)_menuDidHide:(id)arg1;	// IMP=0x0000000100025e28
- (void)_requestMakeCutCopyPasteCalloutVisible:(_Bool)arg1;	// IMP=0x0000000100025e1c
- (void)_makeCalloutVisible:(_Bool)arg1;	// IMP=0x0000000100025c70
@property(readonly, nonatomic, getter=isMenuVisible) _Bool menuVisible;
- (void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 label:(id)arg3 suggestion:(_Bool)arg4 animated:(_Bool)arg5;	// IMP=0x0000000100025514
- (id)attributedStringForName:(id)arg1 label:(id)arg2;	// IMP=0x0000000100025288
- (void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 animated:(_Bool)arg3;	// IMP=0x0000000100025228
- (void)setName:(id)arg1 numberLabel:(id)arg2 suggestion:(_Bool)arg3;	// IMP=0x0000000100025184
- (void)setName:(id)arg1 numberLabel:(id)arg2;	// IMP=0x0000000100025130
- (void)insertStringAtCurrentPosition:(id)arg1 deletingPreviousCharacter:(_Bool)arg2;	// IMP=0x0000000100024fdc
- (void)insertStringAtCurrentPosition:(id)arg1;	// IMP=0x0000000100024fcc
- (_Bool)shouldInsertStringAtCurrentPosition:(id)arg1 deletingPreviousCharacter:(_Bool)arg2;	// IMP=0x0000000100024d5c
- (void)deleteCharacter;	// IMP=0x0000000100024cb0
- (void)setText:(id)arg1 needsFormat:(_Bool)arg2;	// IMP=0x0000000100024c98
- (void)setText:(id)arg1 needsFormat:(_Bool)arg2 name:(id)arg3 label:(id)arg4;	// IMP=0x0000000100024c14
- (id)text;	// IMP=0x0000000100024b7c
- (void)endEditing;	// IMP=0x0000000100024b60
- (void)dealloc;	// IMP=0x0000000100024ae8
- (struct CGSize)intrinsicContentSize;	// IMP=0x0000000100024a78
- (void)createPillViewForSenderIdentity:(id)arg1;	// IMP=0x00000001000244bc
- (void)setSenderIdentity:(id)arg1;	// IMP=0x000000010002444c
- (void)pillViewWasTapped:(id)arg1;	// IMP=0x00000001000243b0
- (id)initWithFrame:(struct CGRect)arg1 forDialerType:(int)arg2;	// IMP=0x0000000100023dd4
- (id)generateNumberLabelHorizontalConstraints;	// IMP=0x0000000100023cb4
- (float)addNumberFontSize;	// IMP=0x0000000100023c80
- (double)nameAndLabelFontSize;	// IMP=0x0000000100023c4c
- (id)numberLabelFont;	// IMP=0x0000000100023be8
- (float)spacingBetweenNumberBaselineAndNameBaseline;	// IMP=0x0000000100023bb0
- (float)numberLabelMinimumFontSize;	// IMP=0x0000000100023ba8
- (double)numberLabelMaximumFontSize;	// IMP=0x0000000100023b74

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

