//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CNContactPickerDelegate.h"
#import "CNKFaceTimeMultiwayConversationViewControllerDelegate.h"
#import "CNKStagingAreaViewControllerDelegate.h"
#import "PHAudioRoutingAlertDataSource.h"
#import "PHAudioRoutingAlertDelegate.h"
#import "PHFaceTimePeoplePickerViewControllerDelegate.h"
#import "PHInCallBackgroundStyleProtocol.h"
#import "PHInCallRootViewControllerProtocol.h"
#import "PHInCallSpringBoardEventHandlerProtocol.h"
#import "PHPhoneRemoteViewControllerDelegate.h"
#import "TURouteControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class CNContactPickerViewController, CNKFaceTimeMultiwayConversationViewController, CNKStagingAreaViewController, NSString, PHAudioCallViewController, PHAudioRoutingAlertController, PHEmergencyDialerViewController, PHFaceTimePeoplePickerViewController, PHPhoneRemoteViewController, PHSOSViewController, PHVideoCallViewController, SBUIRemoteAlertButtonAction, TUCall, UINavigationController, UIView;

@interface PHInCallRootViewController : UIViewController <TURouteControllerDelegate, CNContactPickerDelegate, CNKFaceTimeMultiwayConversationViewControllerDelegate, CNKStagingAreaViewControllerDelegate, PHFaceTimePeoplePickerViewControllerDelegate, PHAudioRoutingAlertDataSource, PHAudioRoutingAlertDelegate, PHInCallRootViewControllerProtocol, PHPhoneRemoteViewControllerDelegate, PHInCallBackgroundStyleProtocol, PHInCallSpringBoardEventHandlerProtocol, UIPopoverPresentationControllerDelegate, UINavigationControllerDelegate>
{
    _Bool _dismissalWasDemandedBeforeRemoteViewControllerWasAvailable;	// 8 = 0x8
    long long _alertActivationReason;	// 16 = 0x10
    TUCall *_alertActivationCall;	// 24 = 0x18
    PHAudioCallViewController *_audioCallViewController;	// 32 = 0x20
    PHVideoCallViewController *_videoCallViewController;	// 40 = 0x28
    PHEmergencyDialerViewController *_emergencyDialerViewController;	// 48 = 0x30
    PHSOSViewController *_sosViewController;	// 56 = 0x38
    CNKFaceTimeMultiwayConversationViewController *_multiwayViewController;	// 64 = 0x40
    CNKStagingAreaViewController *_stagingAreaViewController;	// 72 = 0x48
    UIViewController *_currentViewController;	// 80 = 0x50
    UINavigationController *_videoCallNavigationController;	// 88 = 0x58
    CNContactPickerViewController *_contactsViewController;	// 96 = 0x60
    UINavigationController *_audioCallNavigationController;	// 104 = 0x68
    PHFaceTimePeoplePickerViewController *_peoplePickerViewController;	// 112 = 0x70
    PHAudioRoutingAlertController *_routeListController;	// 120 = 0x78
    PHPhoneRemoteViewController *_remoteViewController;	// 128 = 0x80
    UIView *_transportIndicatorView;	// 136 = 0x88
    SBUIRemoteAlertButtonAction *_currentAlertButtonAction;	// 144 = 0x90
}

+ (_Bool)hasDismissalAssertions;	// IMP=0x0000000100016570
+ (id)dismissalAssertions;	// IMP=0x00000001000c838c
+ (void)forceClearAllDismissalAssertions;	// IMP=0x00000001000230a4
+ (_Bool)containsDismissalAssertionForReason:(id)arg1;	// IMP=0x00000001000c8378
+ (void)releaseDismissalAssertionReasons:(id)arg1;	// IMP=0x00000001000c820c
+ (void)releaseDismissalAssertionForReason:(id)arg1;	// IMP=0x00000001000162c8
+ (void)obtainDismissalAssertionForReason:(id)arg1;	// IMP=0x0000000100007674
+ (void)setShouldForceDismiss;	// IMP=0x00000001000c3af0
+ (void)setShouldLockDeviceOnNextDismiss;	// IMP=0x00000001000c3ae0
+ (void)initialize;	// IMP=0x0000000100007270
@property(retain, nonatomic) SBUIRemoteAlertButtonAction *currentAlertButtonAction; // @synthesize currentAlertButtonAction=_currentAlertButtonAction;
@property(retain, nonatomic) UIView *transportIndicatorView; // @synthesize transportIndicatorView=_transportIndicatorView;
@property(retain, nonatomic) PHPhoneRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;
@property(retain, nonatomic) PHAudioRoutingAlertController *routeListController; // @synthesize routeListController=_routeListController;
@property(retain, nonatomic) PHFaceTimePeoplePickerViewController *peoplePickerViewController; // @synthesize peoplePickerViewController=_peoplePickerViewController;
@property(retain) UINavigationController *audioCallNavigationController; // @synthesize audioCallNavigationController=_audioCallNavigationController;
@property(retain, nonatomic) CNContactPickerViewController *contactsViewController; // @synthesize contactsViewController=_contactsViewController;
@property(retain, nonatomic) UINavigationController *videoCallNavigationController; // @synthesize videoCallNavigationController=_videoCallNavigationController;
@property(retain, nonatomic) UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) CNKStagingAreaViewController *stagingAreaViewController; // @synthesize stagingAreaViewController=_stagingAreaViewController;
@property(retain, nonatomic) CNKFaceTimeMultiwayConversationViewController *multiwayViewController; // @synthesize multiwayViewController=_multiwayViewController;
@property(retain, nonatomic) PHSOSViewController *sosViewController; // @synthesize sosViewController=_sosViewController;
@property(retain, nonatomic) PHEmergencyDialerViewController *emergencyDialerViewController; // @synthesize emergencyDialerViewController=_emergencyDialerViewController;
@property(retain, nonatomic) PHVideoCallViewController *videoCallViewController; // @synthesize videoCallViewController=_videoCallViewController;
@property(retain, nonatomic) PHAudioCallViewController *audioCallViewController; // @synthesize audioCallViewController=_audioCallViewController;
@property(retain, nonatomic) TUCall *alertActivationCall; // @synthesize alertActivationCall=_alertActivationCall;
@property long long alertActivationReason; // @synthesize alertActivationReason=_alertActivationReason;
@property _Bool dismissalWasDemandedBeforeRemoteViewControllerWasAvailable; // @synthesize dismissalWasDemandedBeforeRemoteViewControllerWasAvailable=_dismissalWasDemandedBeforeRemoteViewControllerWasAvailable;
- (void).cxx_destruct;	// IMP=0x0000000100023700
- (void)dismissAudioRoutingDeviceListAnimated:(_Bool)arg1;	// IMP=0x00000001000caf3c
- (void)audioRoutingAlertControllerDidDismiss:(id)arg1;	// IMP=0x00000001000caf2c
- (void)audioRoutingAlertController:(id)arg1 didSelectRoute:(id)arg2;	// IMP=0x00000001000cae84
- (id)hideActionTitleForAudioRoutingAlertController:(id)arg1;	// IMP=0x00000001000cae10
- (id)routesForAudioRoutingAlertController:(id)arg1;	// IMP=0x00000001000cad8c
- (void)peoplePicker:(id)arg1 didAddContacts:(id)arg2 addresses:(id)arg3;	// IMP=0x00000001000ca59c
- (void)peoplePickerDidCancel:(id)arg1;	// IMP=0x00000001000ca580
- (void)didRequestTransitionToCanvasFromStagingAreaViewController:(id)arg1;	// IMP=0x00000001000ca388
- (_Bool)contact:(id)arg1 hasEmailAddressInSet:(id)arg2;	// IMP=0x00000001000ca188
- (id)existingLowercaseAddressesForFrontmostCall;	// IMP=0x00000001000c9d88
- (void)presentRoutePickerViewControllerFrom:(id)arg1;	// IMP=0x00000001000c9ae4
- (void)presentPeoplePickerViewController;	// IMP=0x00000001000c997c
- (void)viewController:(id)arg1 setStatusBarHidden:(_Bool)arg2;	// IMP=0x00000001000c9964
- (void)viewControllerDidRequestRoutePickerFrom:(id)arg1;	// IMP=0x00000001000c9958
- (void)viewControllerDidRequestAddParticipants:(id)arg1;	// IMP=0x00000001000c9894
- (void)contactPickerDidCancel:(id)arg1;	// IMP=0x00000001000c9888
- (void)routesChangedForRouteController:(id)arg1;	// IMP=0x00000001000c9834
- (_Bool)prefersStatusBarHidden;	// IMP=0x00000001000c982c
- (id)childViewControllerForHomeIndicatorAutoHidden;	// IMP=0x00000001000c9820
- (id)_childViewControllerForWhitePointAdaptivityStyle;	// IMP=0x00000001000c9814
- (void)animateToAlert;	// IMP=0x00000001000c95b4
- (void)updateTransportIndicatorView;	// IMP=0x00000001000c90f4
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;	// IMP=0x00000001000c9050
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;	// IMP=0x00000001000c8fb0
- (void)resetStatusBarStyleOverrides;	// IMP=0x000000010001d90c
- (void)setInCallStatusBarStyleOverride;	// IMP=0x00000001000c8ef8
- (void)updateDesiredSpringboardBehavior;	// IMP=0x000000010001458c
- (void)handleDoubleHeightStatusBarTap;	// IMP=0x00000001000c8ec4
- (void)handleHeadsetButtonPressed:(_Bool)arg1;	// IMP=0x00000001000c8d34
- (void)handleVolumeDownButtonPressed;	// IMP=0x00000001000c8bfc
- (void)handleVolumeUpButtonPressed;	// IMP=0x00000001000c8ac4
- (void)handleLockButtonPressed;	// IMP=0x00000001000c898c
- (void)handleActivationForEndAndLock;	// IMP=0x00000001000c84d4
- (void)pullRelayingCallsIfNecessary;	// IMP=0x000000010001d9c4
- (void)releaseIdleTimerAssertionWithComment:(id)arg1;	// IMP=0x000000010000a3ec
- (void)obtainIdleTimerAssertionWithComment:(id)arg1;	// IMP=0x00000001000c8398
- (void)dismissalAssertionReleasedNotification:(id)arg1;	// IMP=0x0000000100016418
- (void)setStatusBarHidden:(_Bool)arg1 withDuration:(double)arg2;	// IMP=0x000000010001f260
- (void)setBackgroundStyle:(long long)arg1 animatedWithDuration:(double)arg2;	// IMP=0x00000001000c81b4
- (void)viewServiceDidTerminateWithError:(id)arg1;	// IMP=0x00000001000c8020
- (void)dismissPhoneRemoteViewControllerAnimated:(_Bool)arg1;	// IMP=0x00000001000211f8
- (void)dismissPhoneRemoteViewController;	// IMP=0x00000001000211e8
- (void)presentPhoneRemoteViewControllerForView:(id)arg1;	// IMP=0x00000001000c7940
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;	// IMP=0x00000001000c785c
- (id)callForVideoCallBasedViewController:(id)arg1;	// IMP=0x00000001000c7790
- (void)transitionToVideoCallBasedViewController:(id)arg1;	// IMP=0x00000001000c70ec
- (struct CGRect)preferredPIPContentRect;	// IMP=0x00000001000c6ed0
- (void)updateMultiwayDeviceOrientation:(long long)arg1;	// IMP=0x00000001000c6e20
- (void)didChangeDeviceOrientationNotification:(id)arg1;	// IMP=0x00000001000c6d50
- (void)mostRecentlyDisconnectedCallDidClearNotification:(id)arg1;	// IMP=0x00000001000217a4
- (void)emergencyCallbackModeChangedNotification:(id)arg1;	// IMP=0x00000001000c6bd0
- (void)updateAlertActivationReasonForCall:(id)arg1;	// IMP=0x0000000100020fdc
- (void)updateAlertActivationReason;	// IMP=0x000000010001db74
- (void)updateSwipeDismissalStyleForCall:(id)arg1;	// IMP=0x00000001000c6b28
- (void)dismissContactsViewControllerAnimated:(_Bool)arg1;	// IMP=0x00000001000213d4
- (void)dismissContactsViewController;	// IMP=0x00000001000213c4
- (void)willRotate:(id)arg1;	// IMP=0x00000001000c691c
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;	// IMP=0x00000001000c6804
- (void)prepareForPopoverPresentation:(id)arg1;	// IMP=0x00000001000c6628
- (void)presentAsPopover:(id)arg1 fromView:(id)arg2;	// IMP=0x00000001000c6430
- (void)presentContactsViewControllerForView:(id)arg1;	// IMP=0x00000001000c620c
- (void)animateOutWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021ae0
- (void)animateInWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000c60e0
- (void)prepareForDismissal;	// IMP=0x0000000100021dc4
- (void)requestInCallDismissalWithAnimation:(_Bool)arg1;	// IMP=0x0000000100021834
- (id)_remoteViewControllerProxy;	// IMP=0x000000010000a4fc
- (void)viewDidMoveToWindow:(id)arg1 shouldAppearOrDisappear:(_Bool)arg2;	// IMP=0x000000010000a660
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100023394
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100022ff8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010001e9b8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010001d5ec
- (void)printUI;	// IMP=0x00000001000c5f98
- (void)loadView;	// IMP=0x0000000100007be8
- (void)_transitionFromViewController:(id)arg1 toViewController:(id)arg2;	// IMP=0x000000010000a0dc
- (void)updateCallControllerForCurrentState;	// IMP=0x0000000100007d4c
- (_Bool)shouldShowSOS;	// IMP=0x00000001000c5c54
- (void)callViewControllerStateChangedNotification:(id)arg1;	// IMP=0x0000000100014580
- (void)pipControllerDidRequestReturnToFullScreenNotification:(id)arg1;	// IMP=0x00000001000c5c48
- (void)crossFadeFrom:(id)arg1 toViewController:(id)arg2 addingViewController:(_Bool)arg3;	// IMP=0x00000001000c5800
- (void)handlePIPWillCancelNotification:(id)arg1;	// IMP=0x00000001000c56d4
- (void)pipStateChangedNotification:(id)arg1;	// IMP=0x00000001000c5354
- (void)callContinuityChangedNotification:(id)arg1;	// IMP=0x00000001000c51f8
- (void)remoteParticipantHandlesChanged:(id)arg1;	// IMP=0x00000001000c5008
- (void)callDowngradedToAudioNotification:(id)arg1;	// IMP=0x00000001000c4f74
- (void)videoCallStateChangedNotification:(id)arg1;	// IMP=0x00000001000c4e20
- (void)callStateChangedNotification:(id)arg1;	// IMP=0x0000000100020e98
- (_Bool)shouldShowNavigationBarForViewController:(id)arg1;	// IMP=0x00000001000c4d14
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x00000001000c4b68
- (void)_loadStagingAreaViewControllerForCall:(id)arg1 hasJoined:(_Bool)arg2;	// IMP=0x00000001000c49e4
- (void)_loadMultiwayViewControllerForCall:(id)arg1;	// IMP=0x00000001000c4808
- (void)_loadAudioCallViewController;	// IMP=0x0000000100009998
- (void)_loadVideoCallViewController;	// IMP=0x00000001000c4638
- (void)_loadSOSViewController;	// IMP=0x00000001000c4564
- (void)_reloadSOSHandles;	// IMP=0x00000001000c4510
- (id)sosHandles;	// IMP=0x00000001000c41cc
- (void)_logAggdMetricsForCall:(id)arg1;	// IMP=0x0000000100007ab4
- (void)dealloc;	// IMP=0x0000000100023500
- (void)_willAppearInRemoteViewController:(id)arg1;	// IMP=0x000000010001d024
- (void)registerForNotifications;	// IMP=0x0000000100007774
- (void)showSOSDisconnectConfirmation:(CDUnknownBlockType)arg1;	// IMP=0x00000001000c3ecc
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000072e4
- (void)sendResponseIfNecessaryWithUnhandledEvents:(unsigned long long)arg1;	// IMP=0x00000001000c3bac
- (void)forceUpdateCallControllerForSOS;	// IMP=0x00000001000c3b58
- (void)_testing_finishedAnimatingIn;	// IMP=0x000000010001eadc
- (void)_testing_viewDidAppear;	// IMP=0x000000010001ea58
- (void)_testing_viewWillAppear;	// IMP=0x000000010001d844

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

