//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHAbstractCallParticipantLabelView.h"

@class NSLayoutConstraint, UIActivityIndicatorView, UIButton, UILabel;

@interface PHMultipleCallParticipantLabelView : PHAbstractCallParticipantLabelView
{
    NSLayoutConstraint *_participantMarqueeLabelRightConstraint;	// 8 = 0x8
    UILabel *_statusLabel;	// 16 = 0x10
    NSLayoutConstraint *_statusLabelRightConstraint;	// 24 = 0x18
    UIActivityIndicatorView *_progressSpinner;	// 32 = 0x20
    UIButton *_conferenceParticipantsButton;	// 40 = 0x28
}

@property(retain) UIButton *conferenceParticipantsButton; // @synthesize conferenceParticipantsButton=_conferenceParticipantsButton;
@property(retain) UIActivityIndicatorView *progressSpinner; // @synthesize progressSpinner=_progressSpinner;
@property(retain) NSLayoutConstraint *statusLabelRightConstraint; // @synthesize statusLabelRightConstraint=_statusLabelRightConstraint;
@property(retain) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain) NSLayoutConstraint *participantMarqueeLabelRightConstraint; // @synthesize participantMarqueeLabelRightConstraint=_participantMarqueeLabelRightConstraint;
- (void).cxx_destruct;	// IMP=0x00000001000284f0
- (void)infoButtonTapped:(id)arg1;	// IMP=0x000000010002841c
- (void)setShowsInfoButton:(_Bool)arg1;	// IMP=0x00000001000280c8
- (void)setHidesLabel:(_Bool)arg1;	// IMP=0x000000010002802c
- (double)labelAlphaValueForActivityState:(unsigned short)arg1;	// IMP=0x0000000100028018
- (void)setActivityState:(unsigned short)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100027da4
- (void)setActivityState:(unsigned short)arg1;	// IMP=0x0000000100027d94
- (void)setTextColor:(id)arg1;	// IMP=0x0000000100027d18
- (void)setShowsActivitySpinner:(_Bool)arg1;	// IMP=0x0000000100027a24
- (void)setLabelDescriptor:(id)arg1;	// IMP=0x000000010002798c
- (struct CGSize)intrinsicContentSize;	// IMP=0x0000000100027978
- (void)dealloc;	// IMP=0x0000000100027900
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000273fc

@end

