//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface PHSublayerResizingView : UIView
{
}

+ (Class)layerClass;	// IMP=0x00000001000607c0
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x00000001000607d4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010006078c

@end

