//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TUHandle.h"

@interface TUHandle (PhoneKit)
+ (long long)handleTypeForRecentCall:(id)arg1;	// IMP=0x00000001000ee8bc
+ (id)handleForRecentCall:(id)arg1;	// IMP=0x00000001000ee804
@end

