//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CALayer, MAGFilterSetChangeSubscription, MAGNamedFilterSet, NSDictionary, UISwipeGestureRecognizer, UITapGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface MAGFilterLabelDial : UIControl
{
    MAGNamedFilterSet *_selectedFilterSet;	// 8 = 0x8
    NSDictionary *_filterSetToLabelMap;	// 16 = 0x10
    UIView *_meshView;	// 24 = 0x18
    UIView *_labelContainer;	// 32 = 0x20
    CALayer *_maskLayer;	// 40 = 0x28
    UISwipeGestureRecognizer *_rightSwipeGestureRecognizer;	// 48 = 0x30
    UISwipeGestureRecognizer *_leftSwipeGestureRecognizer;	// 56 = 0x38
    UITapGestureRecognizer *_tapGestureRecognizer;	// 64 = 0x40
    MAGFilterSetChangeSubscription *_changeSubscription;	// 72 = 0x48
}

@property(retain, nonatomic) MAGFilterSetChangeSubscription *changeSubscription; // @synthesize changeSubscription=_changeSubscription;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UISwipeGestureRecognizer *leftSwipeGestureRecognizer; // @synthesize leftSwipeGestureRecognizer=_leftSwipeGestureRecognizer;
@property(retain, nonatomic) UISwipeGestureRecognizer *rightSwipeGestureRecognizer; // @synthesize rightSwipeGestureRecognizer=_rightSwipeGestureRecognizer;
@property(retain, nonatomic) CALayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) UIView *labelContainer; // @synthesize labelContainer=_labelContainer;
@property(retain, nonatomic) UIView *meshView; // @synthesize meshView=_meshView;
@property(retain, nonatomic) NSDictionary *filterSetToLabelMap; // @synthesize filterSetToLabelMap=_filterSetToLabelMap;
@property(retain, nonatomic) MAGNamedFilterSet *selectedFilterSet; // @synthesize selectedFilterSet=_selectedFilterSet;
- (void).cxx_destruct;	// IMP=0x000000010001b2c0
- (void)accessibilityDecrement;	// IMP=0x000000010001b100
- (void)accessibilityIncrement;	// IMP=0x000000010001b070
- (unsigned long long)accessibilityTraits;	// IMP=0x000000010001b02c
- (id)accessibilityLabel;	// IMP=0x000000010001b020
- (id)accessibilityValue;	// IMP=0x000000010001afcc
- (_Bool)isAccessibilityElement;	// IMP=0x000000010001afc4
- (void)positionLabels;	// IMP=0x000000010001ad58
- (void)setSelectedFilterSet:(id)arg1 animated:(_Bool)arg2;	// IMP=0x000000010001aa88
- (void)setSelectedFilterSet:(id)arg1 animated:(_Bool)arg2 sendActions:(_Bool)arg3;	// IMP=0x000000010001a97c
- (void)tapped:(id)arg1;	// IMP=0x000000010001a710
- (void)leftSwipeFired:(id)arg1;	// IMP=0x000000010001a680
- (void)rightSwipeFired:(id)arg1;	// IMP=0x000000010001a5f0
- (id)previousFilterSet;	// IMP=0x000000010001a4c8
- (id)nextFilterSet;	// IMP=0x000000010001a350
- (void)layoutSubviews;	// IMP=0x0000000100019d94
- (void)tintColorDidChange;	// IMP=0x0000000100019ca0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000189cc
- (id)_horizontalMeshTransform;	// IMP=0x000000010001892c
- (struct CGSize)_interpolatedHorizontalMeshTransformSize;	// IMP=0x0000000100018804

@end

