//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

__attribute__((visibility("hidden")))
@interface MAGFocusIndicatorView : UIView
{
}

- (void)animateToHidden;	// IMP=0x000000010000d7f0
- (void)animateToShown;	// IMP=0x000000010000d7ec
- (void)willBeHidden;	// IMP=0x000000010000d7e8
- (void)willBeShown;	// IMP=0x000000010000d7e4

@end

