//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MAGControlPanel;

@protocol MAGLiveViewControlPanelDelegate <NSObject>
- (void)zoomSliderValueChanged:(double)arg1 forControlPanel:(MAGControlPanel *)arg2;
- (void)torchModeChangedTo:(_Bool)arg1 forControlPanel:(MAGControlPanel *)arg2;
- (void)filtersButtonLongPressedForControlPanel:(MAGControlPanel *)arg1;
- (void)filtersButtonPressedForControlPanel:(MAGControlPanel *)arg1;
- (void)snapshotButtonPressedForControlPanel:(MAGControlPanel *)arg1;
- (void)manualFocusChangedTo:(_Bool)arg1 forControlPanel:(MAGControlPanel *)arg2;
@end

