//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SFActivityViewControllerDelegate.h"

@class ActionPanel, MFMailComposeViewController;

@protocol ActionPanelDelegate <_SFActivityViewControllerDelegate>
- (void)actionPanel:(ActionPanel *)arg1 prepareForMailActivityWithMailController:(MFMailComposeViewController *)arg2 completionHandler:(void (^)(void))arg3;
- (void)actionPanelAddTabDocumentToReadingList:(ActionPanel *)arg1 completion:(void (^)(_Bool))arg2;
@end

