//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SFActivityItemProvider.h"

@class TabDocument;

@interface ActionPanelActivityItemProvider : _SFActivityItemProvider
{
    TabDocument *_tabDocument;	// 24 = 0x18
}

@property(readonly, nonatomic) TabDocument *tabDocument; // @synthesize tabDocument=_tabDocument;
- (void).cxx_destruct;	// IMP=0x000000010008c10c
- (id)activityViewController:(id)arg1 thumbnailImageForActivityType:(id)arg2 suggestedSize:(struct CGSize)arg3;	// IMP=0x000000010008c018
- (id)initWithPlaceholderItem:(id)arg1 URL:(id)arg2 pageTitle:(id)arg3;	// IMP=0x000000010008c000
- (id)initWithTabDocument:(id)arg1;	// IMP=0x000000010008bf7c
- (id)initWithPlaceholderItem:(id)arg1 tabDocument:(id)arg2;	// IMP=0x000000010008be74

@end

