//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SFActivity.h"

@class TabDocument;

@interface Activity : _SFActivity
{
    TabDocument *_tabDocument;	// 8 = 0x8
}

@property(readonly, nonatomic) TabDocument *tabDocument; // @synthesize tabDocument=_tabDocument;
- (void).cxx_destruct;	// IMP=0x0000000100037018
- (id)init;	// IMP=0x0000000100036ff8
- (id)initWithTabDocument:(id)arg1;	// IMP=0x0000000100036f5c

@end

