//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "BrowserWindowControllerDelegate.h"
#import "BrowserWindowControllerObserving.h"
#import "MCProfileConnectionObserver.h"
#import "MobileSafariWindowDelegate.h"
#import "PageLoadTestRunnerDelegate.h"
#import "TabSnapshotCacheStressTestRunnerDelegate.h"
#import "UIApplicationDelegate.h"
#import "WBDatabaseLockAcquisitorDelegate.h"

@class ApplicationShortcutController, BookmarksDatabaseHealthReporter, BrowserContainerViewController, BrowserController, BrowserWindowController, DragOverlayViewController, MobileSafariWindow, NSArray, NSDictionary, NSString, SBSAssertion, TabDocument, UIWindow, WBDatabaseLockAcquisitor, WBSCloudHistory, WBSCyclerConnectionManager, WBSFormAutoFillCorrectionsHistoryObserver;

@interface Application : UIApplication <PageLoadTestRunnerDelegate, TabSnapshotCacheStressTestRunnerDelegate, BrowserWindowControllerDelegate, BrowserWindowControllerObserving, MCProfileConnectionObserver, MobileSafariWindowDelegate, WBDatabaseLockAcquisitorDelegate, UIApplicationDelegate>
{
    _Bool _isReadingDefaults;	// 8 = 0x8
    _Bool _shouldReadDefaultsOnResume;	// 9 = 0x9
    _Bool _isRunningShowBookmarksTest;	// 10 = 0xa
    _Bool _startedBookmarksTest;	// 11 = 0xb
    _Bool _isRunningCanvasTest;	// 12 = 0xc
    _Bool _willEnterSuspendedState;	// 13 = 0xd
    _Bool _shouldPrepareTabDocumentForNewUserActivityWhenFinishedLaunching;	// 14 = 0xe
    _Bool _finishedLaunching;	// 15 = 0xf
    WBSCloudHistory *_cloudHistory;	// 16 = 0x10
    _Bool _resigningActive;	// 24 = 0x18
    _Bool _shouldAnimateOpeningExternalURL;	// 25 = 0x19
    long long _currentKeyboardModifierFlags;	// 32 = 0x20
    ApplicationShortcutController *_shortcutController;	// 40 = 0x28
    UIWindow *_obfuscationWindow;	// 48 = 0x30
    NSDictionary *_openURLPayload;	// 56 = 0x38
    MobileSafariWindow *_window;	// 64 = 0x40
    BrowserContainerViewController *_containerViewController;	// 72 = 0x48
    DragOverlayViewController *_dragOverlayViewController;	// 80 = 0x50
    UIWindow *_dragWindow;	// 88 = 0x58
    id <DragInteractionDriver> _dragInteractionDriver;	// 96 = 0x60
    WBSFormAutoFillCorrectionsHistoryObserver *_formAutoFillCorrectionsHistoryObserver;	// 104 = 0x68
    BookmarksDatabaseHealthReporter *_bookmarksDatabaseHealthReporter;	// 112 = 0x70
    unsigned long long _bookmarksDatabaseBackgroundTaskIdentifier;	// 120 = 0x78
    WBDatabaseLockAcquisitor *_bookmarksDatabaseBackgroundTaskLockAcquisitor;	// 128 = 0x80
    SBSAssertion *_wallpaperSuspensionAssertion;	// 136 = 0x88
    WBSCyclerConnectionManager *_cyclerConnectionManager;	// 144 = 0x90
    BrowserWindowController *_browserWindowController;	// 152 = 0x98
    TabDocument *_tabDocumentPendingUserActivityPayload;	// 160 = 0xa0
}

+ (unsigned long long)systemMemorySize;	// IMP=0x000000010000d838
+ (void)initialize;	// IMP=0x000000010000bf6c
+ (id)sharedApplication;	// IMP=0x000000010000bf5c
+ (id)sharedTestRunner;	// IMP=0x0000000100020df4
+ (void)commandLineTestOption:(int)arg1 arg:(const char *)arg2;	// IMP=0x0000000100018774
+ (void)postTestNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;	// IMP=0x0000000100023ad0
+ (void)postTestNotificationName:(id)arg1 object:(id)arg2;	// IMP=0x0000000100023a7c
@property(nonatomic) __weak TabDocument *tabDocumentPendingUserActivityPayload; // @synthesize tabDocumentPendingUserActivityPayload=_tabDocumentPendingUserActivityPayload;
@property(retain, nonatomic) WBSCloudHistory *cloudHistory; // @synthesize cloudHistory=_cloudHistory;
@property(readonly, nonatomic) BrowserWindowController *browserWindowController; // @synthesize browserWindowController=_browserWindowController;
- (void).cxx_destruct;	// IMP=0x0000000100011d58
- (void)_reloadContainerViewController;	// IMP=0x0000000100011ca4
- (void)windowControllerDidReplaceWindows:(id)arg1;	// IMP=0x0000000100011c98
- (void)windowController:(id)arg1 didRemoveWindow:(id)arg2;	// IMP=0x0000000100011c8c
- (void)windowController:(id)arg1 didAddWindow:(id)arg2 withSourceInfo:(id)arg3;	// IMP=0x0000000100011ae4
- (long long)resolveUnspecifiedPositionForBrowserWindowController:(id)arg1;	// IMP=0x0000000100011abc
- (void)safariWindow:(id)arg1 didEndAllTouchesAtPoint:(struct CGPoint)arg2;	// IMP=0x00000001000119e0
- (void)safariWindow:(id)arg1 statusBarChangedFromHeight:(double)arg2 toHeight:(double)arg3;	// IMP=0x0000000100011928
- (void)_getBookmarksDataClassEnabledWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100011778
- (void)_updateCloudFeatureAvailability;	// IMP=0x0000000100011424
- (void)_prepareTabDocumentForNewUserActivity;	// IMP=0x0000000100011254
- (void)_export30DaysWorthOfHistoryAfterUpgrade;	// IMP=0x0000000100010f44
@property(retain, nonatomic) UIWindow *window;
- (void)applicationWillTerminate;	// IMP=0x0000000100007008
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x000000010000f940
- (void)endDragInteractionWithPoint:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000f700
- (void)updateDragInteractionWithPoint:(struct CGPoint)arg1;	// IMP=0x000000010000f620
- (void)beginDragInteractionWithDragContext:(id)arg1;	// IMP=0x000000010000f3bc
- (_Bool)canBeginNewDragInteraction;	// IMP=0x000000010000f1e4
- (void)updateTabCount;	// IMP=0x000000010000f178
- (void)auditTabCount;	// IMP=0x000000010000f13c
- (_Bool)canAddNewTabForPrivateBrowsing:(_Bool)arg1;	// IMP=0x000000010000f09c
@property(readonly, nonatomic) unsigned long long maximumTabCount;
- (unsigned long long)_maximumTabCount;	// IMP=0x000000010000efdc
- (unsigned long long)_numberOfTabsForPrivateBrowsing:(_Bool)arg1;	// IMP=0x000000010000ee38
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010000eb30
- (void)_addDefaultsObserver;	// IMP=0x000000010000e7e0
- (void)_managedProfileConfigurationDidUpdate;	// IMP=0x000000010000e77c
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;	// IMP=0x000000010000e770
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;	// IMP=0x000000010000e764
- (void)_setHandlingURL:(_Bool)arg1 url:(id)arg2;	// IMP=0x000000010000e6cc
- (void)_appleKeyboardsChanged:(id)arg1;	// IMP=0x000000010000e6c0
- (void)_reloadSearchEngines;	// IMP=0x000000010000e658
- (void)userDefaultsDidChange:(id)arg1;	// IMP=0x000000010000447c
- (id)_openURLInNewTab:(id)arg1 withOptions:(id)arg2;	// IMP=0x000000010000e50c
@property(readonly, nonatomic) ApplicationShortcutController *shortcutController;
- (void)handleKeyUIEvent:(id)arg1;	// IMP=0x000000010000e3b4
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010000e2e8
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010000dcc0
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;	// IMP=0x000000010000dc5c
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;	// IMP=0x000000010000db20
- (void)_applicationOpenURLAction:(id)arg1 payload:(id)arg2 origin:(id)arg3;	// IMP=0x000000010000da50
- (void)applicationOpenURL:(id)arg1;	// IMP=0x000000010000d8ec
- (void)_saveBrowserState;	// IMP=0x000000010000d820
- (void)didReceiveMemoryWarning;	// IMP=0x000000010000d630
- (void)_saveNSURLCacheToDiskInBackground:(_Bool)arg1;	// IMP=0x0000000100006c94
- (void)databaseLockAcquisitor:(id)arg1 acquiredLock:(_Bool)arg2;	// IMP=0x000000010000d1c0
- (void)_performBookmarksDatabaseTasksInBackground;	// IMP=0x000000010000ce48
- (void)_suspendOrResumeWallpaperAnimationIfNeeded;	// IMP=0x000000010000cd88
- (void)_endObfuscation;	// IMP=0x000000010000cd38
- (void)_beginObfuscation;	// IMP=0x000000010000cc2c
- (void)_reportBookmarksDatabaseHealth;	// IMP=0x000000010000cbc4
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0000000100006a8c
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x000000010000ca00
- (void)clearReaderViewsExceptMultiplePageReader:(_Bool)arg1;	// IMP=0x0000000100006e00
- (_Bool)shouldReportForegroundTabCrash;	// IMP=0x000000010000c7ec
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0000000100005c78
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x000000010000699c
- (void)_updateKeyboardCorrectionLearningAllowed;	// IMP=0x000000010000c584
- (void)saveChangesToCloudHistoryStore;	// IMP=0x000000010000c528
- (void)_application:(id)arg1 statusBarTouchesEnded:(id)arg2;	// IMP=0x000000010000c43c
- (void)_applicationWillSuspend:(id)arg1;	// IMP=0x000000010000c41c
- (void)_readDefaults;	// IMP=0x0000000100005a0c
- (_Bool)_shouldObfuscateOnSuspend;	// IMP=0x000000010000c2e4
@property(readonly, nonatomic) _Bool usesPrivateBrowsingModeInAnyWindow;
@property(readonly, nonatomic) _Bool usesDefaultBrowsingModeInAllWindows;
- (id)_focusedBrowserController;	// IMP=0x000000010000c020
- (id)_browserControllerForExternalNavigation;	// IMP=0x000000010000c014
@property(readonly, nonatomic) BrowserController *primaryBrowserController;
@property(readonly, nonatomic) NSArray *browserControllers;
- (_Bool)runMemoryOrIOTestWithType:(unsigned long long)arg1;	// IMP=0x0000000100023854
- (_Bool)startHistoryLoadTest;	// IMP=0x00000001000236c8
- (id)_generateMemoryFootprintResults:(id)arg1;	// IMP=0x0000000100022dfc
- (_Bool)startHistoryTest;	// IMP=0x0000000100022998
- (_Bool)_resetHistoryWithCompressedDatabaseAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002232c
- (void)_doSearchTestOnCVC:(id)arg1 WithTestStrings:(id)arg2 andDispatchGroup:(id)arg3;	// IMP=0x0000000100021eec
- (void)startSearchPerformanceUnifiedFieldKeyTimeTest;	// IMP=0x0000000100021a40
- (void)startSearchPerformanceTestWithTestStrings:(id)arg1;	// IMP=0x0000000100020eb4
- (void)startSearchPerformanceTest;	// IMP=0x0000000100020e00
- (_Bool)didStartBookmarksTest;	// IMP=0x0000000100020de0
- (_Bool)isRunningCanvasTest;	// IMP=0x0000000100003c54
- (_Bool)isRunningShowBookmarksTest;	// IMP=0x0000000100009ab4
- (void)runSplitViewTest;	// IMP=0x0000000100020ae4
- (void)runBookmarksViewTest;	// IMP=0x0000000100020888
- (void)_switchToBookmarksCollectionForTestNamed:(id)arg1;	// IMP=0x00000001000205f0
- (id)_scrollViewForTestNamed:(id)arg1;	// IMP=0x0000000100020388
- (void)_populateInMemoryBookmarksDBForTestNamed:(id)arg1;	// IMP=0x000000010001feb8
- (void)finishedBookmarksTest;	// IMP=0x000000010001fde4
- (void)startBookmarksTest;	// IMP=0x000000010001fd44
- (_Bool)prepareBookmarksTest;	// IMP=0x000000010001fca4
- (void)_runTabOverviewScrollPerfTest;	// IMP=0x000000010001f7d8
- (void)_runTabOverviewPresentingAndDismissalTest;	// IMP=0x000000010001f330
- (void)_runTabOverviewOpenNewTabTest;	// IMP=0x000000010001ed98
- (void)runTabOverviewTest;	// IMP=0x000000010001ea9c
- (void)_runTabBarSwitchTabTest;	// IMP=0x000000010001e89c
- (_Bool)startTabBarTest;	// IMP=0x000000010001e2bc
- (id)_syntheticHTMLString;	// IMP=0x000000010001e290
- (void)finishedCanvasTestWithURL:(id)arg1 forTabDocument:(id)arg2;	// IMP=0x000000010001de50
- (void)_pollCanvasTest:(id)arg1;	// IMP=0x000000010001dd2c
- (_Bool)startCanvasTest:(id)arg1;	// IMP=0x000000010001dbf0
- (void)failedPurpleTestWithError:(id)arg1;	// IMP=0x000000010001db3c
- (void)finishedPurpleTest:(id)arg1;	// IMP=0x000000010001daa0
- (void)startedPurpleTest;	// IMP=0x00000001000082fc
- (void)_runSidebarTest;	// IMP=0x000000010001d6a8
- (_Bool)startSidebarTest;	// IMP=0x000000010001d410
- (void)startTabViewScrollTest;	// IMP=0x000000010001d30c
- (void)_prepareTabViewScrollTest;	// IMP=0x000000010001d28c
- (void)prepareTabViewScrollTest;	// IMP=0x000000010001d214
- (void)startTabViewRotationTest;	// IMP=0x000000010001d0cc
- (void)_prepareTabViewRotationTest;	// IMP=0x000000010001d020
- (void)prepareTabViewRotationTest;	// IMP=0x000000010001cfa8
- (void)startTabViewCloseTest;	// IMP=0x000000010001c970
- (void)_prepareTabViewCloseTest;	// IMP=0x000000010001c8c4
- (void)prepareTabViewCloseTest;	// IMP=0x000000010001c84c
- (void)startTabViewSelectTest;	// IMP=0x000000010001c644
- (void)_prepareTabViewSelectTest;	// IMP=0x000000010001c168
- (void)prepareTabViewSelectTest;	// IMP=0x000000010001c0f0
- (void)startTabViewOpenTest;	// IMP=0x000000010001bfec
- (void)_prepareTabViewOpenTest;	// IMP=0x000000010001ba5c
- (void)prepareTabViewOpenTest;	// IMP=0x000000010001b9e4
- (void)startTabViewBringUpTest;	// IMP=0x000000010001b8d0
- (void)_prepareTabViewBringUpTest;	// IMP=0x000000010001b2dc
- (void)prepareTabViewBringUpTest;	// IMP=0x000000010001b264
- (void)_loadTabsForTesting:(unsigned long long)arg1 presentTabView:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001adb8
- (void)loadTabsForTesting:(unsigned long long)arg1 presentTabView:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001acfc
- (void)loadTabsForTesting:(unsigned long long)arg1 presentTabView:(_Bool)arg2;	// IMP=0x000000010001aad4
- (void)runGeneratePasswordTest;	// IMP=0x000000010001a908
- (void)runLargeFormTypingTest;	// IMP=0x000000010001a844
- (void)_runFormTypingTextWithSetupScript:(id)arg1;	// IMP=0x000000010001a210
- (void)_typeTextInForm:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019f58
- (void)runLargeFormFocusTest;	// IMP=0x0000000100019d30
- (void)_loadLargeForm:(CDUnknownBlockType)arg1;	// IMP=0x0000000100019ce8
- (void)_loadAlternateHTMLString:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019a48
- (void)loadBlankPageforKeyboardTests;	// IMP=0x0000000100019920
- (void)startKeyboardRotationTest;	// IMP=0x0000000100019738
- (void)startKeyboardBringupTest;	// IMP=0x0000000100019568
- (void)startKeyboardSplitAndMergeTest;	// IMP=0x0000000100019438
- (void)_observeNotificationOnce:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019188
- (_Bool)runTest:(id)arg1 options:(id)arg2;	// IMP=0x0000000100005dbc
- (id)_numberOption:(id)arg1;	// IMP=0x0000000100018fa8
- (void)checkExtendedLaunchPageLoad:(id)arg1 forTabDocument:(id)arg2;	// IMP=0x0000000100018e08
- (id)_extendLaunchTest;	// IMP=0x0000000100018dec
- (_Bool)overrideBrowserStateForTestNamed:(id)arg1 existingUUID:(id)arg2;	// IMP=0x0000000100018a24
- (void)startCommandLineTest;	// IMP=0x0000000100018970
- (id)_browserControllerForApplicationTesting;	// IMP=0x0000000100018720
- (void)pageLoadTestRunnerFinished:(id)arg1;	// IMP=0x0000000100023a30
- (void)tabSnapshotCacheStressTestRunnerDidFinish:(id)arg1;	// IMP=0x0000000100023c74
- (void)runTabSnapshotCacheStressTest;	// IMP=0x0000000100023b8c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

