//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WBSCloudBookmarksDeviceEligibilityFetcher.h"

@class ACAccountStore, NSString;

@interface CloudBookmarksDeviceEligibilityFetcher : NSObject <WBSCloudBookmarksDeviceEligibilityFetcher>
{
    ACAccountStore *_accountStore;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000692d8
- (void)fetchDeviceEligibilityInformationWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100069068
- (id)initWithAccountStore:(id)arg1;	// IMP=0x0000000100068fcc
- (id)init;	// IMP=0x0000000100068f68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

