//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class VibrantLabelView, VibrantSeparatorView;

@interface FrequentlyVisitedSitesSectionHeaderView : UIView
{
    _Bool _isInLayoutSubviews;	// 8 = 0x8
    double _requiredHeight;	// 16 = 0x10
    double _labelHeight;	// 24 = 0x18
    VibrantLabelView *_frequentlyVisitedSitesLabel;	// 32 = 0x20
    VibrantSeparatorView *_separatorView;	// 40 = 0x28
    double _labelLeftInset;	// 48 = 0x30
    CDUnknownBlockType _updateOnLayout;	// 56 = 0x38
}

@property(copy, nonatomic) CDUnknownBlockType updateOnLayout; // @synthesize updateOnLayout=_updateOnLayout;
@property(nonatomic) double labelLeftInset; // @synthesize labelLeftInset=_labelLeftInset;
@property(readonly, nonatomic) VibrantSeparatorView *separatorView; // @synthesize separatorView=_separatorView;
@property(readonly, nonatomic) VibrantLabelView *frequentlyVisitedSitesLabel; // @synthesize frequentlyVisitedSitesLabel=_frequentlyVisitedSitesLabel;
- (void).cxx_destruct;	// IMP=0x000000010011b1d4
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010011b128
- (void)layoutSubviews;	// IMP=0x000000010011afb8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010011ad24

@end

