//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HistoryTableViewController, _SFNavigationIntent;

@protocol HistoryTableViewControllerDelegate <NSObject>
- (void)historyTableViewControllerDidDismissPopover:(HistoryTableViewController *)arg1;
- (void)historyTableViewControllerDidPresentPopover:(HistoryTableViewController *)arg1;
- (void)historyTableViewControllerDidEndEditing:(HistoryTableViewController *)arg1;
- (void)historyTableViewControllerDidBeginEditing:(HistoryTableViewController *)arg1;
- (void)historyTableViewController:(HistoryTableViewController *)arg1 didProduceNavigationIntent:(_SFNavigationIntent *)arg2;
@end

