//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class UIImageView, UILabel;

@interface NewsCompletionHeaderView : UITableViewHeaderFooterView
{
    UIImageView *_newsImage;	// 8 = 0x8
    UILabel *_newsLabel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010009f3d8
- (void)setHeaderText:(id)arg1;	// IMP=0x000000010009f3c0
- (void)layoutSubviews;	// IMP=0x000000010009f258
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x000000010009f000

@end

