//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLSession.h"

#import "ReadingListMetadataProvider.h"

@class NSString;

@interface NSURLSession (ReadingListMetadataFetcherAdditions) <ReadingListMetadataProvider>
- (void)fetchThumbnailForBookmark:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100078bf4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

