//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, TabDocument, _WKRemoteObjectInterface;

@interface PageLoadTest : NSObject
{
    TabDocument *_tabDocument;	// 8 = 0x8
    NSArray *_pagesNeedingMemoryWarningSent;	// 16 = 0x10
    _WKRemoteObjectInterface *_eventsListenerInterface;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000b4bb0
- (void)didFinishPageLoadWithLoadData:(id)arg1;	// IMP=0x00000001000b4b3c
- (void)resetAfterWebProcessCrash;	// IMP=0x00000001000b4b08
- (void)_enablePageLoadMeasurementCollection;	// IMP=0x00000001000b4a10
- (void)_setUpPageLoadTestEventsListener;	// IMP=0x00000001000b4950
- (void)_setUpWebProcessForPageLoadMeasurementCollection;	// IMP=0x00000001000b491c
- (void)_invalidateRemoteObjects;	// IMP=0x00000001000b4884
- (void)dealloc;	// IMP=0x00000001000b4838
- (id)initWithTabDocument:(id)arg1 pagesNeedingMemoryWarningSent:(id)arg2;	// IMP=0x00000001000b4758
- (id)initWithTabDocument:(id)arg1;	// IMP=0x00000001000b4748

@end

