//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@interface PreviewTableViewController : UITableViewController
{
    id <PreviewTableViewControllerDelegate> _previewDelegate;	// 8 = 0x8
    id <LinkPreviewProvider> _linkPreviewProvider;	// 16 = 0x10
}

@property(nonatomic) __weak id <LinkPreviewProvider> linkPreviewProvider; // @synthesize linkPreviewProvider=_linkPreviewProvider;
@property(nonatomic) __weak id <PreviewTableViewControllerDelegate> previewDelegate; // @synthesize previewDelegate=_previewDelegate;
- (void).cxx_destruct;	// IMP=0x000000010009076c
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;	// IMP=0x000000010009069c
- (void)commitPreviewViewController:(id)arg1;	// IMP=0x0000000100090644
- (id)previewViewControllerForRowAtIndexPath:(id)arg1;	// IMP=0x000000010009057c
- (void)viewDidLoad;	// IMP=0x00000001000904f8

@end

