//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QuickWebsiteSearchQuery : NSObject
{
    NSString *_websiteNamePrefix;	// 8 = 0x8
    NSString *_searchTerms;	// 16 = 0x10
}

@property(readonly, nonatomic) NSString *searchTerms; // @synthesize searchTerms=_searchTerms;
@property(readonly, nonatomic) NSString *websiteNamePrefix; // @synthesize websiteNamePrefix=_websiteNamePrefix;
- (void).cxx_destruct;	// IMP=0x00000001000371c0
- (id)initWithUserEnteredString:(id)arg1;	// IMP=0x000000010003702c

@end

