//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CompletionItem.h"

@class NSString, QuickWebsiteSearchQuery, SFSearchResult, WBSQuerySuggestion, WBSQuickWebsiteSearchProvider;

@interface QuickWebsiteSearchCompletionItem : NSObject <CompletionItem>
{
    SFSearchResult *_sfSearchResultValue;	// 8 = 0x8
    WBSQuickWebsiteSearchProvider *_searchProvider;	// 16 = 0x10
    QuickWebsiteSearchQuery *_searchQuery;	// 24 = 0x18
}

@property(readonly, nonatomic) QuickWebsiteSearchQuery *searchQuery; // @synthesize searchQuery=_searchQuery;
@property(readonly, nonatomic) WBSQuickWebsiteSearchProvider *searchProvider; // @synthesize searchProvider=_searchProvider;
- (void).cxx_destruct;	// IMP=0x0000000100140b7c
@property(readonly, nonatomic) unsigned long long engagementDestination;
@property(readonly, nonatomic) SFSearchResult *sfSearchResultValue; // @synthesize sfSearchResultValue=_sfSearchResultValue;
- (id)reflectedStringForUserTypedString:(id)arg1;	// IMP=0x00000001001409ec
@property(readonly, nonatomic) NSString *parsecDomainIdentifier;
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;	// IMP=0x0000000100140960
- (void)acceptCompletionWithActionHandler:(id)arg1;	// IMP=0x0000000100140858
- (void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2;	// IMP=0x00000001001406e8
- (id)completionTableViewCellForCompletionList:(id)arg1;	// IMP=0x0000000100140670
- (id)completionTableViewCellReuseIdentifier;	// IMP=0x0000000100140644
- (id)initWithProvider:(id)arg1 query:(id)arg2;	// IMP=0x0000000100140574

// Remaining properties
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) id <CompletionItemActionHandler> handlerForActionItem;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *lastSearchQuery;
@property(nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult;
@property(readonly, nonatomic) _Bool restoresSearchState;
@property(retain, nonatomic) WBSQuerySuggestion *siriSuggestion;
@property(readonly) Class superclass;
@property(readonly, nonatomic) _Bool usesDefaultHeaderView;

@end

