//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CompletionItem.h"

@class NSString, SFSearchResult, WBSCompletionQuery, WBSQuerySuggestion, WebBookmark;

@interface ReadingListCompletionItem : NSObject <CompletionItem>
{
    WebBookmark *_bookmark;	// 8 = 0x8
    WBSCompletionQuery *_userQuery;	// 16 = 0x10
    SFSearchResult *_sfSearchResultValue;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001001410a4
@property(readonly, nonatomic) unsigned long long engagementDestination;
@property(readonly, nonatomic) SFSearchResult *sfSearchResultValue; // @synthesize sfSearchResultValue=_sfSearchResultValue;
- (id)reflectedStringForUserTypedString:(id)arg1;	// IMP=0x0000000100140f34
@property(readonly, nonatomic) NSString *parsecDomainIdentifier;
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;	// IMP=0x0000000100140ec0
- (id)completionTableViewCellForCompletionList:(id)arg1;	// IMP=0x0000000100140e48
- (id)completionTableViewCellReuseIdentifier;	// IMP=0x0000000100140e1c
- (void)acceptCompletionWithActionHandler:(id)arg1;	// IMP=0x0000000100140d74
- (void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2;	// IMP=0x0000000100140cac
- (id)initWithReadingListBookmark:(id)arg1 userQuery:(id)arg2;	// IMP=0x0000000100140bd0

// Remaining properties
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) id <CompletionItemActionHandler> handlerForActionItem;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *lastSearchQuery;
@property(nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult;
@property(readonly, nonatomic) _Bool restoresSearchState;
@property(retain, nonatomic) WBSQuerySuggestion *siriSuggestion;
@property(readonly) Class superclass;
@property(readonly, nonatomic) _Bool usesDefaultHeaderView;

@end

