//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SFSearchResult.h"

#import "CompletionItem.h"

@class NSString, WBSQuerySuggestion;

@interface SFSearchResult (CompletionItem) <CompletionItem>
- (id)_cardSectionFeedbackFromMKPlaceViewFeedbackType:(int)arg1;	// IMP=0x00000001000a0a60
- (void)placeViewController:(id)arg1 shouldLogFeedbackOfType:(int)arg2;	// IMP=0x00000001000a0a10
- (void)didEngageActionItem:(id)arg1 actionPerformed:(_Bool)arg2;	// IMP=0x00000001000a099c
- (void)didEngageCardSection:(id)arg1;	// IMP=0x00000001000a0990
- (void)cardViewDidAppear:(id)arg1;	// IMP=0x00000001000a0984
- (void)_postFeedback:(id)arg1;	// IMP=0x00000001000a08f4
@property(retain, nonatomic) id <CompletionItemActionHandler> handlerForActionItem;
- (unsigned long long)_searchUIStyleWithNarrowLayout:(_Bool)arg1;	// IMP=0x00000001000a08d0
@property(readonly, nonatomic) NSString *parsecDomainIdentifier;
- (id)reflectedStringForUserTypedString:(id)arg1;	// IMP=0x00000001000a08bc
- (id)completionTableViewCellReuseIdentifier;	// IMP=0x00000001000a0890
@property(readonly, nonatomic) _Bool restoresSearchState;
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;	// IMP=0x00000001000a0884
- (id)userVisibleURLString;	// IMP=0x00000001000a07e8
- (_Bool)_usesMapsPlacecard;	// IMP=0x00000001000a0690
- (void)_punchoutWithHandler:(id)arg1;	// IMP=0x00000001000a02d8
- (void)acceptCompletionWithActionHandler:(id)arg1;	// IMP=0x000000010009f86c
- (_Bool)_willShowNewsHeader;	// IMP=0x000000010009f6b0
- (void)configureCompletionTableHeaderView:(id)arg1 forCompletionListGroup:(id)arg2;	// IMP=0x000000010009f600
@property(readonly, nonatomic) _Bool usesDefaultHeaderView;
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
- (id)completionTableHeaderView;	// IMP=0x000000010009f508
- (void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2;	// IMP=0x000000010009f504
- (id)completionTableViewCellForCompletionList:(id)arg1;	// IMP=0x000000010009f418

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) unsigned long long engagementDestination;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *lastSearchQuery;
@property(nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult;
@property(readonly, nonatomic) SFSearchResult *sfSearchResultValue;
@property(retain, nonatomic) WBSQuerySuggestion *siriSuggestion;
@property(readonly) Class superclass;
@end

