//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SharedDataMigration : NSObject
{
}

+ (_Bool)migrateThumbnails;	// IMP=0x00000001000b42d0
+ (_Bool)migrateRecentSearches;	// IMP=0x00000001000b4250
+ (void)migratePersistentStorageDefaults;	// IMP=0x00000001000b4108
+ (_Bool)_migrateCacheFileFromSubpath:(id)arg1 toSubpath:(id)arg2 ensureIsDirectory:(_Bool)arg3;	// IMP=0x00000001000b3ca4
+ (id)_userCachesDirectoryPath;	// IMP=0x00000001000b3c28

@end

