//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSLayoutConstraint, UILabel;

@interface TabExplanationView : UIView
{
    UIView *_labelsContainer;	// 8 = 0x8
    UILabel *_title;	// 16 = 0x10
    UILabel *_message;	// 24 = 0x18
    NSLayoutConstraint *_spaceBetweenTitleAndMessageConstraint;	// 32 = 0x20
    NSArray *_defaultHorizontalPaddingConstraints;	// 40 = 0x28
    NSArray *_accessibilityHorizontalPaddingConstraints;	// 48 = 0x30
    unsigned long long _variant;	// 56 = 0x38
}

@property(readonly, nonatomic) unsigned long long variant; // @synthesize variant=_variant;
- (void).cxx_destruct;	// IMP=0x000000010008e360
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010008e24c
- (void)updateConstraints;	// IMP=0x000000010008e174
@property(readonly, nonatomic) struct CGRect labelsContainerFrame;
- (void)setQuery:(id)arg1;	// IMP=0x000000010008e100
- (void)setVariant:(unsigned long long)arg1 query:(id)arg2;	// IMP=0x000000010008dee4
- (id)initWithVariant:(unsigned long long)arg1 query:(id)arg2;	// IMP=0x000000010008d3e8
- (id)_basicLabel;	// IMP=0x000000010008d228

@end

