//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSUUID, TabMergingController;

@protocol TabMergingControllerDelegate <NSObject>

@optional
- (void)tabMergingControllerDidReconcileItems:(TabMergingController *)arg1;
- (void)tabMergingController:(TabMergingController *)arg1 didChangeOwnershipOfItem:(id <MergeableItem>)arg2 fromOwnerUUID:(NSUUID *)arg3 toOwnerUUID:(NSUUID *)arg4;
- (void)tabMergingController:(TabMergingController *)arg1 didChangeActiveItem:(id <MergeableItem>)arg2;
@end

