//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TabThumbnailView.h"

@class TabSnapshotImageView, UIView;

@interface TabOverviewItemView : TabThumbnailView
{
    _Bool _hasBorrowedContentView;	// 8 = 0x8
    _Bool _isAnimatingCornerRadius;	// 9 = 0x9
    double _cornerRadius;	// 16 = 0x10
    double _topBackdropHeight;	// 24 = 0x18
    UIView *_safeAreaInsetsReferenceView;	// 32 = 0x20
    UIView *_blankSnapshotView;	// 40 = 0x28
    UIView *_snapshotClipperView;	// 48 = 0x30
    TabSnapshotImageView *_snapshotView;	// 56 = 0x38
    UIView *_dimmingView;	// 64 = 0x40
    struct CGSize _windowSize;	// 72 = 0x48
}

@property(retain, nonatomic) UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
@property(retain, nonatomic) TabSnapshotImageView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(retain, nonatomic) UIView *snapshotClipperView; // @synthesize snapshotClipperView=_snapshotClipperView;
@property(readonly, nonatomic) UIView *blankSnapshotView; // @synthesize blankSnapshotView=_blankSnapshotView;
@property(nonatomic) __weak UIView *safeAreaInsetsReferenceView; // @synthesize safeAreaInsetsReferenceView=_safeAreaInsetsReferenceView;
@property(nonatomic) struct CGSize windowSize; // @synthesize windowSize=_windowSize;
@property(nonatomic) double topBackdropHeight; // @synthesize topBackdropHeight=_topBackdropHeight;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) _Bool isAnimatingCornerRadius; // @synthesize isAnimatingCornerRadius=_isAnimatingCornerRadius;
- (void).cxx_destruct;	// IMP=0x0000000100136fc4
- (struct UIEdgeInsets)_safeAreaInsetsForFrame:(struct CGRect)arg1 inSuperview:(id)arg2;	// IMP=0x0000000100136dcc
- (_Bool)headerHasFinishedAnimating;	// IMP=0x0000000100136d78
- (_Bool)shouldUseOpaqueHeaderBackground;	// IMP=0x0000000100136d30
- (struct CGRect)headerViewFrame;	// IMP=0x0000000100136c64
- (struct CGSize)headerViewInset;	// IMP=0x0000000100136c34
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100136bac
- (double)_scaledHeaderHeight;	// IMP=0x0000000100136b0c
- (void)_updateCornerRadiusIfNeeded;	// IMP=0x0000000100136984
- (void)layoutSubviews;	// IMP=0x00000001001366e0
- (void)animateToCornerRadius:(double)arg1 withDuration:(double)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001001364ec
- (void)removeBorrowedContentView:(id)arg1;	// IMP=0x0000000100136470
- (void)insertBorrowedContentView:(id)arg1;	// IMP=0x0000000100136420
- (void)updateSnapshotWithImage:(id)arg1;	// IMP=0x00000001001362cc
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x00000001001361f8
- (id)initWithImage:(id)arg1;	// IMP=0x0000000100135e34

@end

