//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TiltedTabBlankSnapshotView, TiltedTabItem, TiltedTabThumbnailView, TiltedTabView, UIButton, UIImage, UIView;

@interface TiltedTabItemLayoutInfo : NSObject
{
    _Bool _reordering;	// 8 = 0x8
    _Bool _closing;	// 9 = 0x9
    _Bool _finishedClosing;	// 10 = 0xa
    double _borrowedContentScale;	// 16 = 0x10
    UIView *_borrowedContentView;	// 24 = 0x18
    double _contentOpacity;	// 32 = 0x20
    TiltedTabThumbnailView *_contentView;	// 40 = 0x28
    double _topBackdropHeight;	// 48 = 0x30
    double _bottomInset;	// 56 = 0x38
    double _initialCornerRadius;	// 64 = 0x40
    double _contentOffsetDeltaY;	// 72 = 0x48
    double _zPosition;	// 80 = 0x50
    TiltedTabView *_tiltedTabView;	// 88 = 0x58
    TiltedTabItem *_item;	// 96 = 0x60
    long long _transition;	// 104 = 0x68
    unsigned long long _indexForLayout;	// 112 = 0x70
    unsigned long long _countForLayout;	// 120 = 0x78
    double _verticalScrollAdjustment;	// 128 = 0x80
    struct CGRect _closeButtonHitRect;	// 136 = 0x88
    struct CGRect _contentFrame;	// 168 = 0xa8
    struct CATransform3D _contentTransform;	// 200 = 0xc8
}

@property(nonatomic) double verticalScrollAdjustment; // @synthesize verticalScrollAdjustment=_verticalScrollAdjustment;
@property(nonatomic) unsigned long long countForLayout; // @synthesize countForLayout=_countForLayout;
@property(nonatomic) unsigned long long indexForLayout; // @synthesize indexForLayout=_indexForLayout;
@property(nonatomic) long long transition; // @synthesize transition=_transition;
@property(nonatomic, getter=isFinishedClosing) _Bool finishedClosing; // @synthesize finishedClosing=_finishedClosing;
@property(nonatomic, getter=isClosing) _Bool closing; // @synthesize closing=_closing;
@property(nonatomic, getter=isReordering) _Bool reordering; // @synthesize reordering=_reordering;
@property(readonly, nonatomic) __weak TiltedTabItem *item; // @synthesize item=_item;
@property(readonly, nonatomic) __weak TiltedTabView *tiltedTabView; // @synthesize tiltedTabView=_tiltedTabView;
@property(nonatomic) double zPosition; // @synthesize zPosition=_zPosition;
@property(nonatomic) double contentOffsetDeltaY; // @synthesize contentOffsetDeltaY=_contentOffsetDeltaY;
@property(nonatomic) double initialCornerRadius; // @synthesize initialCornerRadius=_initialCornerRadius;
@property(nonatomic) double bottomInset; // @synthesize bottomInset=_bottomInset;
@property(nonatomic) double topBackdropHeight; // @synthesize topBackdropHeight=_topBackdropHeight;
@property(retain, nonatomic) TiltedTabThumbnailView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) struct CATransform3D contentTransform; // @synthesize contentTransform=_contentTransform;
@property(nonatomic) double contentOpacity; // @synthesize contentOpacity=_contentOpacity;
@property(nonatomic) struct CGRect contentFrame; // @synthesize contentFrame=_contentFrame;
@property(nonatomic) struct CGRect closeButtonHitRect; // @synthesize closeButtonHitRect=_closeButtonHitRect;
@property(retain, nonatomic) UIView *borrowedContentView; // @synthesize borrowedContentView=_borrowedContentView;
@property(nonatomic) double borrowedContentScale; // @synthesize borrowedContentScale=_borrowedContentScale;
- (void).cxx_destruct;	// IMP=0x00000001000ab010
@property(nonatomic) _Bool hidesTabTitle;
- (void)updateBorrowedContentFrame;	// IMP=0x00000001000aa9f8
- (struct CGRect)_borrowedContentFrame;	// IMP=0x00000001000aa954
@property(readonly, nonatomic) struct CGRect contentClipperBounds;
- (struct CGRect)clippedContentFrame;	// IMP=0x00000001000aa7c8
- (void)pulseContentShadowView;	// IMP=0x00000001000aa530
- (void)resetToInitialCornerRadius;	// IMP=0x00000001000aa364
- (void)updateSnapshotViewAnimated:(_Bool)arg1 adjustContentsRect:(_Bool)arg2;	// IMP=0x00000001000aa140
- (void)updateSnapshotViewAnimated:(_Bool)arg1;	// IMP=0x00000001000aa130
- (void)tearDownThumbnailView;	// IMP=0x00000001000aa000
- (void)setUpThumbnailView;	// IMP=0x00000001000a9c40
@property(readonly, nonatomic) struct CGRect snapshotViewContentsRect;
- (struct CGSize)_sizeForSnapshot:(id)arg1;	// IMP=0x00000001000a9a0c
@property(readonly, nonatomic) struct CGRect blankSnapshotBlankViewFrame;
@property(readonly, nonatomic) struct CGRect blankSnapshotHeaderViewFrame;
@property(readonly, nonatomic) struct CGRect blankSnapshotViewFrame;
@property(readonly, nonatomic) struct CGRect snapshotViewFrame;
@property(readonly, nonatomic) TiltedTabBlankSnapshotView *blankSnapshotView;
@property(readonly, nonatomic) UIView *snapshotView;
@property(readonly, nonatomic) UIView *contentClipperView;
@property(readonly, nonatomic) UIView *contentShadowView;
@property(readonly, nonatomic) UIButton *closeButton;
@property(nonatomic) _Bool usesDarkTheme;
@property(nonatomic, getter=isRecording) _Bool recording;
@property(retain, nonatomic) UIImage *icon;
@property(copy, nonatomic) NSString *title;
- (void)dealloc;	// IMP=0x00000001000a9744
- (id)initWithTiltedTabView:(id)arg1 item:(id)arg2;	// IMP=0x00000001000a961c

@end

