//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (TableViewScrollPositionSaving)
@property(readonly, nonatomic) _Bool safari_hasSavedTableViewScrollPosition;
- (_Bool)safari_restoreTableViewScrollPosition;	// IMP=0x00000001000b1a78
- (void)safari_saveTableViewScrollPosition;	// IMP=0x00000001000b16e8
- (id)_safari_tableViewScrollPositionKey;	// IMP=0x00000001000b1688
- (id)safari_tableViewScrollPositionSaveIdentifier;	// IMP=0x00000001000b1680
- (id)safari_tableViewForScrollPositionSaving;	// IMP=0x00000001000b1618
@end

