//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ContentInteractionTestRunner.h"

@interface ZoomAnimationTestProcessor : ContentInteractionTestRunner
{
    int _iterationsRemaining;	// 48 = 0x30
    int _targetIndex;	// 52 = 0x34
    long long _testState;	// 56 = 0x38
    double _initialZoom;	// 64 = 0x40
}

@property(nonatomic) double initialZoom; // @synthesize initialZoom=_initialZoom;
@property(nonatomic) int targetIndex; // @synthesize targetIndex=_targetIndex;
@property(nonatomic) long long testState; // @synthesize testState=_testState;
@property(nonatomic) int iterationsRemaining; // @synthesize iterationsRemaining=_iterationsRemaining;
- (_Bool)performActionForPage:(id)arg1;	// IMP=0x0000000100141c98
- (void)advanceTest;	// IMP=0x0000000100141b28
- (void)resetZoom;	// IMP=0x0000000100141aa8
- (void)startZoom;	// IMP=0x00000001001419c0
- (void)scrollViewDidEndZooming:(id)arg1;	// IMP=0x0000000100141960
- (void)scrollViewWillBeginZooming:(id)arg1;	// IMP=0x000000010014194c
- (_Bool)startPageAction:(id)arg1;	// IMP=0x0000000100141830
- (void)dealloc;	// IMP=0x00000001001417b8
- (id)initWithTestName:(id)arg1 browserController:(id)arg2;	// IMP=0x0000000100141670

@end

