//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDAddDataManualEntryItem.h"

@class NSDate, NSDateFormatter, UIDatePicker, WDManualDataEntryTableViewCell;

@interface _WDDateBasedAddDataManualEntryItem : WDAddDataManualEntryItem
{
    UIDatePicker *_datePicker;	// 40 = 0x28
    WDManualDataEntryTableViewCell *_tableViewCell;	// 48 = 0x30
    NSDate *_maximumDate;	// 56 = 0x38
    NSDate *_chosenDate;	// 64 = 0x40
    _Bool _highlightWhenEditing;	// 72 = 0x48
    NSDateFormatter *_dateFormatter;	// 80 = 0x50
    long long _datePickerMode;	// 88 = 0x58
}

@property(nonatomic) long long datePickerMode; // @synthesize datePickerMode=_datePickerMode;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (void).cxx_destruct;	// IMP=0x00000001000f7c9c
- (void)setTitle:(id)arg1;	// IMP=0x00000001000f7bd8
- (void)beginEditing;	// IMP=0x00000001000f7bc0
- (void)setValue:(id)arg1;	// IMP=0x00000001000f7b30
- (void)_generateValue:(CDUnknownBlockType)arg1;	// IMP=0x00000001000f7a54
- (id)generateValue;	// IMP=0x00000001000f7a44
- (void)_saveDisambiguatedDate:(id)arg1;	// IMP=0x00000001000f7950
- (void)_datePickerDidChange:(id)arg1;	// IMP=0x00000001000f7818
- (id)tableViewCells;	// IMP=0x00000001000f7618
- (id)initWithMaximumDate:(id)arg1 highlightWhenEditing:(_Bool)arg2;	// IMP=0x00000001000f7588

@end

