//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HKGraphSeriesDataSourceDelegate.h"

@class HKGraphSeriesDataSource, NSDate, NSString, WDInteractiveChartHeartRateViewController;

@interface _WDInteractiveChartHeartRateCachedDataController : NSObject <HKGraphSeriesDataSourceDelegate>
{
    WDInteractiveChartHeartRateViewController *_heartRateViewController;	// 8 = 0x8
    HKGraphSeriesDataSource *_dataSource;	// 16 = 0x10
    long long _timeScope;	// 24 = 0x18
    NSDate *_startDate;	// 32 = 0x20
    NSDate *_endDate;	// 40 = 0x28
    CDUnknownBlockType _completion;	// 48 = 0x30
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) long long timeScope; // @synthesize timeScope=_timeScope;
@property(retain, nonatomic) HKGraphSeriesDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak WDInteractiveChartHeartRateViewController *heartRateViewController; // @synthesize heartRateViewController=_heartRateViewController;
- (void).cxx_destruct;	// IMP=0x000000010012e2b8
- (void)dataSourceDidUpdateCache:(id)arg1;	// IMP=0x000000010012dfe8
- (void)requestAndWaitForData;	// IMP=0x000000010012de88
- (id)initWithHeartRateViewController:(id)arg1 dataSource:(id)arg2 timeScope:(long long)arg3 startDate:(id)arg4 endDate:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x000000010012dd20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

