//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKConditionRecord.h"

@interface HKConditionRecord (DisplayItemAdditions)
- (long long)recordCategoryType;	// IMP=0x000000010003bb8c
- (void)fetchDetailItemsWithHealthRecordsStore:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003acd0
- (id)codings;	// IMP=0x000000010003acc4
- (id)title;	// IMP=0x000000010003ac60
@end

