//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKReportContent.h"

@class NSString;

@interface HKReportBlockContent : HKReportContent
{
    NSString *_name;	// 32 = 0x20
    CDUnknownBlockType _renderHandler;	// 40 = 0x28
}

+ (id)blockContentWithName:(id)arg1;	// IMP=0x00000001000d70dc
@property(copy, nonatomic) CDUnknownBlockType renderHandler; // @synthesize renderHandler=_renderHandler;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;	// IMP=0x00000001000d72ac
- (id)description;	// IMP=0x00000001000d71d0
- (void)renderAndDraw:(_Bool)arg1;	// IMP=0x00000001000d7150

@end

