//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HKGraphViewDelegate.h"

@class HKGraphSeries, NSString;

@interface HKScalarGraphSeriesDelegate : NSObject <HKGraphViewDelegate>
{
    HKGraphSeries *_graphSeries;	// 8 = 0x8
}

@property(readonly, nonatomic) HKGraphSeries *graphSeries; // @synthesize graphSeries=_graphSeries;
- (void).cxx_destruct;	// IMP=0x00000001000976d8
- (void)graphViewDidTapYAxis:(id)arg1;	// IMP=0x00000001000976c4
- (id)seriesSelectionLineColorForGraphView:(id)arg1;	// IMP=0x00000001000976c0
- (id)graphView:(id)arg1 graphSeriesForZoom:(long long)arg2 stackOffset:(long long)arg3;	// IMP=0x0000000100097650
- (long long)stackCountForGraphView:(id)arg1;	// IMP=0x0000000100097648
- (void)graphView:(id)arg1 didUpdateLegendViewsWithTopLegendFrame:(struct CGRect)arg2;	// IMP=0x0000000100097644
- (void)graphView:(id)arg1 didUpdateSeries:(id)arg2 newDataArrived:(_Bool)arg3;	// IMP=0x0000000100097640
- (void)graphView:(id)arg1 didUpdateYAxisWidth:(double)arg2 toWidth:(double)arg3;	// IMP=0x000000010009763c
- (void)graphViewSizeChanged:(id)arg1;	// IMP=0x0000000100097638
- (void)graphView:(id)arg1 didFinishUserScrollingToValueRange:(id)arg2;	// IMP=0x0000000100097634
- (void)graphView:(id)arg1 didUpdateVisibleValueRange:(id)arg2 changeContext:(long long)arg3;	// IMP=0x0000000100097630
- (void)graphView:(id)arg1 didUpdateFromDateZoom:(long long)arg2 toDateZoom:(long long)arg3 newVisibleRange:(id)arg4;	// IMP=0x000000010009762c
- (void)graphViewDidEndSelection:(id)arg1;	// IMP=0x0000000100097628
- (void)graphView:(id)arg1 didUpdateSelectedPoint:(id)arg2;	// IMP=0x0000000100097624
- (void)graphViewDidBeginSelection:(id)arg1;	// IMP=0x0000000100097620
- (id)initWithGraphSeries:(id)arg1;	// IMP=0x00000001000975a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

