//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "HKProfileIconObserver.h"
#import "UIApplicationDelegate.h"
#import "UIApplicationTestingDelegate.h"
#import "WDFavoriteDisplayTypesControllerObserver.h"
#import "WDIntroFlowManagerDelegate.h"

@class HKNavigationController, NSString, UIWindow, WDHealthDataViewController, WDIntroFlowManager, WDProfile, WDTabBarController, WDTodayViewController;

@interface WDAppDelegate : UIResponder <UIApplicationTestingDelegate, HKProfileIconObserver, WDFavoriteDisplayTypesControllerObserver, WDIntroFlowManagerDelegate, UIApplicationDelegate>
{
    WDProfile *_profile;	// 8 = 0x8
    WDIntroFlowManager *_introFlowManager;	// 16 = 0x10
    HKNavigationController *_profileNavigationController;	// 24 = 0x18
    HKNavigationController *_medicalIDNavigationController;	// 32 = 0x20
    HKNavigationController *_sourcesNavigationController;	// 40 = 0x28
    WDTabBarController *_tabBarController;	// 48 = 0x30
    WDHealthDataViewController *_healthDataViewController;	// 56 = 0x38
    WDTodayViewController *_todayViewController;	// 64 = 0x40
    UIWindow *_window;	// 72 = 0x48
}

+ (id)currentDelegate;	// IMP=0x000000010016e468
@property(readonly, nonatomic) WDProfile *profile; // @synthesize profile=_profile;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;	// IMP=0x0000000100170404
- (void)_postAWDMetricForUsingDeepLink;	// IMP=0x00000001001703c0
- (void)_postAWDMetricForFinishedAddingAccount;	// IMP=0x00000001001703b0
- (void)_postAWDOnboardingMetricForType:(int)arg1;	// IMP=0x000000010017034c
- (id)_storeDemoModeFavoriteDisplayTypes;	// IMP=0x000000010016ffc4
- (void)favoriteDisplayTypesControllerReady:(id)arg1;	// IMP=0x000000010016ff60
- (void)resetStoreDemoModeFavorites;	// IMP=0x000000010016fed4
- (void)restoreStoreDemoModeFavoritesIfNeeded;	// IMP=0x000000010016fdec
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010016fd24
- (void)_restoreApplicationStateWithUserActivity:(id)arg1;	// IMP=0x000000010016fc88
- (_Bool)_restoreApplicationStateWithOnboardingUserActivity:(id)arg1;	// IMP=0x000000010016eeec
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;	// IMP=0x000000010016eee8
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010016ee28
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;	// IMP=0x000000010016ee20
- (void)didTapProfileIcon;	// IMP=0x000000010016ee14
- (void)presentProfileViewController;	// IMP=0x000000010016ede4
- (void)_configureUserActivityPolicies;	// IMP=0x000000010016ed50
- (void)_configureNotificationPolicies;	// IMP=0x000000010016ecc0
- (void)_buildUIWithProfile:(id)arg1;	// IMP=0x000000010016e62c
- (void)_restoreToBaseStateAndSelectTabAtIndex:(long long)arg1;	// IMP=0x000000010016e4c4
- (id)introFlowManager;	// IMP=0x000000010016e458
- (id)tabBarController;	// IMP=0x000000010016e448
- (_Bool)_openURL:(id)arg1 options:(id)arg2;	// IMP=0x000000010016de90
- (void)openHealthAppURL:(id)arg1;	// IMP=0x000000010016de78
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x000000010016dde4
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x000000010016dddc
- (_Bool)application:(id)arg1 shouldRestoreApplicationState:(id)arg2;	// IMP=0x000000010016ddb0
- (_Bool)application:(id)arg1 shouldSaveApplicationState:(id)arg2;	// IMP=0x000000010016dda8
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;	// IMP=0x000000010016dab8
- (_Bool)landscapeChartAnimationTest;	// IMP=0x0000000100033574
- (_Bool)todayViewScrollTest;	// IMP=0x00000001000333f8
- (_Bool)categoryViewScrollTest:(long long)arg1;	// IMP=0x00000001000330bc
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;	// IMP=0x0000000100032e80

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

