//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@class SFSafariViewController, WDProfile;

@interface WDClinicalOnboardingOAuthNavigationViewController : UINavigationController
{
    WDProfile *_profile;	// 8 = 0x8
    SFSafariViewController *_safariViewController;	// 16 = 0x10
}

+ (id)clinicalOnboardingOauthViewControllerWithProfile:(id)arg1;	// IMP=0x0000000100128300
@property(retain, nonatomic) SFSafariViewController *safariViewController; // @synthesize safariViewController=_safariViewController;
@property(retain, nonatomic) WDProfile *profile; // @synthesize profile=_profile;
- (void).cxx_destruct;	// IMP=0x0000000100128c48
- (void)_postAWDOnboardingMetric;	// IMP=0x0000000100128bb4
- (void)presentSafariViewController;	// IMP=0x0000000100128b60
- (void)showClinicalAccountEducationViewControllerWithAccount:(id)arg1;	// IMP=0x00000001001289d8
- (void)createRootViewController;	// IMP=0x0000000100128744
- (void)completionNotificationHandler:(id)arg1;	// IMP=0x0000000100128538
- (void)beginListeningToNotification;	// IMP=0x00000001001284d4
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0000000100128478
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100128428
- (void)viewDidLoad;	// IMP=0x00000001001283d8
- (id)initWithProfile:(id)arg1;	// IMP=0x0000000100128364

@end

