//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIStackView, WDBrandLogoView, WDClinicalSourcesDataProvider;

@interface WDClinicalLocationCell : UITableViewCell
{
    id <HKClinicalBrandable> _brandable;	// 8 = 0x8
    WDClinicalSourcesDataProvider *_dataProvider;	// 16 = 0x10
    WDBrandLogoView *_logoView;	// 24 = 0x18
    UILabel *_titleLabel;	// 32 = 0x20
    UILabel *_subtitleLabel;	// 40 = 0x28
    UILabel *_detailLabel;	// 48 = 0x30
    UIStackView *_stackView;	// 56 = 0x38
}

+ (id)defaultReuseIdentifier;	// IMP=0x0000000100031d94
@property(readonly, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(readonly, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) WDBrandLogoView *logoView; // @synthesize logoView=_logoView;
@property(readonly, nonatomic) WDClinicalSourcesDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(readonly, nonatomic) id <HKClinicalBrandable> brandable; // @synthesize brandable=_brandable;
- (void).cxx_destruct;	// IMP=0x0000000100032ddc
- (void)willDisplay;	// IMP=0x0000000100032ba8
- (void)prepareForReuse;	// IMP=0x0000000100032b50
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100032a50
- (void)_updateForContentSizeCategory:(id)arg1;	// IMP=0x0000000100032a4c
- (void)_updateForCurrentSizeCategory;	// IMP=0x0000000100032988
- (void)_updateContentWithBrandable:(id)arg1 dataProvider:(id)arg2;	// IMP=0x000000010003282c
- (void)setBrandable:(id)arg1 dataProvider:(id)arg2;	// IMP=0x0000000100032780
- (void)_configureDistinctIntrinsicLayoutPrioritiesForLabels;	// IMP=0x0000000100032360
- (void)_setUpConstraints;	// IMP=0x00000001000322f0
- (void)_setupSubviews;	// IMP=0x0000000100031d98
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100031cdc

@end

