//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKTableViewController.h"

#import "WDTodayMonthViewControllerDelegate.h"
#import "WDUserActivityResponder.h"

@class HKDisplayType, NSDate, NSString, UIActivityIndicatorView, UIBarButtonItem, WDProfile, _UIContentUnavailableView;

@interface WDDataListViewController : HKTableViewController <WDTodayMonthViewControllerDelegate, WDUserActivityResponder>
{
    WDProfile *_profile;	// 8 = 0x8
    UIBarButtonItem *_deleteAllButtonItem;	// 16 = 0x10
    UIActivityIndicatorView *_spinner;	// 24 = 0x18
    long long _cellStyle;	// 32 = 0x20
    _UIContentUnavailableView *_noContentView;	// 40 = 0x28
    id <WDDataListViewControllerDataProvider> _dataProvider;	// 48 = 0x30
    HKDisplayType *_displayType;	// 56 = 0x38
    NSDate *_scrollToDate;	// 64 = 0x40
}

@property(retain, nonatomic) NSDate *scrollToDate; // @synthesize scrollToDate=_scrollToDate;
@property(readonly, nonatomic) HKDisplayType *displayType; // @synthesize displayType=_displayType;
@property(readonly, nonatomic) id <WDDataListViewControllerDataProvider> dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;	// IMP=0x00000001000ab9f4
- (id)applyTransitionActivity:(id)arg1;	// IMP=0x00000001000ab9ac
- (void)applyChangeActivity:(id)arg1;	// IMP=0x00000001000ab9a8
- (void)_updateActivityForViewDidAppear;	// IMP=0x00000001000ab86c
- (_Bool)_hasSpinnerRowRowAtIndexPath:(id)arg1;	// IMP=0x00000001000ab7c0
- (_Bool)_shouldShowSpinnerRowInSection:(long long)arg1;	// IMP=0x00000001000ab6a4
- (void)_updateRightBarButtonItems;	// IMP=0x00000001000ab638
- (id)_rightBarButtonItems;	// IMP=0x00000001000ab428
- (void)_deleteAllWithOptions:(unsigned long long)arg1;	// IMP=0x00000001000aae5c
- (void)_deleteAssociatedSamplesConfirmationPlural:(_Bool)arg1 deleteBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000aa9a4
- (void)_deleteAllButtonTapped:(id)arg1;	// IMP=0x00000001000aa588
- (void)_calendarDateSelectorButtonTapped:(id)arg1;	// IMP=0x00000001000aa394
- (void)resetDataAndScrollToDate:(id)arg1;	// IMP=0x00000001000aa2a8
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000aa1a0
- (void)didTapBackButtonForMonthViewController:(id)arg1;	// IMP=0x00000001000aa19c
- (void)monthViewController:(id)arg1 didSelectDate:(id)arg2;	// IMP=0x00000001000aa15c
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001000a9d98
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a9d18
- (id)_sampleAtIndexPath:(id)arg1;	// IMP=0x00000001000a9c94
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a9bb0
- (id)_defaultCellForTableView:(id)arg1 cellStyle:(long long)arg2 indexPath:(id)arg3 text:(id)arg4 secondaryText:(id)arg5 icon:(id)arg6;	// IMP=0x00000001000a9a14
- (id)_quantityCellForTableView:(id)arg1 dataObjectSource:(id)arg2;	// IMP=0x00000001000a9574
- (id)_sourceIconForObject:(id)arg1;	// IMP=0x00000001000a932c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a90b0
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000a903c
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x00000001000a9020
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x00000001000a9010
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x00000001000a8f58
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000a8f40
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x00000001000a8e14
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000a8b70
- (void)_dataProviderDidUpdate;	// IMP=0x00000001000a8ae4
- (void)viewDidLoad;	// IMP=0x00000001000a85c4
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000a8574
- (_Bool)_dataProviderEnabled;	// IMP=0x00000001000a84d0
- (long long)_closestRowToDate:(id)arg1;	// IMP=0x00000001000a832c
- (void)_reloadAllData;	// IMP=0x00000001000a831c
- (void)_reloadAllDataScrolledToDate:(id)arg1;	// IMP=0x00000001000a7fc0
- (id)_sampleTypesForDeleteAll;	// IMP=0x00000001000a7e94
- (void)_displayTypeStringsChanged:(id)arg1;	// IMP=0x00000001000a7e88
- (void)_localeDidChange:(id)arg1;	// IMP=0x00000001000a7e7c
- (void)dealloc;	// IMP=0x00000001000a7dec
@property(readonly, nonatomic) WDProfile *profile;
- (id)initWithDisplayType:(id)arg1 profile:(id)arg2 dataProvider:(id)arg3;	// IMP=0x00000001000a7acc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

