//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDStoredDataByCategoryViewController.h"

@class HKDevice, NSString;

@interface WDDeviceStoredDataViewController : WDStoredDataByCategoryViewController
{
    HKDevice *_device;	// 8 = 0x8
    NSString *_displayName;	// 16 = 0x10
}

@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) HKDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;	// IMP=0x000000010010ef44
- (void)deleteAllStoredData;	// IMP=0x000000010010ebd0
- (_Bool)shouldShowDeleteAllDataButton;	// IMP=0x000000010010eb80
- (id)storedDataDisplayName;	// IMP=0x000000010010eae8
- (id)storedDataPredicate;	// IMP=0x000000010010e964

@end

