//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

#import "UITextViewDelegate.h"

@class NSString, UITextView;

@interface WDFooterViewWithLink : UITableViewHeaderFooterView <UITextViewDelegate>
{
    UITextView *_footerTextView;	// 8 = 0x8
}

+ (id)defaultReuseIdentifier;	// IMP=0x000000010006e080
@property(retain, nonatomic) UITextView *footerTextView; // @synthesize footerTextView=_footerTextView;
- (void).cxx_destruct;	// IMP=0x000000010006eb64
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;	// IMP=0x000000010006ea7c
- (void)_setupConstraints;	// IMP=0x000000010006e724
- (void)_setUpFooterTextViewWithBodyText:(id)arg1 linkText:(id)arg2 link:(id)arg3;	// IMP=0x000000010006e16c
- (id)initWithReuseIdentifier:(id)arg1 bodyText:(id)arg2 linkText:(id)arg3 link:(id)arg4;	// IMP=0x000000010006e084

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

