//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKDisplayCategory, NSString;

@interface WDHealthDataCategoryVideoDataProvider : NSObject
{
    HKDisplayCategory *_category;	// 8 = 0x8
    NSString *_importanceText;	// 16 = 0x10
    NSString *_descriptionText;	// 24 = 0x18
    NSString *_videoPosterImageName;	// 32 = 0x20
}

+ (id)videoURLManagerIdentifierForOnboarding;	// IMP=0x00000001000690f0
+ (id)videoPosterImageNameForOnboarding;	// IMP=0x00000001000690d4
+ (id)videoPosterImageNameForCategory:(id)arg1;	// IMP=0x000000010006906c
+ (id)videoPosterImageNameWithName:(id)arg1;	// IMP=0x0000000100069058
+ (id)descriptionTextForCategory:(id)arg1;	// IMP=0x0000000100068f5c
- (void).cxx_destruct;	// IMP=0x0000000100069100
- (id)videoURLManagerIdentifier;	// IMP=0x0000000100068efc
- (id)videoPosterImageName;	// IMP=0x0000000100068eec
- (id)descriptionText;	// IMP=0x0000000100068edc
- (id)initWithCategory:(id)arg1;	// IMP=0x0000000100068dd8

@end

