//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton;

@interface WDImprovementDataCollectionOptInViewControllerLinkCell : UITableViewCell
{
    UIButton *_linkButton;	// 8 = 0x8
}

+ (id)defaultReuseIdentifier;	// IMP=0x000000010008ad5c
@property(retain, nonatomic) UIButton *linkButton; // @synthesize linkButton=_linkButton;
- (void).cxx_destruct;	// IMP=0x000000010008b294
- (void)setupLinkButton;	// IMP=0x000000010008ad60
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010008acf0

@end

