//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKSelectedRangeData, NSString, UIColor, WDInteractiveChartCurrentValueView;

@protocol WDInteractiveChartCurrentValueViewDataSource <NSObject>
- (UIColor *)textColorForCurrentValueView:(WDInteractiveChartCurrentValueView *)arg1;
- (HKSelectedRangeData *)selectedRangeDataForColumnAtIndex:(long long)arg1;
- (NSString *)secondaryStringForCurrentValueView:(WDInteractiveChartCurrentValueView *)arg1;
- (long long)numberOfColumnsForCurrentValueView:(WDInteractiveChartCurrentValueView *)arg1;
- (void)loadLastRecordedDateStringForMenstrualCycleStartWithCompletion:(void (^)(NSString *, NSError *))arg1;
- (_Bool)pendingData;
- (_Bool)shouldUseLastRecordedDate;
@end

