//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKViewTableViewCell.h"

#import "WDDisplayTypeDetailViewControllerChartCellType.h"

@class NSString;

@interface WDInteractiveChartTableViewCell : HKViewTableViewCell <WDDisplayTypeDetailViewControllerChartCellType>
{
    unsigned long long _displayMode;	// 8 = 0x8
    unsigned long long _marginMode;	// 16 = 0x10
}

+ (id)defaultReuseIdentifier;	// IMP=0x00000001001542f0
@property(nonatomic) unsigned long long marginMode; // @synthesize marginMode=_marginMode;
@property(nonatomic) unsigned long long displayMode; // @synthesize displayMode=_displayMode;
- (void)setTimeScope:(long long)arg1;	// IMP=0x0000000100154320
- (void)setPrimaryValueSource:(id)arg1 secondaryValueSource:(id)arg2 chartSource:(id)arg3;	// IMP=0x000000010015431c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

