//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UILabel, UIStackView;

@interface WDInteractiveChartCurrentValueView : UIView
{
    id <WDInteractiveChartCurrentValueViewDataSource> _dataSource;	// 8 = 0x8
    UIStackView *_columnStack;	// 16 = 0x10
    UIStackView *_containerStack;	// 24 = 0x18
    UILabel *_valueLabel;	// 32 = 0x20
    UILabel *_secondaryLabel;	// 40 = 0x28
    NSTimer *_deferredNoDataTimer;	// 48 = 0x30
}

@property(nonatomic) __weak NSTimer *deferredNoDataTimer; // @synthesize deferredNoDataTimer=_deferredNoDataTimer;
@property(retain, nonatomic) UILabel *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
@property(retain, nonatomic) UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(retain, nonatomic) UIStackView *containerStack; // @synthesize containerStack=_containerStack;
@property(retain, nonatomic) UIStackView *columnStack; // @synthesize columnStack=_columnStack;
@property(nonatomic) __weak id <WDInteractiveChartCurrentValueViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x00000001000a01b4
- (void)scheduleDeferredDataReload;	// IMP=0x000000010009fecc
- (void)showNoDataStatus;	// IMP=0x000000010009fc04
- (void)updateCurrentValueTextWithAttributedString:(id)arg1;	// IMP=0x000000010009fa34
- (void)_updateCurrentValueViewWithNumberOfColumns:(long long)arg1;	// IMP=0x000000010009f634
- (void)reloadData;	// IMP=0x000000010009f170
- (void)_setupSubviews;	// IMP=0x000000010009e914
- (id)_fontForType:(long long)arg1;	// IMP=0x000000010009e820
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010009e7c8
- (id)init;	// IMP=0x000000010009e738

@end

