//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITextFieldDelegate.h"

@class HKDisplayType, NSArray, NSLayoutConstraint, NSNumberFormatter, NSString, UIFont, UILabel, UITextField, UIView;

@interface WDManualDataEntryTableViewCell : UITableViewCell <UITextFieldDelegate>
{
    unsigned long long _dataEntryType;	// 8 = 0x8
    UITextField *_valueField;	// 16 = 0x10
    UIView *_inputView;	// 24 = 0x18
    NSString *_decimalSeparator;	// 32 = 0x20
    UILabel *_displayNameLabel;	// 40 = 0x28
    UILabel *_unitLabel;	// 48 = 0x30
    NSArray *_displayNameLabelConstraints;	// 56 = 0x38
    NSNumberFormatter *_integerNumberFormatter;	// 64 = 0x40
    NSString *_lastValidSanitizedText;	// 72 = 0x48
    NSArray *_regularLayoutConstraints;	// 80 = 0x50
    NSArray *_largeTextLayoutConstraints;	// 88 = 0x58
    NSLayoutConstraint *_largeTextValueFieldToUnitLabelSpacingConstraint;	// 96 = 0x60
    _Bool _shouldHighlightWhenEditing;	// 104 = 0x68
    HKDisplayType *_displayType;	// 112 = 0x70
    id <WDManualDataEntryTableViewCellDelegate> _delegate;	// 120 = 0x78
    UIFont *_bodyFont;	// 128 = 0x80
}

@property(retain, nonatomic) UIFont *bodyFont; // @synthesize bodyFont=_bodyFont;
@property(nonatomic) __weak id <WDManualDataEntryTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldHighlightWhenEditing; // @synthesize shouldHighlightWhenEditing=_shouldHighlightWhenEditing;
@property(retain, nonatomic) HKDisplayType *displayType; // @synthesize displayType=_displayType;
- (void).cxx_destruct;	// IMP=0x00000001000cc4a0
- (void)_updateDecimalSeparator;	// IMP=0x00000001000cc3a4
- (id)_sanitizedTextFieldText:(id)arg1;	// IMP=0x00000001000cc2ac
- (id)_removeDecimalSeparatorsFromText:(id)arg1;	// IMP=0x00000001000cc068
- (void)_localeDidChange:(id)arg1;	// IMP=0x00000001000cc020
- (void)textFieldDidEndEditing:(id)arg1;	// IMP=0x00000001000cbf88
- (void)textFieldDidBeginEditing:(id)arg1;	// IMP=0x00000001000cbef8
- (_Bool)textFieldShouldBeginEditing:(id)arg1;	// IMP=0x00000001000cbee0
- (void)_valueFieldDidChange:(id)arg1;	// IMP=0x00000001000cbde0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000cbce0
- (id)inputView;	// IMP=0x00000001000cbcc8
- (void)setInputView:(id)arg1;	// IMP=0x00000001000cbcb0
- (void)endEditing;	// IMP=0x00000001000cbc50
- (void)beginEditing;	// IMP=0x00000001000cbbf0
- (void)_setupIntegerNumberFormatterIfNeeded;	// IMP=0x00000001000cbb68
- (void)_setupUIWithDisplayName:(id)arg1 unitName:(id)arg2;	// IMP=0x00000001000cb6d8
- (void)_updateDisplayNameLabelConstraints;	// IMP=0x00000001000cb430
- (void)_updateFont;	// IMP=0x00000001000cb334
- (void)_updateForCurrentSizeCategory;	// IMP=0x00000001000cb170
- (void)_setupConstraints;	// IMP=0x00000001000ca9ec
@property(retain, nonatomic) NSString *value;
@property(retain, nonatomic) NSString *displayName;
- (void)dealloc;	// IMP=0x00000001000ca884
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000ca850
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000ca7b8
- (id)initWithDisplayName:(id)arg1 unitName:(id)arg2 dataEntryType:(unsigned long long)arg3;	// IMP=0x00000001000ca678

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

