//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class CALayer;

@interface WDPlayButton : UIButton
{
    CALayer *_playSymbolLayer;	// 8 = 0x8
}

@property(retain, nonatomic) CALayer *playSymbolLayer; // @synthesize playSymbolLayer=_playSymbolLayer;
- (void).cxx_destruct;	// IMP=0x00000001000e8414
- (void)setupPlaySymbol;	// IMP=0x00000001000e8100
- (void)setBounds:(struct CGRect)arg1;	// IMP=0x00000001000e7ff8
- (void)didMoveToSuperview;	// IMP=0x00000001000e7fa8

@end

