//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDSampleListDataProvider.h"

@interface WDQuantityListDataProvider : WDSampleListDataProvider
{
}

- (id)titleForSection:(unsigned long long)arg1;	// IMP=0x00000001000ecacc
- (id)textForObject:(id)arg1;	// IMP=0x00000001000ec928
- (id)sampleTypes;	// IMP=0x00000001000ec864
- (id)initWithDisplayType:(id)arg1 profile:(id)arg2;	// IMP=0x00000001000ec778

@end

