//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKObject.h"

@interface WDSleepDetailViewAppearance : HKObject
{
}

+ (id)detailSectionDetailFont;	// IMP=0x0000000100162d04
+ (id)mainSectionUnitDetailFont;	// IMP=0x0000000100162ce0
+ (id)mainSectionDetailFont;	// IMP=0x0000000100162cb8
+ (id)headerColor;	// IMP=0x0000000100162ca4
+ (id)headerFont;	// IMP=0x0000000100162c80

@end

