//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MTABedtimeOptionsViewControllerDelegate.h"
#import "MTAlarmDataSourceObserver.h"
#import "MTSleepDataObserver.h"

@class MTABedtimeClockView, MTABedtimeOptionsViewController, MTABedtimeSwitchView, MTABedtimeTimeInBedView, MTABedtimeTimeView, MTAlarmDataSource, MTAlarmManager, NSArray, NSLayoutConstraint, NSString, NSUserActivity, UIScrollView, UIView;

@interface MTABedtimeViewController : UIViewController <MTABedtimeOptionsViewControllerDelegate, MTSleepDataObserver, MTAlarmDataSourceObserver>
{
    NSUserActivity *_userActivity;	// 8 = 0x8
    _Bool _contentViewLoaded;	// 16 = 0x10
    MTAlarmManager *_alarmManager;	// 24 = 0x18
    MTAlarmDataSource *_dataSource;	// 32 = 0x20
    UIScrollView *_scrollView;	// 40 = 0x28
    UIView *_contentView;	// 48 = 0x30
    MTABedtimeSwitchView *_switchView;	// 56 = 0x38
    MTABedtimeTimeView *_sleepTimeView;	// 64 = 0x40
    MTABedtimeTimeView *_wakeTimeView;	// 72 = 0x48
    MTABedtimeClockView *_circleView;	// 80 = 0x50
    MTABedtimeTimeInBedView *_timeInBedView;	// 88 = 0x58
    NSArray *_contentViewConstraints;	// 96 = 0x60
    NSLayoutConstraint *_switchViewHeightConstraint;	// 104 = 0x68
    MTABedtimeOptionsViewController *_optionsController;	// 112 = 0x70
}

@property(retain, nonatomic) MTABedtimeOptionsViewController *optionsController; // @synthesize optionsController=_optionsController;
@property(retain, nonatomic) NSLayoutConstraint *switchViewHeightConstraint; // @synthesize switchViewHeightConstraint=_switchViewHeightConstraint;
@property(retain, nonatomic) NSArray *contentViewConstraints; // @synthesize contentViewConstraints=_contentViewConstraints;
@property(nonatomic) _Bool contentViewLoaded; // @synthesize contentViewLoaded=_contentViewLoaded;
@property(retain, nonatomic) MTABedtimeTimeInBedView *timeInBedView; // @synthesize timeInBedView=_timeInBedView;
@property(retain, nonatomic) MTABedtimeClockView *circleView; // @synthesize circleView=_circleView;
@property(retain, nonatomic) MTABedtimeTimeView *wakeTimeView; // @synthesize wakeTimeView=_wakeTimeView;
@property(retain, nonatomic) MTABedtimeTimeView *sleepTimeView; // @synthesize sleepTimeView=_sleepTimeView;
@property(retain, nonatomic) MTABedtimeSwitchView *switchView; // @synthesize switchView=_switchView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) MTAlarmDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) MTAlarmManager *alarmManager; // @synthesize alarmManager=_alarmManager;
- (void).cxx_destruct;	// IMP=0x000000010005c71c
- (void)bedtimeOptionsViewControllerDidCancel:(id)arg1;	// IMP=0x000000010005c548
- (void)bedtimeOptionsViewController:(id)arg1 saveOptionsWithSleepAlarm:(id)arg2;	// IMP=0x000000010005c494
- (void)circleViewDidEndEditing:(id)arg1;	// IMP=0x000000010005c270
- (void)circleViewEdited:(id)arg1;	// IMP=0x000000010005c0a0
- (void)enableSwitchToggled:(id)arg1;	// IMP=0x000000010005bda0
- (void)showOptions:(id)arg1;	// IMP=0x000000010005bb5c
- (void)_reloadView;	// IMP=0x000000010005bb1c
- (void)loadSleepData;	// IMP=0x000000010005b938
- (void)setupRegularLandscapeContentViewConstraints;	// IMP=0x000000010005a8c4
- (void)setupRegularPortraitContentViewConstraints;	// IMP=0x000000010005941c
- (void)setupCompactContentViewConstraints;	// IMP=0x00000001000581f4
- (void)setupContentViewConstraints;	// IMP=0x0000000100057e1c
- (void)setupConstraints;	// IMP=0x0000000100057a60
- (void)willEnterForeground:(id)arg1;	// IMP=0x0000000100057974
- (void)didEnterBackground:(id)arg1;	// IMP=0x0000000100057898
- (void)handleContentSizeCategoryChange:(id)arg1;	// IMP=0x00000001000577c8
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100057598
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100057540
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000574d8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100057458
- (void)_updateOptionsViewForSleepAlarm:(id)arg1;	// IMP=0x00000001000573ec
- (void)_updateTimeInBedViewForSleepAlarm:(id)arg1;	// IMP=0x0000000100057380
- (void)_updateSwitchViewForSleepAlarm:(id)arg1;	// IMP=0x00000001000572b0
- (void)_updateCircleViewsForSleepAlarm:(id)arg1;	// IMP=0x00000001000570ec
- (void)_updateSleepWakeTimeViewsForSleepAlarm:(id)arg1;	// IMP=0x0000000100056f54
- (void)_updateSleepAlarmViewsForSleepAlarm:(id)arg1;	// IMP=0x0000000100056eb8
- (void)_updateSleepAlarmViews;	// IMP=0x0000000100056e44
- (void)viewDidLoad;	// IMP=0x0000000100056c1c
- (void)loadView;	// IMP=0x00000001000563f8
- (void)dataSource:(id)arg1 didRemoveAlarms:(id)arg2;	// IMP=0x0000000100056384
- (void)dataSourceDidReload:(id)arg1;	// IMP=0x0000000100056350
- (void)sleepDataDidChange;	// IMP=0x00000001000562b8
- (void)stopListeningForHealthKitChanges;	// IMP=0x000000010005629c
- (void)startListeningForHealthKitChanges;	// IMP=0x0000000100056280
- (void)dealloc;	// IMP=0x0000000100056228
- (id)initWithAlarmManager:(id)arg1 dataSource:(id)arg2;	// IMP=0x0000000100055d84

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

