//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol MTAStateManagement <NSObject>
- (void)saveState;
- (void)reloadState;

@optional
- (void)teardownForTest:(NSString *)arg1 options:(NSDictionary *)arg2;
- (void)setupForTest:(NSString *)arg1 options:(NSDictionary *)arg2;
- (void)reloadState:(void (^)(void))arg1;
@end

