//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MTATimerIntervalPickerViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MTATimerButtonsController, MTATimerIntervalPickerView, MTATimerPickerCell, MTATimerTimeView, NSString, UIButton, UITableView, UITableViewCell;

@interface MTATimerControlsView : UIView <UITableViewDataSource, UITableViewDelegate, MTATimerIntervalPickerViewDelegate>
{
    MTATimerTimeView *_timeView;	// 8 = 0x8
    MTATimerIntervalPickerView *_timePicker;	// 16 = 0x10
    UITableView *_tableView;	// 24 = 0x18
    MTATimerPickerCell *_pickerCell;	// 32 = 0x20
    UITableViewCell *_toneChooserCell;	// 40 = 0x28
    UIButton *_toneButton;	// 48 = 0x30
    NSString *_toneName;	// 56 = 0x38
    MTATimerButtonsController *_buttonsController;	// 64 = 0x40
    unsigned long long _style;	// 72 = 0x48
    id <TimerControlsTarget> _delegate;	// 80 = 0x50
    unsigned long long _state;	// 88 = 0x58
}

@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;	// IMP=0x0000000100040488
- (void)pickerView:(id)arg1 didChangeSelectedDuration:(double)arg2;	// IMP=0x0000000100040448
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;	// IMP=0x0000000100040420
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010004038c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100040248
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100040240
- (void)layoutSubviews;	// IMP=0x000000010003f994
- (void)setButtonSize:(unsigned long long)arg1;	// IMP=0x000000010003f8ec
- (void)_configureAndAddButton:(id)arg1;	// IMP=0x000000010003f88c
- (void)setState:(unsigned long long)arg1 animate:(_Bool)arg2;	// IMP=0x000000010003f4c4
- (void)updateToneButtonFrame;	// IMP=0x000000010003f430
- (void)setTimerToneName:(id)arg1;	// IMP=0x000000010003f324
- (void)handleLocaleChange;	// IMP=0x000000010003f30c
@property(nonatomic) double countDownDuration;
- (void)setTime:(double)arg1;	// IMP=0x000000010003f29c
- (id)tonePickerFont;	// IMP=0x000000010003f1ac
- (void)handleContentSizeChange;	// IMP=0x000000010003ef30
- (id)initWithDelegate:(id)arg1 style:(unsigned long long)arg2;	// IMP=0x000000010003e608

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

