//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@interface MTAWorldClockGridLayout : UICollectionViewFlowLayout
{
    unsigned long long _rowsPerPage;	// 8 = 0x8
    unsigned long long _columnsPerPage;	// 16 = 0x10
}

@property(nonatomic) unsigned long long columnsPerPage; // @synthesize columnsPerPage=_columnsPerPage;
@property(nonatomic) unsigned long long rowsPerPage; // @synthesize rowsPerPage=_rowsPerPage;
@property(readonly, nonatomic) unsigned long long itemsPerPage;

@end

