//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTATableViewController.h"

#import "MTAAddClockViewControllerDelegate.h"
#import "MTAStateManagement.h"

@class NSArray, NSString, NSUserActivity;

@interface MTAWorldClockTableViewController : MTATableViewController <MTAAddClockViewControllerDelegate, MTAStateManagement>
{
    NSUserActivity *_userActivity;	// 8 = 0x8
    _Bool _shouldStackViewsInCell;	// 16 = 0x10
    NSArray *_pptTestCities;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000317e8
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010003167c
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;	// IMP=0x0000000100031550
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001000313e4
- (void)addClockViewController:(id)arg1 addCity:(id)arg2;	// IMP=0x00000001000311b0
- (id)addViewController;	// IMP=0x0000000100031124
- (void)showAddView;	// IMP=0x0000000100030ed0
- (void)saveScrollPoint;	// IMP=0x0000000100030dfc
- (long long)numberOfItems;	// IMP=0x0000000100030d68
- (float)itemsTableRowHeight;	// IMP=0x0000000100030d54
- (id)noItemsText;	// IMP=0x0000000100030ce4
- (void)setupForTest:(id)arg1 options:(id)arg2;	// IMP=0x0000000100030acc
- (void)saveState;	// IMP=0x0000000100030ac0
- (void)reloadState;	// IMP=0x0000000100030a4c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000309e0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100030840
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010003061c
- (void)viewDidLoad;	// IMP=0x0000000100030518
- (void)handleTextSizeChange:(id)arg1;	// IMP=0x00000001000303f4
- (void)dealloc;	// IMP=0x000000010003039c
- (id)init;	// IMP=0x00000001000300e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

