/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 1, 2019 at 6:52:15 PM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16C5050a)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACM2SVTrustedDevicesViewControllerDelegate <NSObject>
@required
-(void)trustedDevicesViewControllerNeedsRefresh:(id)arg1;
-(void)trustedDevicesViewControllerDidSelectUnableReceiveMessages:(id)arg1;
-(void)downloadImageWithURL:(id)arg1 completionBlock:(/*^block*/id)arg2;
-(void)cancelInProgressImageDownloads;

@end

