/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 1, 2019 at 6:52:17 PM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16C5050a)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSPersistentStoreDescription, RTPersistenceMigrator, NSMutableDictionary, NSCloudKitMirroringDelegate, NSCloudKitMirroringDelegateOptions, NSURL;

@interface RTPersistenceStore : NSObject {

	NSPersistentStoreDescription* _storeDescription;
	RTPersistenceMigrator* _migrator;
	NSMutableDictionary* _userInfo;
	NSCloudKitMirroringDelegate* _mirroringDelegate;
	NSCloudKitMirroringDelegateOptions* _mirroringDelegateOptions;
	unsigned long long _state;

}

@property (nonatomic,retain) NSCloudKitMirroringDelegate * mirroringDelegate;                            //@synthesize mirroringDelegate=_mirroringDelegate - In the implementation block
@property (nonatomic,retain) NSCloudKitMirroringDelegateOptions * mirroringDelegateOptions;              //@synthesize mirroringDelegateOptions=_mirroringDelegateOptions - In the implementation block
@property (assign,nonatomic) unsigned long long state;                                                   //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) RTPersistenceMigrator * migrator;                                           //@synthesize migrator=_migrator - In the implementation block
@property (readonly) NSPersistentStoreDescription * storeDescription;                                    //@synthesize storeDescription=_storeDescription - In the implementation block
@property (readonly) NSURL * URL; 
@property (readonly) NSMutableDictionary * userInfo;                                                     //@synthesize userInfo=_userInfo - In the implementation block
-(id)storeName;
-(NSCloudKitMirroringDelegate *)mirroringDelegate;
-(id)cachedModelWithError:(id*)arg1 ;
-(void)setMirroringDelegate:(NSCloudKitMirroringDelegate *)arg1 ;
-(NSCloudKitMirroringDelegateOptions *)mirroringDelegateOptions;
-(RTPersistenceMigrator *)migrator;
-(void)setMigrator:(RTPersistenceMigrator *)arg1 ;
-(BOOL)addToCoordinator:(id)arg1 lightweightMigration:(BOOL)arg2 vacuum:(BOOL)arg3 allowMirroring:(BOOL)arg4 error:(id*)arg5 ;
-(id)retrieveMetadataWithCoordinator:(id)arg1 error:(id*)arg2 ;
-(BOOL)performVacuumWithCoordinator:(id)arg1 error:(id*)arg2 ;
-(BOOL)updateMetadata:(id)arg1 coordinator:(id)arg2 error:(id*)arg3 ;
-(BOOL)removeFromCoordinator:(id)arg1 error:(id*)arg2 ;
-(BOOL)destroyWithCoordinator:(id)arg1 error:(id*)arg2 ;
-(BOOL)removeStoreAtURL:(id)arg1 error:(id*)arg2 ;
-(BOOL)openWithCoordinator:(id)arg1 configuration:(id)arg2 error:(id*)arg3 ;
-(id)initWithStoreDescription:(id)arg1 ;
-(void)setMirroringDelegateOptions:(NSCloudKitMirroringDelegateOptions *)arg1 ;
-(BOOL)error:(id*)arg1 code:(unsigned long long)arg2 ;
-(NSPersistentStoreDescription *)storeDescription;
-(id)_normalizeError:(id)arg1 storeDescription:(id)arg2 ;
-(BOOL)error:(id*)arg1 inError:(id)arg2 ;
-(id)_validateKeys:(id)arg1 ;
-(id)init;
-(NSMutableDictionary *)userInfo;
-(unsigned long long)state;
-(void)setState:(unsigned long long)arg1 ;
-(NSURL *)URL;
@end

