/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 1, 2019 at 6:52:16 PM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16C5050a)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RTPersistenceDelegate.h>

@protocol OS_dispatch_queue;
@class RTDeviceMO, NSManagedObjectContext, RTPersistenceManager, RTDataProtectionManager, RTAccountManager, RTPlatform, RTMetricManager, RTKeychainManager, RTDefaultsManager, RTLifeCycleManager, NSObject, RTKeepAliveTransaction, RTMemoryTransaction, RTAccount, NSString;

@interface RTPersistenceDriver : NSObject <RTPersistenceDelegate> {

	RTDeviceMO* _resetSyncCurrentDevice;
	NSManagedObjectContext* _resetSyncContext;
	BOOL _requiresDirtyTransaction;
	BOOL _requiresSetupTransaction;
	RTPersistenceManager* _persistenceManager;
	RTDataProtectionManager* _dataProtectionManager;
	RTAccountManager* _accountManager;
	RTPlatform* _currentPlatform;
	RTMetricManager* _metricManager;
	RTKeychainManager* _keychainManager;
	RTDefaultsManager* _defaultsManager;
	RTLifeCycleManager* _lifecycleManager;
	NSObject*<OS_dispatch_queue> _queue;
	RTKeepAliveTransaction* _keepAliveTransaction;
	RTMemoryTransaction* _memoryTransaction;
	long long _cloudSyncAuthorization;
	long long _encryptedDataAvailability;
	RTAccount* _currentAccount;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                   //@synthesize queue=_queue - In the implementation block
@property (retain) RTKeepAliveTransaction * keepAliveTransaction;                  //@synthesize keepAliveTransaction=_keepAliveTransaction - In the implementation block
@property (retain) RTMemoryTransaction * memoryTransaction;                        //@synthesize memoryTransaction=_memoryTransaction - In the implementation block
@property (assign) BOOL requiresDirtyTransaction;                                  //@synthesize requiresDirtyTransaction=_requiresDirtyTransaction - In the implementation block
@property (assign) BOOL requiresSetupTransaction;                                  //@synthesize requiresSetupTransaction=_requiresSetupTransaction - In the implementation block
@property (assign) long long cloudSyncAuthorization;                               //@synthesize cloudSyncAuthorization=_cloudSyncAuthorization - In the implementation block
@property (assign) long long encryptedDataAvailability;                            //@synthesize encryptedDataAvailability=_encryptedDataAvailability - In the implementation block
@property (retain) RTAccount * currentAccount;                                     //@synthesize currentAccount=_currentAccount - In the implementation block
@property (readonly) RTPersistenceManager * persistenceManager;                    //@synthesize persistenceManager=_persistenceManager - In the implementation block
@property (readonly) RTDataProtectionManager * dataProtectionManager;              //@synthesize dataProtectionManager=_dataProtectionManager - In the implementation block
@property (readonly) RTAccountManager * accountManager;                            //@synthesize accountManager=_accountManager - In the implementation block
@property (readonly) RTPlatform * currentPlatform;                                 //@synthesize currentPlatform=_currentPlatform - In the implementation block
@property (readonly) RTMetricManager * metricManager;                              //@synthesize metricManager=_metricManager - In the implementation block
@property (readonly) RTKeychainManager * keychainManager;                          //@synthesize keychainManager=_keychainManager - In the implementation block
@property (retain) RTDefaultsManager * defaultsManager;                            //@synthesize defaultsManager=_defaultsManager - In the implementation block
@property (retain) RTLifeCycleManager * lifecycleManager;                          //@synthesize lifecycleManager=_lifecycleManager - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)shutdown;
-(RTPersistenceManager *)persistenceManager;
-(RTMetricManager *)metricManager;
-(RTAccountManager *)accountManager;
-(RTPlatform *)currentPlatform;
-(id)initWithPersistenceManager:(id)arg1 dataProtectionManager:(id)arg2 accountManager:(id)arg3 platform:(id)arg4 metricManager:(id)arg5 keychainManager:(id)arg6 defaultsManager:(id)arg7 lifecycleManager:(id)arg8 ;
-(RTDefaultsManager *)defaultsManager;
-(void)setDefaultsManager:(RTDefaultsManager *)arg1 ;
-(void)onDataProtectionChange:(id)arg1 ;
-(RTDataProtectionManager *)dataProtectionManager;
-(void)setEncryptedDataAvailability:(long long)arg1 ;
-(long long)encryptedDataAvailability;
-(void)persistenceStore:(id)arg1 failedWithError:(id)arg2 ;
-(id)appleIDsForStore:(id)arg1 ;
-(BOOL)store:(id)arg1 validateAppleIDs:(id)arg2 ;
-(BOOL)prepareStore:(id)arg1 withContext:(id)arg2 error:(id*)arg3 ;
-(BOOL)backupPersistenceStore:(id)arg1 error:(id*)arg2 ;
-(void)onCloudSyncAuthorizationChange:(id)arg1 ;
-(void)onAccountChange:(id)arg1 ;
-(void)setKeepAliveTransaction:(RTKeepAliveTransaction *)arg1 ;
-(void)setMemoryTransaction:(RTMemoryTransaction *)arg1 ;
-(void)_onDataProtectionChange:(id)arg1 ;
-(void)_evaluteDirtyTransactionAfterConfigurationChange:(long long)arg1 ;
-(long long)cloudSyncAuthorization;
-(RTAccount *)currentAccount;
-(void)_setupPersistenceAfterConfigurationChange:(long long)arg1 cloudSyncAuthorization:(long long)arg2 account:(id)arg3 ;
-(void)_onCloudSyncAuthorizationChange:(id)arg1 ;
-(void)setCloudSyncAuthorization:(long long)arg1 ;
-(void)_onAccountChange:(id)arg1 ;
-(void)setCurrentAccount:(RTAccount *)arg1 ;
-(void)setRequiresDirtyTransaction:(BOOL)arg1 ;
-(void)evaluateTransactions;
-(void)setRequiresSetupTransaction:(BOOL)arg1 ;
-(BOOL)requiresDirtyTransaction;
-(BOOL)requiresSetupTransaction;
-(RTKeepAliveTransaction *)keepAliveTransaction;
-(RTMemoryTransaction *)memoryTransaction;
-(unsigned long long)persistenceDeviceClassForPlatform;
-(void)cleanupOlderPersistentStores;
-(BOOL)purgeExpiredRecordsFromPersistenceStore:(id)arg1 withContext:(id)arg2 error:(id*)arg3 ;
-(RTLifeCycleManager *)lifecycleManager;
-(void)persistenceManagerWillStartResetSync:(id)arg1 ;
-(void)persistenceManagerDidFinishResetSync:(id)arg1 ;
-(id)optionsForStoreWithType:(unsigned long long)arg1 error:(id*)arg2 ;
-(id)mirroringOptionsForStoreWithType:(unsigned long long)arg1 ;
-(void)persistenceStore:(id)arg1 encounteredCriticalError:(id)arg2 ;
-(RTKeychainManager *)keychainManager;
-(void)setLifecycleManager:(RTLifeCycleManager *)arg1 ;
-(id)init;
-(void)dealloc;
-(void)start;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

