/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 1, 2019 at 6:52:18 PM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16C5050a)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPlatform.h>

@class NSUserDefaults;

@interface RTPlatform_MobileGestalt : RTPlatform {

	NSUserDefaults* _userDefaults;

}
-(id)deviceClass;
-(BOOL)internalInstall;
-(id)productType;
-(BOOL)supportsCoreRoutineCapability;
-(BOOL)supportsRoutes;
-(BOOL)supportsMagicalMomentsCapability;
-(BOOL)supportsMicroLocations;
-(id)userAssignedDeviceName;
-(id)systemModel;
-(BOOL)iPhonePlatform;
-(BOOL)watchPlatform;
-(BOOL)macOSPlatform;
-(BOOL)simulatorPlatform;
-(BOOL)lowEndHardware;
-(BOOL)supportsMultiUser;
-(BOOL)iPhoneDevice;
-(id)init;
-(id)systemVersion;
-(id)initWithUserDefaults:(id)arg1 ;
@end

