//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "MFApplicationSceneActor.h"
#import "UINavigationControllerDelegate.h"

@class MFMailComposeController, NSString;

@interface ComposeNavigationController : UINavigationController <UINavigationControllerDelegate, MFApplicationSceneActor>
{
    MFMailComposeController *_composeViewController;	// 8 = 0x8
}

+ (void)removeAutosavedMessageWithIdentifier:(id)arg1;	// IMP=0x00000001000053f0
+ (_Bool)hasAutosavedMessageWithIdentifier:(id)arg1;	// IMP=0x000000010000532c
- (void)setDelegate:(id)arg1;	// IMP=0x0000000100005b3c
- (void)securityScopeForURL:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005a9c
- (void)serializedPlaceholderForURL:(id)arg1 mimeType:(id)arg2 contentID:(id)arg3 withHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001000059e4
- (void)serializedPlaceholderForData:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3 contentID:(id)arg4 withHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010000591c
- (void)serializedPlaceholderForFileName:(id)arg1 fileSize:(long long)arg2 mimeType:(id)arg3 contentID:(id)arg4 withHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100005854
- (void)scrollToTopAnimated:(_Bool)arg1;	// IMP=0x0000000100005814
- (_Bool)shouldAutorotate;	// IMP=0x0000000100005778
- (id)withdrawlGestureExclusionRects;	// IMP=0x0000000100005580
- (struct CGRect)withdrawalGestureEngagementRect;	// IMP=0x000000010000555c
- (id)localizedIdentificationString;	// IMP=0x0000000100005538
- (void)willBecomeActiveSceneActor;	// IMP=0x00000001000054d0
- (void)prepareToBeWithdrawnAsActiveSceneActor;	// IMP=0x0000000100005468
- (void)setTopBarDocked:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010000542c
- (void)autosaveWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000053d8
- (void)recoverAutosavedMessageWithIdentifier:(id)arg1;	// IMP=0x0000000100005368
- (int)resolution;	// IMP=0x0000000100005314
- (_Bool)isDirty;	// IMP=0x00000001000052fc
- (id)_mailComposeView;	// IMP=0x00000001000052e4
- (id)_mailComposeController;	// IMP=0x00000001000052d4
- (struct CGRect)frameForAttachmentWithIdentifier:(id)arg1;	// IMP=0x0000000100005214
- (void)_setCompositionContext:(id)arg1;	// IMP=0x00000001000051fc
- (void)setInitialTitle:(id)arg1;	// IMP=0x00000001000051e4
- (void)setContentVisible:(_Bool)arg1;	// IMP=0x00000001000051cc
@property(nonatomic) id <MFMailComposeViewControllerDelegate> mailComposeDelegate;
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100005140
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000050a0
- (id)view;	// IMP=0x0000000100005048
- (void)dealloc;	// IMP=0x0000000100004ff0
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100004eec
- (id)initWithComposition:(id)arg1 mailComposeControllerOptions:(unsigned long long)arg2;	// IMP=0x0000000100004d74
- (id)initWithComposition:(id)arg1;	// IMP=0x0000000100004d64

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

