//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CoreTelephonyClientSubscriberDelegate.h"
#import "TSSIMUnlockDetailViewControllerDelegate.h"
#import "TSSIMUnlockEntryViewDelegate.h"

@class CTXPCServiceSubscriptionContext, CoreTelephonyClient, NSString, TSSubscriptionAction;

@interface TSSIMUnlockDetailViewController : UIViewController <TSSIMUnlockEntryViewDelegate, TSSIMUnlockDetailViewControllerDelegate, CoreTelephonyClientSubscriberDelegate>
{
    _Bool _suppressCancellation;	// 8 = 0x8
    CoreTelephonyClient *_telephonyClient;	// 16 = 0x10
    CTXPCServiceSubscriptionContext *_subscriptionContext;	// 24 = 0x18
    TSSubscriptionAction *_subscriptionAction;	// 32 = 0x20
    NSString *_lockedSIMName;	// 40 = 0x28
    id <TSSIMUnlockDetailViewControllerDelegate> _delegate;	// 48 = 0x30
}

@property(nonatomic) __weak id <TSSIMUnlockDetailViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *lockedSIMName; // @synthesize lockedSIMName=_lockedSIMName;
@property(readonly, nonatomic) TSSubscriptionAction *subscriptionAction; // @synthesize subscriptionAction=_subscriptionAction;
@property(readonly, nonatomic) CTXPCServiceSubscriptionContext *subscriptionContext; // @synthesize subscriptionContext=_subscriptionContext;
- (void).cxx_destruct;	// IMP=0x0000000100003b60
- (_Bool)_appearingOrAppeared;	// IMP=0x0000000100003ab4
- (id)_entryView;	// IMP=0x0000000100003a60
- (id)_detailView;	// IMP=0x0000000100003a54
- (void)_cancelButtonPressed:(id)arg1;	// IMP=0x0000000100003a0c
- (void)simPukEntryErrorDidOccur:(id)arg1 status:(id)arg2;	// IMP=0x0000000100003634
- (void)simPinEntryErrorDidOccur:(id)arg1 status:(id)arg2;	// IMP=0x0000000100003128
- (void)simStatusDidChange:(id)arg1 status:(id)arg2;	// IMP=0x0000000100002d78
- (void)unlockDetailViewController:(id)arg1 didCompleteWithResult:(long long)arg2;	// IMP=0x0000000100002a54
- (void)entryView:(id)arg1 didEnterText:(id)arg2;	// IMP=0x00000001000025ac
- (_Bool)isFirstResponder;	// IMP=0x0000000100002560
- (_Bool)canResignFirstResponder;	// IMP=0x0000000100002514
- (_Bool)resignFirstResponder;	// IMP=0x00000001000024c8
- (_Bool)canBecomeFirstResponder;	// IMP=0x0000000100002464
- (_Bool)becomeFirstResponder;	// IMP=0x0000000100002400
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000020a4
- (void)viewDidLoad;	// IMP=0x0000000100001f2c
- (void)loadView;	// IMP=0x0000000100001dc4
- (id)initWithSubscriptionContext:(id)arg1 subscriptionAction:(id)arg2 suppressCancellation:(_Bool)arg3 delegate:(id)arg4;	// IMP=0x0000000100001b74
- (id)initWithSubscriptionContext:(id)arg1 subscriptionAction:(id)arg2 lockedSIMName:(id)arg3 delegate:(id)arg4;	// IMP=0x000000010000198c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

