//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSSubscriptionAction.h"

@class NSString;

@interface TSSubscriptionPUKUnlockAction : TSSubscriptionAction
{
    NSString *_puk;	// 32 = 0x20
    NSString *_pin1;	// 40 = 0x28
}

@property(readonly, copy, nonatomic) NSString *pin1; // @synthesize pin1=_pin1;
@property(readonly, copy, nonatomic) NSString *puk; // @synthesize puk=_puk;
- (void).cxx_destruct;	// IMP=0x0000000100009824
- (long long)actionSubtype;	// IMP=0x0000000100009764
- (long long)actionType;	// IMP=0x000000010000975c
- (id)copyByApplyingPIN1:(id)arg1;	// IMP=0x00000001000096e0
- (id)copyByApplyingPUK:(id)arg1;	// IMP=0x0000000100009664
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000095b4

@end

