//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "WFServicePINEntryControllerProtocol.h"

@class NSString, NSURL, UINavigationController, WFServicePINEntryViewController;

@interface WFServicePINEntryNavigationController : UIViewController <WFServicePINEntryControllerProtocol>
{
    id <WFPINEntryViewControllerProtocol> _remoteViewControllerProxy;	// 8 = 0x8
    UINavigationController *_navController;	// 16 = 0x10
    WFServicePINEntryViewController *_PINEntryViewController;	// 24 = 0x18
    NSURL *_URL;	// 32 = 0x20
    NSString *_pageTitle;	// 40 = 0x28
}

+ (id)_remoteViewControllerInterface;	// IMP=0x0000000100002ee4
+ (id)_exportedInterface;	// IMP=0x0000000100002ec8
- (void).cxx_destruct;	// IMP=0x0000000100003508
- (void)didCancelEnteringPIN;	// IMP=0x00000001000034f0
- (void)didAcceptEnteredPIN;	// IMP=0x000000010000310c
- (void)cancel;	// IMP=0x00000001000030f0
- (void)setPageTitle:(id)arg1;	// IMP=0x000000010000307c
- (void)setURL:(id)arg1;	// IMP=0x0000000100002f14
- (void)_willAppearInRemoteViewController:(id)arg1;	// IMP=0x0000000100002f00
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0000000100002e68
- (void)viewDidLoad;	// IMP=0x0000000100002c30

@end

