//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface SSSDittoDismissTimer : NSObject
{
    NSTimer *_currentTimer;	// 8 = 0x8
    _Bool _hasSetViewState;	// 16 = 0x10
    _Bool _hasSetInDragAndDrop;	// 17 = 0x11
    _Bool _hasSetShowingSharingUI;	// 18 = 0x12
    _Bool _hasSetShowingWaitingForImageIdentifierUpdatesUI;	// 19 = 0x13
    _Bool _hasSetPerformingDismissAnimation;	// 20 = 0x14
    _Bool _hasSetUserInterfaceHidden;	// 21 = 0x15
    _Bool _inDragAndDrop;	// 22 = 0x16
    _Bool _showingSharingUI;	// 23 = 0x17
    _Bool _showingWaitingForImageIdentifierUpdatesUI;	// 24 = 0x18
    _Bool _performingDismissAnimation;	// 25 = 0x19
    _Bool _userInterfaceHidden;	// 26 = 0x1a
    unsigned long long _viewState;	// 32 = 0x20
    id <SSSDittoDismissTimerDelegate> _delegate;	// 40 = 0x28
}

@property(nonatomic) __weak id <SSSDittoDismissTimerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool userInterfaceHidden; // @synthesize userInterfaceHidden=_userInterfaceHidden;
@property(nonatomic) _Bool performingDismissAnimation; // @synthesize performingDismissAnimation=_performingDismissAnimation;
@property(nonatomic) _Bool showingWaitingForImageIdentifierUpdatesUI; // @synthesize showingWaitingForImageIdentifierUpdatesUI=_showingWaitingForImageIdentifierUpdatesUI;
@property(nonatomic) _Bool showingSharingUI; // @synthesize showingSharingUI=_showingSharingUI;
@property(nonatomic) _Bool inDragAndDrop; // @synthesize inDragAndDrop=_inDragAndDrop;
@property(nonatomic) unsigned long long viewState; // @synthesize viewState=_viewState;
- (void).cxx_destruct;	// IMP=0x0000000100017314
- (void)newScreenshotReceived;	// IMP=0x0000000100016ff0
- (void)userInteractionOccurred;	// IMP=0x0000000100016fe4
@property(readonly, nonatomic) _Bool timerIsRunning;
- (void)_timerFired;	// IMP=0x0000000100016e7c
- (void)_significantTimerEventOccured;	// IMP=0x0000000100016cd8
- (_Bool)_timerShouldBeRunning;	// IMP=0x0000000100016c40
- (id)_stateDescription;	// IMP=0x00000001000169d4
- (id)init;	// IMP=0x00000001000169a0

@end

