//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, UIStepper, UIWebView;

@interface SSSDittoDebugView : UIView
{
    UIButton *_addScreenshotsButton;	// 8 = 0x8
    UIStepper *_numberOfScreenshotsToAddStepper;	// 16 = 0x10
    UILabel *_numberOfScreenshotsToAddIndicatorView;	// 24 = 0x18
    UIButton *_uiCatalogButton;	// 32 = 0x20
    UIWebView *_webView;	// 40 = 0x28
    CDUnknownBlockType _blockToRunForAddScreenshotsButton;	// 48 = 0x30
    id <SSSDittoDebugViewDelegate> _delegate;	// 56 = 0x38
}

@property(nonatomic) __weak id <SSSDittoDebugViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType blockToRunForAddScreenshotsButton; // @synthesize blockToRunForAddScreenshotsButton=_blockToRunForAddScreenshotsButton;
- (void).cxx_destruct;	// IMP=0x0000000100011e9c
- (void)layoutSubviews;	// IMP=0x0000000100011c48
- (void)_uiCatalogButtonPushed;	// IMP=0x0000000100011bc4
@property(readonly, nonatomic) long long numberOfScreenshotsToAdd;
- (void)advanceScrollOffset;	// IMP=0x0000000100011ae8
- (void)_addScreenshotPushed;	// IMP=0x0000000100011aa4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010001171c

@end

