//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SSSScreenshotsViewController;

@protocol SSSScreenshotsViewControllerDelegate <NSObject>
- (void)activityViewControllerDismissedFromScreenshotsViewController:(SSSScreenshotsViewController *)arg1;
- (void)screenshotsViewController:(SSSScreenshotsViewController *)arg1 requestsPresentingActivityViewControllerWithBlock:(void (^)(void))arg2;
- (void)screenshotsViewController:(SSSScreenshotsViewController *)arg1 requestsDeleteForScreenshots:(NSArray *)arg2 forReason:(unsigned long long)arg3;
- (void)dismissRequestedFromScreenshotsViewController:(SSSScreenshotsViewController *)arg1;
@end

