//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SSSScreenshotImageIdentifierUpdateNotifying.h"

@class NSArray, NSMutableArray;

@interface SSSScreenshotManager : NSObject <SSSScreenshotImageIdentifierUpdateNotifying>
{
    NSMutableArray *_screenshots;	// 8 = 0x8
    NSMutableArray *_environmentDescriptionIdentifiersUIIsInterestedIn;	// 16 = 0x10
    NSMutableArray *_environmentDescriptionIdentifiersInActiveDragSession;	// 24 = 0x18
    NSMutableArray *_environmentDescriptionIdentifiersBeingRemoved;	// 32 = 0x20
    NSMutableArray *_environmentDescriptionIdentifiersBeingSaved;	// 40 = 0x28
    NSMutableArray *_imageIdentifierUpdateObservers;	// 48 = 0x30
}

+ (id)sharedScreenshotManager;	// IMP=0x000000010001024c
- (void).cxx_destruct;	// IMP=0x0000000100010304
@property(readonly, nonatomic) NSArray *environmentDescriptionIdentifiersBeingSaved;
@property(readonly, nonatomic) NSArray *environmentDescriptionIdentifiersBeingRemoved;
@property(readonly, nonatomic) NSArray *environmentDescriptionIdentifiersInActiveDragSession;
@property(readonly, nonatomic) NSArray *environmentDescriptionIdentifiersUIIsInterestedIn;
@property(readonly, nonatomic) NSArray *environmentDescriptionIdentifiersBeingTracked;
- (id)description;	// IMP=0x000000010000fe18
- (id)init;	// IMP=0x000000010000fcb8
- (void)_reallyStopTrackingScreenshot:(id)arg1;	// IMP=0x000000010000fab0
- (void)_trackingChanged;	// IMP=0x000000010000fa58
- (void)_screenshotsNoLongerBeingActiveMayHaveChanged;	// IMP=0x000000010000f970
- (void)_reevaluateTrackingForScreenshotWithEnvironmentDescriptionIdentifier:(id)arg1;	// IMP=0x000000010000f878
- (id)_screenshotForEnvironmentDescriptionIdentifier:(id)arg1;	// IMP=0x000000010000f5d8
- (void)performIfNoScreenshotsAreActive:(CDUnknownBlockType)arg1;	// IMP=0x000000010000f58c
- (void)screenshotLeftDragSession:(id)arg1;	// IMP=0x000000010000f4f8
- (void)screenshotEnteredDragSession:(id)arg1;	// IMP=0x000000010000f468
- (void)userInterfaceStoppedBeingInterestedInScreenshot:(id)arg1;	// IMP=0x000000010000f3d4
- (void)userInterfaceBecameInterestedInScreenshot:(id)arg1;	// IMP=0x000000010000f344
- (_Bool)_areAnyScreenshotsActive;	// IMP=0x000000010000f1f8
- (_Bool)_screenshotIsBeingRemoved:(id)arg1;	// IMP=0x000000010000f16c
- (void)removeScreenshot:(id)arg1;	// IMP=0x000000010000ebc8
- (_Bool)_screenshotIsBeingSaved:(id)arg1;	// IMP=0x000000010000eb3c
- (void)saveEditsToScreenshotIfNecessary:(id)arg1;	// IMP=0x000000010000e604
- (void)removeImageIdentifierUpdateObserver:(id)arg1;	// IMP=0x000000010000e5ec
- (void)addImageIdentifierUpdateObserver:(id)arg1;	// IMP=0x000000010000e460
- (void)processImageIdentifierUpdate:(id)arg1;	// IMP=0x000000010000e090
- (id)_screenshotWithEnvironmentDescriptionIdentifier:(id)arg1;	// IMP=0x000000010000ded8
- (id)createScreenshotWithEnvironmentDescription:(id)arg1;	// IMP=0x000000010000de50

@end

