//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SSScreenshotAssetManagerPersistable.h"

@class NSArray, NSSet, NSString, NSUndoManager, PKDrawing, SSEnvironmentDescription, SSSScreenshotImageProvider, SSSScreenshotItemProvider, SSSScreenshotModificationInfo, UIImage;

@interface SSSScreenshot : NSObject <SSScreenshotAssetManagerPersistable>
{
    UIImage *_backingImage;	// 8 = 0x8
    SSSScreenshotItemProvider *_itemProvider;	// 16 = 0x10
    _Bool _hasUnsavedEdits;	// 24 = 0x18
    _Bool _hasEverBeenEdited;	// 25 = 0x19
    _Bool _shouldPromptForDeletion;	// 26 = 0x1a
    NSUndoManager *_undoManager;	// 32 = 0x20
    _Bool _annotationsDirty;	// 40 = 0x28
    PKDrawing *_drawing;	// 48 = 0x30
    id <SSSScreenshotRepresentation> _representation;	// 56 = 0x38
    SSEnvironmentDescription *_environmentDescription;	// 64 = 0x40
    NSArray *_annotations;	// 72 = 0x48
    NSSet *_pixelationPoints;	// 80 = 0x50
    SSSScreenshotImageProvider *_imageProvider;	// 88 = 0x58
    NSString *_identifier;	// 96 = 0x60
    struct SSSCropInfo _cropInfo;	// 104 = 0x68
}

+ (id)nameForScreenshot:(id)arg1;	// IMP=0x0000000100012ae0
@property(readonly, nonatomic) NSUndoManager *undoManager; // @synthesize undoManager=_undoManager;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) SSSScreenshotItemProvider *itemProvider; // @synthesize itemProvider=_itemProvider;
@property(readonly, nonatomic) SSSScreenshotImageProvider *imageProvider; // @synthesize imageProvider=_imageProvider;
@property(retain, nonatomic) NSSet *pixelationPoints; // @synthesize pixelationPoints=_pixelationPoints;
@property(nonatomic) _Bool annotationsDirty; // @synthesize annotationsDirty=_annotationsDirty;
@property(retain, nonatomic) NSArray *annotations; // @synthesize annotations=_annotations;
@property(nonatomic) struct SSSCropInfo cropInfo; // @synthesize cropInfo=_cropInfo;
@property(readonly, nonatomic) SSEnvironmentDescription *environmentDescription; // @synthesize environmentDescription=_environmentDescription;
@property(nonatomic) __weak id <SSSScreenshotRepresentation> representation; // @synthesize representation=_representation;
- (void).cxx_destruct;	// IMP=0x0000000100012f4c
- (void)requestImageWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000129fc
- (void)redo;	// IMP=0x00000001000129bc
- (void)revert;	// IMP=0x00000001000128c4
- (void)undo;	// IMP=0x0000000100012884
@property(readonly, nonatomic) _Bool canRedo;
@property(readonly, nonatomic) _Bool canUndo;
- (void)_informRepresentationOfUndoStackChange;	// IMP=0x000000010001280c
- (void)_undoableModelChangeSequel;	// IMP=0x0000000100012808
- (void)_undoableModelChangePrequel;	// IMP=0x0000000100012804
- (void)_undoNotificationReceived:(id)arg1;	// IMP=0x00000001000127f8
- (void)wasJustSaved;	// IMP=0x00000001000126ec
- (void)wasJustShared;	// IMP=0x00000001000126dc
@property(readonly, nonatomic) _Bool shouldPromptForDeletion;
@property(readonly, nonatomic) _Bool hasEverBeenEdited;
@property(readonly, nonatomic) _Bool hasUnsavedEdits;
- (void)_markAsBeingEdited;	// IMP=0x0000000100012680
- (void)setEnvironmentDescription:(id)arg1;	// IMP=0x000000010001266c
@property(readonly, nonatomic) unsigned long long saveLocation;
@property(retain, nonatomic) PKDrawing *drawing; // @synthesize drawing=_drawing;
- (void)setCropInfoFromContainer:(id)arg1;	// IMP=0x0000000100012268
@property(readonly, nonatomic) SSSScreenshotModificationInfo *modificationInfo;
@property(retain, nonatomic) UIImage *backingImage;
- (void)dealloc;	// IMP=0x0000000100012158
- (id)initWithEnvironmentDescription:(id)arg1;	// IMP=0x0000000100011f3c

@end

