//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPView.h"

@class NSLayoutConstraint, UILabel;

@interface MPVoicemailTableHeaderView : TPView
{
    UILabel *_titleLabel;	// 8 = 0x8
    UILabel *_messageLabel;	// 16 = 0x10
    NSLayoutConstraint *_titleLabelCenterXAnchorLayoutConstraint;	// 24 = 0x18
    NSLayoutConstraint *_titleLabelFirstBaselineLayoutConstraint;	// 32 = 0x20
    NSLayoutConstraint *_titleLabelLastBaselineLayoutConstraint;	// 40 = 0x28
    NSLayoutConstraint *_titleLabelLeadingLayoutConstraint;	// 48 = 0x30
    NSLayoutConstraint *_titleLabelTrailingLayoutConstraint;	// 56 = 0x38
    NSLayoutConstraint *_messageLabelCenterXAnchorLayoutConstraint;	// 64 = 0x40
    NSLayoutConstraint *_messageLabelFirstBaselineLayoutConstraint;	// 72 = 0x48
    NSLayoutConstraint *_messageLabelLastBaselineLayoutConstraint;	// 80 = 0x50
    NSLayoutConstraint *_messageLabelLeadingLayoutConstraint;	// 88 = 0x58
    NSLayoutConstraint *_messageLabelTrailingLayoutConstraint;	// 96 = 0x60
}

@property(retain, nonatomic) NSLayoutConstraint *messageLabelTrailingLayoutConstraint; // @synthesize messageLabelTrailingLayoutConstraint=_messageLabelTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *messageLabelLeadingLayoutConstraint; // @synthesize messageLabelLeadingLayoutConstraint=_messageLabelLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *messageLabelLastBaselineLayoutConstraint; // @synthesize messageLabelLastBaselineLayoutConstraint=_messageLabelLastBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *messageLabelFirstBaselineLayoutConstraint; // @synthesize messageLabelFirstBaselineLayoutConstraint=_messageLabelFirstBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *messageLabelCenterXAnchorLayoutConstraint; // @synthesize messageLabelCenterXAnchorLayoutConstraint=_messageLabelCenterXAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelTrailingLayoutConstraint; // @synthesize titleLabelTrailingLayoutConstraint=_titleLabelTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelLeadingLayoutConstraint; // @synthesize titleLabelLeadingLayoutConstraint=_titleLabelLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelLastBaselineLayoutConstraint; // @synthesize titleLabelLastBaselineLayoutConstraint=_titleLabelLastBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelFirstBaselineLayoutConstraint; // @synthesize titleLabelFirstBaselineLayoutConstraint=_titleLabelFirstBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelCenterXAnchorLayoutConstraint; // @synthesize titleLabelCenterXAnchorLayoutConstraint=_titleLabelCenterXAnchorLayoutConstraint;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;	// IMP=0x0000000100074c50
- (double)titleLabelTrailingLayoutConstraintConstant;	// IMP=0x0000000100074a98
- (double)titleLabelLeadingLayoutConstraintConstant;	// IMP=0x0000000100074a90
- (double)titleLabelLastBaselineLayoutConstraintConstant;	// IMP=0x0000000100074a84
- (double)titleLabelFirstBaselineLayoutConstraintConstant;	// IMP=0x0000000100074998
- (double)messageLabelTrailingLayoutConstraintConstant;	// IMP=0x0000000100074990
- (double)messageLabelLeadingLayoutConstraintConstant;	// IMP=0x0000000100074988
- (double)messageLabelLastBaselineLayoutConstraintConstant;	// IMP=0x000000010007489c
- (double)messageLabelFirstBaselineLayoutConstraintConstant;	// IMP=0x00000001000747b0
- (void)updateLabels;	// IMP=0x00000001000746a4
- (void)updateFonts;	// IMP=0x00000001000745d8
- (void)updateConstraintsConstants;	// IMP=0x0000000100074350
- (void)loadConstraints;	// IMP=0x0000000100073974
- (void)loadView;	// IMP=0x00000001000736f0
- (void)commonInit;	// IMP=0x00000001000736a0
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100073664

@end

