//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPTableViewCell.h"

#import "VMActivityButtonsViewDelegate.h"
#import "VMMessageToolbarDelegate.h"

@class MPVoicemailMessageTableViewCellScrollView, NSLayoutConstraint, NSString, UIDateLabel, UIImageView, UITapGestureRecognizer, VMMessageMetadataView, VMMessageToolbar, VMMessageTranscriptView, VMPlayerControlsView;

@interface MPVoicemailMessageTableViewCell : TPTableViewCell <VMActivityButtonsViewDelegate, VMMessageToolbarDelegate>
{
    _Bool _expanded;	// 8 = 0x8
    _Bool _showsPlayerControls;	// 9 = 0x9
    _Bool _showsTranscriptionView;	// 10 = 0xa
    UIImageView *_unreadIndicatorImageView;	// 16 = 0x10
    NSString *_localizedTranscriptionMessage;	// 24 = 0x18
    NSString *_localizedSenderIdentityTitle;	// 32 = 0x20
    id <MPVoicemailMessageTableViewCellDelegate> _delegate;	// 40 = 0x28
    VMMessageMetadataView *_metadataView;	// 48 = 0x30
    VMPlayerControlsView *_playerControlsView;	// 56 = 0x38
    VMMessageToolbar *_toolbar;	// 64 = 0x40
    VMMessageTranscriptView *_transcriptView;	// 72 = 0x48
    NSLayoutConstraint *_maximumHeightConstraint;	// 80 = 0x50
    MPVoicemailMessageTableViewCellScrollView *_containerScrollView;	// 88 = 0x58
    UITapGestureRecognizer *_metadataViewTapGestureRecognizer;	// 96 = 0x60
    NSLayoutConstraint *_containerTopLayoutConstraint;	// 104 = 0x68
    NSLayoutConstraint *_containerBottomLayoutConstraint;	// 112 = 0x70
    NSLayoutConstraint *_containerLeadingLayoutConstraint;	// 120 = 0x78
    NSLayoutConstraint *_containerTrailingLayoutConstraint;	// 128 = 0x80
    NSLayoutConstraint *_containerHeightLayoutConstraint;	// 136 = 0x88
    NSLayoutConstraint *_metadataViewBottomLayoutConstraint;	// 144 = 0x90
    NSLayoutConstraint *_metadataViewLeadingLayoutConstraint;	// 152 = 0x98
    NSLayoutConstraint *_metadataViewTopLayoutConstraint;	// 160 = 0xa0
    NSLayoutConstraint *_metadataViewTrailingLayoutConstraint;	// 168 = 0xa8
    NSLayoutConstraint *_playerControlsViewLeftLayoutConstraint;	// 176 = 0xb0
    NSLayoutConstraint *_playerControlsViewTopLayoutConstraint;	// 184 = 0xb8
    NSLayoutConstraint *_playerControlsViewRightLayoutConstraint;	// 192 = 0xc0
    NSLayoutConstraint *_playerControlsViewTimelineSliderTopLayoutConstraint;	// 200 = 0xc8
    NSLayoutConstraint *_toolbarBottomLayoutConstraint;	// 208 = 0xd0
    NSLayoutConstraint *_toolbarLeadingLayoutConstraint;	// 216 = 0xd8
    NSLayoutConstraint *_toolbarTopLayoutConstraint;	// 224 = 0xe0
    NSLayoutConstraint *_toolbarTrailingLayoutConstraint;	// 232 = 0xe8
    NSLayoutConstraint *_transcriptViewBottomLayoutConstraint;	// 240 = 0xf0
    NSLayoutConstraint *_transcriptViewLeadingLayoutConstraint;	// 248 = 0xf8
    NSLayoutConstraint *_transcriptViewTopLayoutConstraint;	// 256 = 0x100
    NSLayoutConstraint *_transcriptViewTrailingLayoutConstraint;	// 264 = 0x108
    NSLayoutConstraint *_unreadIndicatorImageViewHeightLayoutConstraint;	// 272 = 0x110
    NSLayoutConstraint *_unreadIndicatorImageViewLeadingLayoutConstraint;	// 280 = 0x118
    NSLayoutConstraint *_unreadIndicatorImageViewTopLayoutConstraint;	// 288 = 0x120
    NSLayoutConstraint *_unreadIndicatorImageViewWidthLayoutConstraint;	// 296 = 0x128
}

+ (double)unreadIndicatorImageViewWidthLayoutConstraintConstantForContentSizeCategory:(id)arg1;	// IMP=0x00000001000c2020
+ (double)unreadIndicatorImageViewLeadingLayoutConstraintConstantForContentSizeCategory:(id)arg1;	// IMP=0x00000001000c2018
+ (double)metadataViewLeadingLayoutConstraintConstantForContentSizeCategory:(id)arg1;	// IMP=0x00000001000c2010
+ (struct UIEdgeInsets)separatorInsetForContentSizeCategory:(id)arg1;	// IMP=0x00000001000c1f74
+ (id)reuseIdentifier;	// IMP=0x00000001000c1f48
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewWidthLayoutConstraint; // @synthesize unreadIndicatorImageViewWidthLayoutConstraint=_unreadIndicatorImageViewWidthLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewTopLayoutConstraint; // @synthesize unreadIndicatorImageViewTopLayoutConstraint=_unreadIndicatorImageViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewLeadingLayoutConstraint; // @synthesize unreadIndicatorImageViewLeadingLayoutConstraint=_unreadIndicatorImageViewLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewHeightLayoutConstraint; // @synthesize unreadIndicatorImageViewHeightLayoutConstraint=_unreadIndicatorImageViewHeightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewTrailingLayoutConstraint; // @synthesize transcriptViewTrailingLayoutConstraint=_transcriptViewTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewTopLayoutConstraint; // @synthesize transcriptViewTopLayoutConstraint=_transcriptViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewLeadingLayoutConstraint; // @synthesize transcriptViewLeadingLayoutConstraint=_transcriptViewLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewBottomLayoutConstraint; // @synthesize transcriptViewBottomLayoutConstraint=_transcriptViewBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarTrailingLayoutConstraint; // @synthesize toolbarTrailingLayoutConstraint=_toolbarTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarTopLayoutConstraint; // @synthesize toolbarTopLayoutConstraint=_toolbarTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarLeadingLayoutConstraint; // @synthesize toolbarLeadingLayoutConstraint=_toolbarLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarBottomLayoutConstraint; // @synthesize toolbarBottomLayoutConstraint=_toolbarBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewTimelineSliderTopLayoutConstraint; // @synthesize playerControlsViewTimelineSliderTopLayoutConstraint=_playerControlsViewTimelineSliderTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewRightLayoutConstraint; // @synthesize playerControlsViewRightLayoutConstraint=_playerControlsViewRightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewTopLayoutConstraint; // @synthesize playerControlsViewTopLayoutConstraint=_playerControlsViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewLeftLayoutConstraint; // @synthesize playerControlsViewLeftLayoutConstraint=_playerControlsViewLeftLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewTrailingLayoutConstraint; // @synthesize metadataViewTrailingLayoutConstraint=_metadataViewTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewTopLayoutConstraint; // @synthesize metadataViewTopLayoutConstraint=_metadataViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewLeadingLayoutConstraint; // @synthesize metadataViewLeadingLayoutConstraint=_metadataViewLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewBottomLayoutConstraint; // @synthesize metadataViewBottomLayoutConstraint=_metadataViewBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerHeightLayoutConstraint; // @synthesize containerHeightLayoutConstraint=_containerHeightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerTrailingLayoutConstraint; // @synthesize containerTrailingLayoutConstraint=_containerTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerLeadingLayoutConstraint; // @synthesize containerLeadingLayoutConstraint=_containerLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerBottomLayoutConstraint; // @synthesize containerBottomLayoutConstraint=_containerBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerTopLayoutConstraint; // @synthesize containerTopLayoutConstraint=_containerTopLayoutConstraint;
@property(retain, nonatomic) UITapGestureRecognizer *metadataViewTapGestureRecognizer; // @synthesize metadataViewTapGestureRecognizer=_metadataViewTapGestureRecognizer;
@property(retain, nonatomic) MPVoicemailMessageTableViewCellScrollView *containerScrollView; // @synthesize containerScrollView=_containerScrollView;
@property(retain, nonatomic) NSLayoutConstraint *maximumHeightConstraint; // @synthesize maximumHeightConstraint=_maximumHeightConstraint;
@property(readonly, nonatomic) VMMessageTranscriptView *transcriptView; // @synthesize transcriptView=_transcriptView;
@property(readonly, nonatomic) VMMessageToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(readonly, nonatomic) VMPlayerControlsView *playerControlsView; // @synthesize playerControlsView=_playerControlsView;
@property(readonly, nonatomic) VMMessageMetadataView *metadataView; // @synthesize metadataView=_metadataView;
@property(nonatomic) _Bool showsTranscriptionView; // @synthesize showsTranscriptionView=_showsTranscriptionView;
@property(nonatomic) _Bool showsPlayerControls; // @synthesize showsPlayerControls=_showsPlayerControls;
@property(nonatomic) __weak id <MPVoicemailMessageTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *localizedSenderIdentityTitle; // @synthesize localizedSenderIdentityTitle=_localizedSenderIdentityTitle;
@property(copy, nonatomic) NSString *localizedTranscriptionMessage; // @synthesize localizedTranscriptionMessage=_localizedTranscriptionMessage;
@property(retain, nonatomic) UIImageView *unreadIndicatorImageView; // @synthesize unreadIndicatorImageView=_unreadIndicatorImageView;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
- (void).cxx_destruct;	// IMP=0x00000001000c67a0
- (void)messageToolbar:(id)arg1 handleActionForButtonType:(unsigned long long)arg2;	// IMP=0x00000001000c60d0
- (void)activityButtonsView:(id)arg1 handleActionForButtonType:(unsigned long long)arg2 event:(id)arg3;	// IMP=0x00000001000c5f50
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x00000001000c5e30
- (void)updateConstraintsConstants;	// IMP=0x00000001000c5d50
@property(readonly, nonatomic) double unreadIndicatorImageViewWidthLayoutConstraintConstant;
@property(readonly, nonatomic) double unreadIndicatorImageViewTopLayoutConstraintConstant;
@property(readonly, nonatomic) double unreadIndicatorImageViewLeadingLayoutConstraintConstant;
@property(readonly, nonatomic) double toolbarLeadingLayoutConstraintConstant;
@property(readonly, nonatomic) double playerControlsViewTimelineSliderTopLayoutConstraintConstant;
@property(readonly, nonatomic) double playerControlsViewRightLayoutConstraintConstant;
@property(readonly, nonatomic) double metadataViewTrailingLayoutConstraintConstant;
@property(readonly, nonatomic) double metadataViewLeadingLayoutConstraintConstant;
- (void)handleMetadataViewTapGesture:(id)arg1;	// IMP=0x00000001000c5870
- (_Bool)shouldShowTranscriptView;	// IMP=0x00000001000c57d8
- (void)unloadConstraints;	// IMP=0x00000001000c50e4
- (void)loadConstraints;	// IMP=0x00000001000c3180
- (void)loadContentView;	// IMP=0x00000001000c2cf4
- (void)willTransitionToState:(unsigned long long)arg1;	// IMP=0x00000001000c2bb4
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000c2b28
@property(copy, nonatomic) NSString *localizedSubtitle;
@property(copy, nonatomic) NSString *localizedTitle;
@property(copy, nonatomic) NSString *localizedDuration;
@property(copy, nonatomic) NSString *localizedDate;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000c209c
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000c208c
@property(readonly, nonatomic) UIDateLabel *dateLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

