//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface PHCarPlayPhoneCallContainer : UIView
{
    _Bool _shouldMerge;	// 8 = 0x8
    _Bool _merging;	// 9 = 0x9
    id <MPCarPlayPhoneCallContainerDataSource> _dataSource;	// 16 = 0x10
    id <MPCarPlayPhoneCallContainerDelegate> _delegate;	// 24 = 0x18
    NSMutableArray *_visibleCells;	// 32 = 0x20
}

@property(getter=isMerging) _Bool merging; // @synthesize merging=_merging;
@property _Bool shouldMerge; // @synthesize shouldMerge=_shouldMerge;
@property(retain) NSMutableArray *visibleCells; // @synthesize visibleCells=_visibleCells;
@property(nonatomic) id <MPCarPlayPhoneCallContainerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id <MPCarPlayPhoneCallContainerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x00000001000be39c
- (id)constraintToFillContainerWithLeftOfCell:(id)arg1;	// IMP=0x00000001000be2d8
- (void)addRelationForLeftOfCell:(id)arg1;	// IMP=0x00000001000be184
- (id)constraintToFillContainerWithRightOfCell:(id)arg1;	// IMP=0x00000001000be154
- (void)addRelationForRightOfCell:(id)arg1;	// IMP=0x00000001000bdfcc
- (void)addRelationForWidthOfCell:(id)arg1;	// IMP=0x00000001000bde78
- (void)updateAllCellConstraints;	// IMP=0x00000001000bdc74
- (void)mergeAllCellConstraints;	// IMP=0x00000001000bdb28
- (void)addConstraintsForNewCell:(id)arg1;	// IMP=0x00000001000bd97c
- (void)removeAllConstraintsForCell:(id)arg1;	// IMP=0x00000001000bd78c
- (void)removeVisibleCells:(unsigned long long)arg1;	// IMP=0x00000001000bd5b0
- (void)createVisibleCells:(unsigned long long)arg1;	// IMP=0x00000001000bd470
- (void)mergeVisibleCells;	// IMP=0x00000001000bd170
- (void)phoneCallViewCellTapped:(id)arg1;	// IMP=0x00000001000bd058
- (void)animateLayoutOfViewWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bcf94
- (void)updateLayoutAnimated:(_Bool)arg1;	// IMP=0x00000001000bcf28
- (void)updateNumberOfCellsWithNewValue:(unsigned long long)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000bcdf0
- (void)setNeedsMerge;	// IMP=0x00000001000bcddc
- (void)updateCell:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;	// IMP=0x00000001000bcbbc
- (void)reloadDataAnimated:(_Bool)arg1;	// IMP=0x00000001000bc918
- (_Bool)shouldReloadCellsWithNumberOfCells:(unsigned long long)arg1;	// IMP=0x00000001000bc90c
- (void)reloadData;	// IMP=0x00000001000bc8fc
- (void)dealloc;	// IMP=0x00000001000bc898
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000bc7fc
- (id)_reloadQueue;	// IMP=0x00000001000bc78c

@end

