//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericTableViewCell.h"

@class NSLayoutConstraint, TPBadgeView, UIImageView, UILabel, UIStackView;

@interface PHCarPlayRecentsOngoingMultiwayTableViewCell : PHCarPlayGenericTableViewCell
{
    _Bool _showsOutgoingCallIcon;	// 8 = 0x8
    UILabel *_nameLabel;	// 16 = 0x10
    UIImageView *_joinCallImageView;	// 24 = 0x18
    NSLayoutConstraint *_nameLabelVerticalLayoutConstraint;	// 32 = 0x20
    UILabel *_phoneNumberTypeLabel;	// 40 = 0x28
    UIImageView *_outgoingCallIconImageView;	// 48 = 0x30
    UIStackView *_stackView;	// 56 = 0x38
    TPBadgeView *_badgeView;	// 64 = 0x40
}

@property(retain, nonatomic) TPBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) UIImageView *outgoingCallIconImageView; // @synthesize outgoingCallIconImageView=_outgoingCallIconImageView;
@property(nonatomic) _Bool showsOutgoingCallIcon; // @synthesize showsOutgoingCallIcon=_showsOutgoingCallIcon;
@property(retain, nonatomic) UILabel *phoneNumberTypeLabel; // @synthesize phoneNumberTypeLabel=_phoneNumberTypeLabel;
@property(retain, nonatomic) NSLayoutConstraint *nameLabelVerticalLayoutConstraint; // @synthesize nameLabelVerticalLayoutConstraint=_nameLabelVerticalLayoutConstraint;
@property(retain, nonatomic) UIImageView *joinCallImageView; // @synthesize joinCallImageView=_joinCallImageView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;	// IMP=0x000000010007a228
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100078fa4

@end

