//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHTableViewController.h"

#import "CNUIObjectViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CNAvatarViewControllerSettings, CNContactFormatter, NSArray, NSString;

@interface PHContactsTableViewController : PHTableViewController <UITableViewDataSource, UITableViewDelegate, CNUIObjectViewControllerDelegate>
{
    NSArray *_contactArray;	// 8 = 0x8
    NSArray *_contactHandles;	// 16 = 0x10
    CNAvatarViewControllerSettings *_avatarViewControllerSettings;	// 24 = 0x18
    CNContactFormatter *_contactFormatter;	// 32 = 0x20
}

@property(retain, nonatomic) CNContactFormatter *contactFormatter; // @synthesize contactFormatter=_contactFormatter;
@property(retain, nonatomic) CNAvatarViewControllerSettings *avatarViewControllerSettings; // @synthesize avatarViewControllerSettings=_avatarViewControllerSettings;
@property(readonly, nonatomic) NSArray *contactHandles; // @synthesize contactHandles=_contactHandles;
@property(readonly, nonatomic) NSArray *contactArray; // @synthesize contactArray=_contactArray;
- (void).cxx_destruct;	// IMP=0x0000000100012540
- (id)contactForContact:(id)arg1 contactStore:(id)arg2;	// IMP=0x000000010001227c
- (void)setUpTableView;	// IMP=0x0000000100011fd8
- (id)formattedNameForHandle:(id)arg1 countryCode:(id)arg2;	// IMP=0x0000000100011da4
- (id)handleAtIndex:(long long)arg1;	// IMP=0x0000000100011c94
- (id)contactAtIndex:(long long)arg1;	// IMP=0x0000000100011c10
- (id)hostingViewControllerForController:(id)arg1;	// IMP=0x0000000100011c0c
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;	// IMP=0x0000000100011bbc
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100011998
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100011590
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100011544
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010001153c
- (void)viewDidLoad;	// IMP=0x00000001000114ec
- (id)initWithContactArray:(id)arg1 contactHandles:(id)arg2;	// IMP=0x00000001000113c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

