//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHTableViewController.h"

#import "CNContactViewControllerDelegate.h"

@class NSArray, NSString, PHRecentsController;

@interface PHRecentsTableViewController : PHTableViewController <CNContactViewControllerDelegate>
{
    PHRecentsController *_recentsController;	// 8 = 0x8
    NSArray *_recentCalls;	// 16 = 0x10
}

@property(copy, nonatomic) NSArray *recentCalls; // @synthesize recentCalls=_recentCalls;
@property(readonly, nonatomic) PHRecentsController *recentsController; // @synthesize recentsController=_recentsController;
- (void).cxx_destruct;	// IMP=0x0000000100092a9c
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;	// IMP=0x00000001000928ac
- (id)contactViewControllerForRecentCall:(id)arg1 contact:(id)arg2;	// IMP=0x00000001000925d8
- (id)contactViewControllerForRecentCall:(id)arg1;	// IMP=0x00000001000923b8
- (id)multipleContactsViewControllerForRecentCall:(id)arg1;	// IMP=0x0000000100091f18
- (void)handlePHRecentsControllerRecentCallsDidChangeNotification:(id)arg1;	// IMP=0x0000000100091dc8
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100091c9c
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;	// IMP=0x0000000100091bf4
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100091ba8
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100091ba0
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100091b84
- (void)handleUIApplicationDidEnterBackgroundNotification:(id)arg1;	// IMP=0x0000000100091b14
- (void)updateView;	// IMP=0x0000000100091a3c
- (void)updateNavigationItemsForEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100091a38
- (void)showRecentCallDetailsViewControllerForRecentCall:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100091604
- (void)removeRecentCallsAtIndexPaths:(id)arg1;	// IMP=0x0000000100090f98
- (void)removeRecentCallAtIndexPath:(id)arg1;	// IMP=0x0000000100090edc
- (id)recentCallAtIndexPath:(id)arg1;	// IMP=0x0000000100090ea0
- (id)recentCallAtIndex:(long long)arg1;	// IMP=0x0000000100090e1c
- (void)reloadDataIfNeeded;	// IMP=0x0000000100090d08
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100090c10
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100090b70
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100090a84
- (void)viewDidLoad;	// IMP=0x00000001000908ec
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000908b0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100090874
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100090838
- (id)init;	// IMP=0x00000001000907fc
- (id)initWithRecentsController:(id)arg1;	// IMP=0x0000000100090724

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

