//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHPreferences.h"

@interface PHSpringBoardPreferences : PHPreferences
{
}

+ (id)sharedPreferences;	// IMP=0x000000010006ba8c
@property(readonly, nonatomic, getter=isProximitySensorAvailable) _Bool proximitySensorAvailable;
- (id)domain;	// IMP=0x000000010006bb44

@end

