//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PHUIConfiguration : NSObject
{
}

+ (_Bool)preferShorterStrings;	// IMP=0x000000010004d210
+ (unsigned long long)voicemailLayoutSpacing;	// IMP=0x000000010004d148
+ (unsigned long long)tableViewCellVerticalSpacing;	// IMP=0x000000010004d090
+ (unsigned long long)inCallFaceTimeOverlayUISize;	// IMP=0x000000010004cfc4
+ (_Bool)shouldUseFullScreenPeoplePicker;	// IMP=0x000000010004cf80
+ (unsigned long long)pipStatusBarPadding;	// IMP=0x000000010004ceb8
+ (double)pipRadius;	// IMP=0x000000010004ce04
+ (double)pipPartialHomeOffset;	// IMP=0x000000010004cd50
+ (double)pipWallInset;	// IMP=0x000000010004cc8c
+ (double)pipWidth;	// IMP=0x000000010004cbc8
+ (double)bottomOffsetForFaceTimeUIInLandscapeMode;	// IMP=0x000000010004cb14
+ (double)topOffsetForFaceTimeUIInLandscapeMode;	// IMP=0x000000010004ca5c
+ (unsigned long long)contentViewSizeForFaceTime;	// IMP=0x000000010004c9a4
+ (_Bool)canRotateInCallUIOverlayForFaceTime;	// IMP=0x000000010004c99c
+ (_Bool)canAutoRotateInCallUIForFaceTimeAudio;	// IMP=0x000000010004c8f4
+ (_Bool)canAutoRotateInCallUIForFaceTime;	// IMP=0x000000010004c84c
+ (double)yParticipantsViewAdjustmentForKeypad;	// IMP=0x000000010004c7d4
+ (double)yOffsetForParticipantsView;	// IMP=0x000000010004c704
+ (double)yOffsetForDialerLCDView;	// IMP=0x000000010004c678
+ (unsigned long long)handsetDialerSize;	// IMP=0x000000010000d398
+ (unsigned long long)handsetDialerSpacing;	// IMP=0x000000010000d2e0
+ (unsigned long long)inCallBottomBarAssetSize;	// IMP=0x000000010004c5ac
+ (unsigned long long)inCallSlideToAnswerSize;	// IMP=0x000000010004c4f0
+ (unsigned long long)inCallControlSize;	// IMP=0x000000010004c430
+ (unsigned long long)inCallBottomBarMaxTitleSize;	// IMP=0x000000010004c378
+ (unsigned long long)inCallBottomBarLowerOffset;	// IMP=0x000000010004c2b8
+ (unsigned long long)inCallBottomBarSpacing;	// IMP=0x000000010004c1f8
+ (unsigned long long)inCallControlSpacing;	// IMP=0x000000010004c138
+ (unsigned long long)inCallControlAlignment;	// IMP=0x000000010004c074
+ (unsigned long long)screenSize;	// IMP=0x000000010000bf50
+ (id)dialerColor;	// IMP=0x000000010000bdb0
+ (double)dialerLCDLabelFontSizeInCall;	// IMP=0x000000010001111c
+ (double)dialerLCDLabelFontSize;	// IMP=0x000000010000ca84
+ (double)dialerLCDFontSizeInCall;	// IMP=0x0000000100011050
+ (double)dialerLCDFontSize;	// IMP=0x000000010000bec4

@end

