//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHAudioRecorderDelegate.h"

@class PHAudioRecorder, VMAccount, VMVoicemailGreeting, VMVoicemailManager;

@interface PHVoicemailGreetingModel : NSObject <PHAudioRecorderDelegate>
{
    id <PHVoicemailGreetingModelDelegate> _delegate;	// 8 = 0x8
    long long _greetingState;	// 16 = 0x10
    VMAccount *_account;	// 24 = 0x18
    VMVoicemailGreeting *_currentGreeting;	// 32 = 0x20
    double _maximumGreetingDuration;	// 40 = 0x28
    PHAudioRecorder *_greetingRecorder;	// 48 = 0x30
    double _greetingDuration;	// 56 = 0x38
}

@property(nonatomic) double greetingDuration; // @synthesize greetingDuration=_greetingDuration;
@property(retain, nonatomic) PHAudioRecorder *greetingRecorder; // @synthesize greetingRecorder=_greetingRecorder;
@property(nonatomic) double maximumGreetingDuration; // @synthesize maximumGreetingDuration=_maximumGreetingDuration;
@property(retain, nonatomic) VMVoicemailGreeting *currentGreeting; // @synthesize currentGreeting=_currentGreeting;
@property(readonly, nonatomic) VMAccount *account; // @synthesize account=_account;
@property(nonatomic) long long greetingState; // @synthesize greetingState=_greetingState;
@property(nonatomic) __weak id <PHVoicemailGreetingModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001000b021c
- (id)greetingTempFileLocation;	// IMP=0x00000001000aff20
- (void)audioRecorderEndedWithFile:(id)arg1 duration:(double)arg2 error:(id)arg3;	// IMP=0x00000001000af9ac
- (void)audioRecorderContinuedWithFile:(id)arg1 duration:(double)arg2;	// IMP=0x00000001000af7ec
- (void)audioRecorderStartedWithFile:(id)arg1;	// IMP=0x00000001000af66c
- (void)_handlePlayerDidFinishPlaying:(id)arg1;	// IMP=0x00000001000af65c
- (void)_handlePlayerControllerRateOrStatusChange:(id)arg1;	// IMP=0x00000001000af658
- (void)fetchGreeting;	// IMP=0x00000001000af2b0
- (void)saveGreeting:(unsigned long long)arg1;	// IMP=0x00000001000aed20
- (void)pauseGreeting;	// IMP=0x00000001000aecc0
- (void)playGreeting;	// IMP=0x00000001000aebc4
- (_Bool)greetingExists;	// IMP=0x00000001000aeac8
- (void)_mediaserverReset:(id)arg1;	// IMP=0x00000001000ae9dc
- (void)_loadGreeting:(id)arg1;	// IMP=0x00000001000ae6dc
- (void)stopRecording;	// IMP=0x00000001000ae684
- (void)startRecording;	// IMP=0x00000001000ae398
@property(readonly, nonatomic) VMVoicemailManager *voicemailManager;
- (double)maximumGreetingDurationForAccount:(id)arg1;	// IMP=0x00000001000ae01c
@property(readonly, nonatomic) unsigned long long selectedGreetingType;
- (void)dealloc;	// IMP=0x00000001000adedc
- (id)initWithAccount:(id)arg1;	// IMP=0x00000001000add9c
- (id)init;	// IMP=0x00000001000add60

@end

