//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneNavigationController.h"

#import "VMAccountsViewControllerDelegate.h"
#import "VMPlayerControllerDelegate.h"

@class MPVoicemailController, MPVoicemailTableViewController<PHVoicemailListProtocol>, NSString, PHVoicemailNoContentViewController, UIAlertController, VMAccountProvisioningViewController, VMCallVoicemailViewController, VMPlayerController;

@interface PHVoicemailNavigationController : PhoneNavigationController <VMAccountsViewControllerDelegate, VMPlayerControllerDelegate>
{
    _Bool _previousAccountProvisioningRequired;	// 16 = 0x10
    _Bool _sharedServiceIsSubscribedPreviousValue;	// 17 = 0x11
    _Bool _active;	// 18 = 0x12
    MPVoicemailTableViewController<PHVoicemailListProtocol> *_inboxViewController;	// 24 = 0x18
    MPVoicemailTableViewController<PHVoicemailListProtocol> *_trashViewController;	// 32 = 0x20
    MPVoicemailTableViewController<PHVoicemailListProtocol> *_blockedViewController;	// 40 = 0x28
    PHVoicemailNoContentViewController *_noContentViewController;	// 48 = 0x30
    VMPlayerController *_playerController;	// 56 = 0x38
    MPVoicemailController *_voicemailController;	// 64 = 0x40
    VMAccountProvisioningViewController *_accountProvisioningViewController;	// 72 = 0x48
    VMCallVoicemailViewController *_callVoicemailViewController;	// 80 = 0x50
    UIAlertController *_mailboxStorageAlertController;	// 88 = 0x58
}

+ (CDStruct_5ec447a9)badge;	// IMP=0x000000010000791c
+ (id)tabBarIconName;	// IMP=0x00000001000076c4
+ (id)tabBarIconImage;	// IMP=0x0000000100007634
+ (id)tabBarIconImageName;	// IMP=0x0000000100007698
+ (int)tabViewType;	// IMP=0x000000010007a2cc
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) _Bool sharedServiceIsSubscribedPreviousValue; // @synthesize sharedServiceIsSubscribedPreviousValue=_sharedServiceIsSubscribedPreviousValue;
@property(retain, nonatomic) UIAlertController *mailboxStorageAlertController; // @synthesize mailboxStorageAlertController=_mailboxStorageAlertController;
@property(retain, nonatomic) VMCallVoicemailViewController *callVoicemailViewController; // @synthesize callVoicemailViewController=_callVoicemailViewController;
@property(retain, nonatomic) VMAccountProvisioningViewController *accountProvisioningViewController; // @synthesize accountProvisioningViewController=_accountProvisioningViewController;
@property(nonatomic) _Bool previousAccountProvisioningRequired; // @synthesize previousAccountProvisioningRequired=_previousAccountProvisioningRequired;
@property(retain, nonatomic) MPVoicemailController *voicemailController; // @synthesize voicemailController=_voicemailController;
@property(retain, nonatomic) VMPlayerController *playerController; // @synthesize playerController=_playerController;
- (void).cxx_destruct;	// IMP=0x000000010007c534
@property(readonly, nonatomic, getter=isAccountProvisioningRequired) _Bool accountProvisioningRequired;
@property(readonly, nonatomic) PHVoicemailNoContentViewController *noContentViewController; // @synthesize noContentViewController=_noContentViewController;
@property(readonly, nonatomic) MPVoicemailTableViewController<PHVoicemailListProtocol> *blockedViewController; // @synthesize blockedViewController=_blockedViewController;
@property(readonly, nonatomic) MPVoicemailTableViewController<PHVoicemailListProtocol> *trashViewController; // @synthesize trashViewController=_trashViewController;
@property(readonly, nonatomic) MPVoicemailTableViewController<PHVoicemailListProtocol> *inboxViewController; // @synthesize inboxViewController=_inboxViewController;
- (void)_invalidateBadge;	// IMP=0x000000010007bea0
- (void)playerController:(id)arg1 didSeekToTime:(float)arg2;	// IMP=0x000000010007be24
- (void)playerController:(id)arg1 didChangeToTimeControlStatus:(long long)arg2;	// IMP=0x000000010007bcf0
- (void)playerController:(id)arg1 didChangeToStatus:(long long)arg2;	// IMP=0x000000010007bc1c
- (void)playerController:(id)arg1 didChangeToDuration:(double)arg2;	// IMP=0x000000010007ba98
- (void)playerController:(id)arg1 didChangeToCurrentTime:(float)arg2;	// IMP=0x000000010007b8f8
- (void)playerControllerDidReset:(id)arg1;	// IMP=0x000000010007b8e8
- (void)accountsViewControllerDidFinish:(id)arg1;	// IMP=0x000000010007b84c
- (id)selectedMessageTableViewCell;	// IMP=0x000000010007b6fc
- (id)selectedMessage;	// IMP=0x000000010007b614
- (void)_handleVMVoicemailManagerAccountsDidChangeNotification:(id)arg1;	// IMP=0x000000010007b508
- (void)_handleCTIndicatorsVoicemailNotification:(id)arg1;	// IMP=0x000000010007b474
- (void)_handlePhoneActivationChangedNotification:(id)arg1;	// IMP=0x000000010007b260
- (void)_handleStorageUsageChangedNotification:(id)arg1;	// IMP=0x000000010007b254
- (void)_handleMessageWaitingStateChanged:(id)arg1;	// IMP=0x000000010007b170
- (void)_handleOnlineStateChanged:(id)arg1;	// IMP=0x000000010007b08c
- (void)_handleVoicemailSubscriptionStatusChangedNotification:(id)arg1;	// IMP=0x000000010007aec0
- (void)_handleVoicemailsChangedNotification:(id)arg1;	// IMP=0x000000010007ad0c
- (void)_handleApplicationResumeNotification:(id)arg1;	// IMP=0x000000010007ad00
- (void)removeNotificationObservers;	// IMP=0x000000010007acac
- (void)addNotificationObservers;	// IMP=0x0000000100007738
- (void)_checkMailboxUsage;	// IMP=0x000000010000ef1c
- (void)_updateUIStateForce:(_Bool)arg1;	// IMP=0x0000000100009adc
- (void)_updateUIState;	// IMP=0x0000000100009acc
- (void)handleURL:(id)arg1;	// IMP=0x000000010007a8c4
- (void)viewDidLoad;	// IMP=0x000000010000ee24
- (id)popToRootViewControllerAnimated:(_Bool)arg1;	// IMP=0x000000010007a6dc
- (void)dealloc;	// IMP=0x000000010007a690
- (id)init;	// IMP=0x00000001000075b4
- (_Bool)shouldSnapshot;	// IMP=0x000000010007a688

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

