//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (PHInCallUIUtilities)
- (double)yOriginForCenterOfSuperview;	// IMP=0x0000000100013ff4
- (double)xOriginForCenterOfSuperview;	// IMP=0x0000000100013e9c
- (struct CGAffineTransform)transformToAbutToEdge:(unsigned long long)arg1 ofView:(id)arg2;	// IMP=0x0000000100013c28
@end

