//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMAccountsViewController.h"

#import "PHVoicemailGreetingViewControllerDelegate.h"
#import "TPSetPINViewControllerDelegate.h"
#import "VMAccountsViewDataSource.h"
#import "VMAccountsViewDelegate.h"

@class NSArray, NSString, VMAccount;

@interface VMAccountProvisioningViewController : VMAccountsViewController <PHVoicemailGreetingViewControllerDelegate, TPSetPINViewControllerDelegate, VMAccountsViewDataSource, VMAccountsViewDelegate>
{
    NSArray *_accounts;	// 8 = 0x8
    VMAccount *_selectedAccount;	// 16 = 0x10
}

@property(retain, nonatomic) VMAccount *selectedAccount; // @synthesize selectedAccount=_selectedAccount;
@property(copy, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
- (void).cxx_destruct;	// IMP=0x0000000100041628
- (void)setPINViewControllerFinished:(id)arg1 success:(_Bool)arg2 oldPIN:(id)arg3 newPIN:(id)arg4;	// IMP=0x0000000100040d20
- (void)voicemailGreetingViewControllerFinished:(id)arg1;	// IMP=0x0000000100040b98
- (void)accountsView:(id)arg1 buttonTappedForRowWithIndex:(unsigned long long)arg2;	// IMP=0x000000010004080c
- (id)titleForAccountsView:(id)arg1;	// IMP=0x0000000100040798
- (unsigned long long)numberOfRowsForAccountsView:(id)arg1;	// IMP=0x000000010004074c
- (id)accountsView:(id)arg1 buttonForRowAtIndex:(unsigned long long)arg2;	// IMP=0x00000001000405d0
- (void)updateAccounts;	// IMP=0x00000001000403c8
- (id)accountAtIndex:(unsigned long long)arg1;	// IMP=0x000000010004034c
- (void)viewDidLoad;	// IMP=0x00000001000401d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

