//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPView.h"

@class UIButton;

@interface VMMessageToolbar : TPView
{
    id <VMMessageToolbarDelegate> _delegate;	// 8 = 0x8
    UIButton *_audioRouteButton;	// 16 = 0x10
    UIButton *_dialRequestButton;	// 24 = 0x18
    UIButton *_trashButton;	// 32 = 0x20
}

@property(retain, nonatomic) UIButton *trashButton; // @synthesize trashButton=_trashButton;
@property(retain, nonatomic) UIButton *dialRequestButton; // @synthesize dialRequestButton=_dialRequestButton;
@property(retain, nonatomic) UIButton *audioRouteButton; // @synthesize audioRouteButton=_audioRouteButton;
@property(nonatomic) __weak id <VMMessageToolbarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001000261ac
- (void)handleActionForButtonSender:(id)arg1 event:(id)arg2;	// IMP=0x0000000100025fb4
- (void)updateFonts;	// IMP=0x0000000100025dfc
- (void)loadConstraints;	// IMP=0x0000000100024f88
- (void)commonInit;	// IMP=0x0000000100024c48
- (void)setButtonType:(unsigned long long)arg1 enabled:(_Bool)arg2;	// IMP=0x0000000100024b98
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100024b5c

@end

