//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VMPlayerTimelineSlider;

@protocol VMPlayerTimelineSliderDelegate <NSObject>

@optional
- (void)playerTimelineSlider:(VMPlayerTimelineSlider *)arg1 didChangeElapsedTime:(double)arg2;
- (void)playerTimelineSliderScrubbingDidEnd:(VMPlayerTimelineSlider *)arg1;
- (void)playerTimelineSliderScrubbingDidCancel:(VMPlayerTimelineSlider *)arg1;
- (void)playerTimelineSliderScrubbingDidBegin:(VMPlayerTimelineSlider *)arg1;
@end

