//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ADPreviewAdMetaDataCreator : NSObject
{
}

+ (int)compressionAlgorithmFromType:(int)arg1;	// IMP=0x00000001000079b0
+ (int)compressionTypeFromType:(int)arg1;	// IMP=0x00000001000079a0
+ (id)createAdMetaData:(id)arg1;	// IMP=0x0000000100007144
+ (id)createManifestForTagPreview:(int)arg1;	// IMP=0x0000000100006f20

@end

