//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"

@class NSString, UIWindow;

@interface ADPreviewAppDelegate : UIResponder <UIApplicationDelegate>
{
    UIWindow *_window;	// 8 = 0x8
}

+ (id)appDelegate;	// IMP=0x0000000100009524
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (id)_prepareRootViewController:(id)arg1 sourceApplication:(id)arg2;	// IMP=0x0000000100009890
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;	// IMP=0x0000000100009828
- (void)processURL:(id)arg1 sourceApplication:(id)arg2;	// IMP=0x0000000100009728
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100009638
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x000000010000960c
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;	// IMP=0x00000001000095e4
- (void)openURL:(id)arg1 sourceApplication:(id)arg2;	// IMP=0x0000000100009550
- (void)dealloc;	// IMP=0x00000001000094cc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

