//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSMutableArray, NSString, NSURL, UIActivityIndicatorView;

@interface ADPreviewAdViewController : UICollectionViewController
{
    NSString *_sourceApplication;	// 8 = 0x8
    UIActivityIndicatorView *_activityIndicator;	// 16 = 0x10
    NSURL *_URL;	// 24 = 0x18
    NSMutableArray *_data;	// 32 = 0x20
    double _bannerHeight;	// 40 = 0x28
    double _bannerWidth;	// 48 = 0x30
}

@property(nonatomic) double bannerWidth; // @synthesize bannerWidth=_bannerWidth;
@property(nonatomic) double bannerHeight; // @synthesize bannerHeight=_bannerHeight;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(copy, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) NSString *sourceApplication; // @synthesize sourceApplication=_sourceApplication;
- (void)moveToCenter;	// IMP=0x000000010000872c
- (void)_prepareData:(double)arg1;	// IMP=0x000000010000859c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000083a8
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100008368
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100008344
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x0000000100008164
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x00000001000080a4
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100008038
- (void)_closeApplication;	// IMP=0x0000000100007fa0
- (void)_serverSetupDidFinishNotification:(id)arg1;	// IMP=0x0000000100007ed0
- (void)_bannerViewDidFailToReceiveAdWithError:(id)arg1;	// IMP=0x0000000100007e64
- (void)_bannerViewActionDidFinish:(id)arg1;	// IMP=0x0000000100007e40
- (void)_bannerViewDidLoadAd:(id)arg1;	// IMP=0x0000000100007d88
- (id)_previewCollectionView;	// IMP=0x0000000100007d7c
- (void)viewDidLoad;	// IMP=0x0000000100007b20
- (void)dealloc;	// IMP=0x0000000100007a64
- (void)initWithURL:(id)arg1;	// IMP=0x00000001000079d4

@end

