//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@class NSNumber;

@interface PassbookUIServiceApplication : UIApplication
{
    NSNumber *_statusBarHeightOverride;	// 8 = 0x8
}

+ (_Bool)shouldBackgroundMainThreadOnSuspendedLaunch;	// IMP=0x000000010000492c
@property(retain, nonatomic) NSNumber *statusBarHeightOverride; // @synthesize statusBarHeightOverride=_statusBarHeightOverride;
- (void).cxx_destruct;	// IMP=0x0000000100004958
- (double)statusBarHeight;	// IMP=0x00000001000048cc

@end

