//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFFSetupAssistantGuideUserToBackup, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface BFFAnalyticsManager : NSObject
{
    NSDate *_timingStartDate;	// 8 = 0x8
    long long _timingStartIdentifier;	// 16 = 0x10
    NSMutableDictionary *_skippedPanes;	// 24 = 0x18
    NSMutableDictionary *_buddyChoices;	// 32 = 0x20
    BFFSetupAssistantGuideUserToBackup *_guideUserMetric;	// 40 = 0x28
    NSMutableArray *_stagedMetrics;	// 48 = 0x30
    id _callstack;	// 56 = 0x38
    NSString *_activationADKey;	// 64 = 0x40
    NSString *_appleIDADKey;	// 72 = 0x48
}

+ (id)sharedManager;	// IMP=0x000000010009ec68
@property(retain, nonatomic) NSString *appleIDADKey; // @synthesize appleIDADKey=_appleIDADKey;
@property(retain, nonatomic) NSString *activationADKey; // @synthesize activationADKey=_activationADKey;
- (void).cxx_destruct;	// IMP=0x00000001000a0670
- (void)logOnBoardingPaneTimeShownForPlaceholder:(double)arg1 forVideo:(double)arg2;	// IMP=0x00000001000a0594
- (void)logScreenTimeChoice:(_Bool)arg1;	// IMP=0x00000001000a0518
- (void)logAutoUpdateChoice:(_Bool)arg1;	// IMP=0x00000001000a049c
- (void)logGuideUserToBackupSucceeded:(_Bool)arg1;	// IMP=0x00000001000a0484
- (void)logGuideUserToBackupSelected:(_Bool)arg1;	// IMP=0x00000001000a046c
- (void)logDestinationDeviceClass:(id)arg1;	// IMP=0x00000001000a0454
- (void)logSourceDeviceClass:(id)arg1;	// IMP=0x00000001000a043c
- (void)logMostRecentBackupAge:(long long)arg1;	// IMP=0x00000001000a0424
- (void)logGuideUserToBackupAvailable:(_Bool)arg1;	// IMP=0x00000001000a040c
- (void)logExpressRestoreShown:(_Bool)arg1;	// IMP=0x00000001000a03f4
- (void)commitAnalyticsForRunType:(long long)arg1;	// IMP=0x00000001000a0204
- (void)_commitFeatureChoiceAnalyticsForRunType:(long long)arg1;	// IMP=0x000000010009fe5c
- (void)_commitSkippedPaneAnalyticsForRunType:(long long)arg1;	// IMP=0x000000010009fa80
- (void)clearSkipChoice:(_Bool)arg1 forPane:(long long)arg2;	// IMP=0x000000010009fa1c
- (void)logSkipChoice:(_Bool)arg1 forPane:(long long)arg2;	// IMP=0x000000010009f984
- (void)clearBuddyChoiceForPane:(long long)arg1;	// IMP=0x000000010009f924
- (void)logBuddyChoice:(unsigned long long)arg1 forPane:(long long)arg2;	// IMP=0x000000010009f88c
- (void)logKeyboardChoices:(id)arg1 againstGuessedKeyboards:(id)arg2 forLocaleidentifier:(id)arg3;	// IMP=0x000000010009f730
- (id)_stringForKeyboardList:(id)arg1;	// IMP=0x000000010009f6c4
- (void)logBuddyDuration:(double)arg1 lockedDuration:(double)arg2 forRunType:(long long)arg3;	// IMP=0x000000010009f61c
- (void)logNumberOfBuddySections:(unsigned long long)arg1 forRunType:(long long)arg2;	// IMP=0x000000010009f594
- (void)cancelTiming;	// IMP=0x000000010009f4e4
- (void)finishTimingIfNeededWithEndIdentifier:(id)arg1;	// IMP=0x000000010009f4d4
- (void)finishTimingWithEndIdentifier:(id)arg1;	// IMP=0x000000010009f4c4
- (void)_finishTimingWithEndIdentifier:(id)arg1 hardFailure:(_Bool)arg2;	// IMP=0x000000010009f004
- (void)startUserPerceivedTimingWithStartIdentifier:(long long)arg1;	// IMP=0x000000010009ef18
- (void)stageMetricID:(unsigned int)arg1 metric:(id)arg2;	// IMP=0x000000010009eddc
- (id)init;	// IMP=0x000000010009ece8

@end

