//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface BFFSetupAssistantKeyboardChoices : PBCodable <NSCopying>
{
    unsigned long long _timestamp;	// 8 = 0x8
    NSString *_chosenKeyboards;	// 16 = 0x10
    NSString *_guessedKeyboards;	// 24 = 0x18
    NSString *_localeIdentifier;	// 32 = 0x20
    _Bool _usedDefault;	// 40 = 0x28
    struct {
        unsigned int timestamp:1;
    } _has;	// 44 = 0x2c
}

@property(retain, nonatomic) NSString *guessedKeyboards; // @synthesize guessedKeyboards=_guessedKeyboards;
@property(retain, nonatomic) NSString *chosenKeyboards; // @synthesize chosenKeyboards=_chosenKeyboards;
@property(nonatomic) _Bool usedDefault; // @synthesize usedDefault=_usedDefault;
@property(retain, nonatomic) NSString *localeIdentifier; // @synthesize localeIdentifier=_localeIdentifier;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;	// IMP=0x00000001000ada90
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000ad92c
- (unsigned long long)hash;	// IMP=0x00000001000ad864
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000ad704
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000ad5e8
- (void)copyTo:(id)arg1;	// IMP=0x00000001000ad524
- (void)writeTo:(id)arg1;	// IMP=0x00000001000ad468
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000ad460
- (id)dictionaryRepresentation;	// IMP=0x00000001000acf78
- (id)description;	// IMP=0x00000001000acec4
@property(readonly, nonatomic) _Bool hasGuessedKeyboards;
@property(readonly, nonatomic) _Bool hasChosenKeyboards;
@property(nonatomic) _Bool hasTimestamp;

@end

