//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFFFlowItem.h"

@class NSString, OBPrivacySplashController;

@interface BuddyPrivacyController : NSObject <BFFFlowItem>
{
    OBPrivacySplashController *_viewController;	// 8 = 0x8
    id <BFFFlowItemDelegate> _delegate;	// 16 = 0x10
}

+ (_Bool)controllerNeedsToRun;	// IMP=0x0000000100030350
+ (id)cloudConfigSkipKey;	// IMP=0x0000000100030340
+ (void)initialize;	// IMP=0x00000001000302b8
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100030934
- (void)viewDidAppear;	// IMP=0x00000001000308a0
- (void)controllerDone;	// IMP=0x0000000100030734
- (id)viewController;	// IMP=0x00000001000303f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

