//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFFFlowItemDelegate.h"
#import "BuddyAppleIDSpinnerPageDelegate.h"
#import "RUIObjectModelDelegate.h"
#import "RemoteUIWebViewControllerDelegate.h"

@class AASetupAssistantService, AAUICloudSyncServicesController, ACAccount, ACAccountStore, BuddyAboutPaneLoader, BuddyAppleIDAuthManager, BuddyAppleIDFindMyPhonePage, BuddyAppleIDSignInController, BuddyAppleIDSpinnerPage, BuddyAppleIDiCloudDrivePage, BuddyEmailSetupPage, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSURL, RUILoader, RUIPage, SSAccount, UINavigationController, UIViewController;

@interface BuddyAppleIDController : NSObject <RUIObjectModelDelegate, BuddyAppleIDSpinnerPageDelegate, RemoteUIWebViewControllerDelegate, BFFFlowItemDelegate>
{
    ACAccount *_accountToUpgrade;	// 8 = 0x8
    struct OpaqueCFHTTPCookieStorage *_cookieStorage;	// 16 = 0x10
    SSAccount *_storeAccount;	// 24 = 0x18
    NSString *_storeUsername;	// 32 = 0x20
    NSString *_storePassword;	// 40 = 0x28
    RUILoader *_loader;	// 48 = 0x30
    BuddyAboutPaneLoader *_aboutLoader;	// 56 = 0x38
    NSMutableArray *_objectModels;	// 64 = 0x40
    NSURL *_createAppleIDURL;	// 72 = 0x48
    NSURL *_existingAccountTermsURL;	// 80 = 0x50
    NSURL *_aboutURL;	// 88 = 0x58
    NSURL *_genericTermsURL;	// 96 = 0x60
    _Bool _upgradeIsSkip;	// 104 = 0x68
    _Bool _didLoginDelegates;	// 105 = 0x69
    int _desiredPane;	// 108 = 0x6c
    int _currentPane;	// 112 = 0x70
    _Bool _over13;	// 116 = 0x74
    RUIPage *_loadingPage;	// 120 = 0x78
    AAUICloudSyncServicesController *_iCloudSyncServicesController;	// 128 = 0x80
    BuddyAppleIDFindMyPhonePage *_findMyPhonePage;	// 136 = 0x88
    BuddyEmailSetupPage *_emailSetupPage;	// 144 = 0x90
    BuddyAppleIDiCloudDrivePage *_iCloudDrivePage;	// 152 = 0x98
    BuddyAppleIDSpinnerPage *_upgradeWithTokenAuthSpinnerPage;	// 160 = 0xa0
    NSMutableDictionary *_spinnerApperanceHandlers;	// 168 = 0xa8
    _Bool _restoreFromBackupMode;	// 176 = 0xb0
    int _existingAccountType;	// 180 = 0xb4
    int _operationType;	// 184 = 0xb8
    _Bool _omitITunesBundle;	// 188 = 0xbc
    NSString *_existingAccountID;	// 192 = 0xc0
    NSString *_accountDSID;	// 200 = 0xc8
    _Bool _completingEnablingCloudServices;	// 208 = 0xd0
    ACAccountStore *_upgradeAccountStore;	// 216 = 0xd8
    BuddyAppleIDAuthManager *_authManager;	// 224 = 0xe0
    BuddyAppleIDAuthManager *_twoAccountsiCloudAuthManager;	// 232 = 0xe8
    BuddyAppleIDAuthManager *_twoAccountsiTunesAuthManager;	// 240 = 0xf0
    BuddyAppleIDSignInController *_twoAccountsiCloudSignInPage;	// 248 = 0xf8
    NSDictionary *_twoAccountsiCloudAuthResults;	// 256 = 0x100
    NSString *_emailChoice;	// 264 = 0x108
    CDUnknownBlockType _didAuthCompletion;	// 272 = 0x110
    UIViewController *_authAttemptLandingViewController;	// 280 = 0x118
    _Bool _legacyCreate;	// 288 = 0x120
    NSString *_rawPassword;	// 296 = 0x128
    _Bool _removeBackToSignInPageOnFirstRemoteUIPush;	// 304 = 0x130
    id <BuddyAppleIDControllerDelegate> _delegate;	// 312 = 0x138
    UINavigationController *_navigationController;	// 320 = 0x140
    AASetupAssistantService *_aaService;	// 328 = 0x148
}

@property(nonatomic) _Bool restoreFromBackupMode; // @synthesize restoreFromBackupMode=_restoreFromBackupMode;
@property(retain, nonatomic) UIViewController *authAttemptLandingViewController; // @synthesize authAttemptLandingViewController=_authAttemptLandingViewController;
@property(retain, nonatomic) AASetupAssistantService *aaService; // @synthesize aaService=_aaService;
@property(readonly, nonatomic) int operationType; // @synthesize operationType=_operationType;
@property(copy, nonatomic) NSString *existingAccountID; // @synthesize existingAccountID=_existingAccountID;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak id <BuddyAppleIDControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100083dec
- (void)cleanupRemoteUI;	// IMP=0x0000000100083cd4
- (void)objectModelPressedBack:(id)arg1;	// IMP=0x0000000100083ba8
- (id)parentViewControllerForObjectModel:(id)arg1;	// IMP=0x0000000100083b9c
- (id)_remoteUINavController;	// IMP=0x0000000100083b90
- (void)remoteUIWebViewControllerDonePressed:(id)arg1;	// IMP=0x0000000100083b74
- (void)_removeBackToPageMatchingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000839cc
- (void)loader:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001000835f8
- (void)objectModelDidChange:(id)arg1;	// IMP=0x000000010008307c
- (_Bool)objectModel:(id)arg1 shouldShowModalHTMLViewWithURL:(id)arg2;	// IMP=0x0000000100082f40
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3;	// IMP=0x0000000100082c6c
- (void)objectModel:(id)arg1 pressedButton:(id)arg2 attributes:(id)arg3;	// IMP=0x0000000100082260
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(unsigned long long)arg3;	// IMP=0x0000000100081b9c
- (void)_popObjectModelAnimated:(_Bool)arg1;	// IMP=0x00000001000819fc
- (void)_cleanupLoader;	// IMP=0x00000001000819ac
- (void)_authCompletedShouldProceed:(_Bool)arg1 error:(id)arg2;	// IMP=0x0000000100081754
- (void)appleIDControllerCompletedShouldProceed:(_Bool)arg1 error:(id)arg2;	// IMP=0x0000000100081214
- (void)_popBackToAuthAttemptLandingPage;	// IMP=0x0000000100081120
- (void)cancelAuthentication;	// IMP=0x0000000100081084
- (void)didAuthenticateWithResults:(id)arg1 showPostSignIn:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000802e8
- (void)_clearStoreAccount;	// IMP=0x0000000100080294
- (void)_userRespondedToCombinedTCsWithAgreement:(_Bool)arg1 withSLAVersion:(id)arg2;	// IMP=0x000000010007fe80
- (void)_setAppearanceHandler:(CDUnknownBlockType)arg1 forSpinnerPage:(id)arg2;	// IMP=0x000000010007fd78
- (void)showSpinnerPage:(id)arg1 appearanceHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010007fc54
- (void)buddyAppleIDSpinnerPageDidAppear:(id)arg1;	// IMP=0x000000010007fa18
- (void)_createOrUpdateAppleAccountWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007e60c
- (void)_didNotifyAppleIDLoginPluginsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007e06c
- (void)_loginDelegateAccountsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007d758
- (void)_setupiTunesAndLoginDelegateAccountsCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007d02c
- (void)_nameDevice;	// IMP=0x000000010007ccd8
- (void)_createMeCard;	// IMP=0x000000010007c9ac
- (void)_loadRepairCloudAccountRemoteUIWithContinuationData:(id)arg1;	// IMP=0x000000010007c7f0
- (void)_loadPostSignInRemoteUI;	// IMP=0x000000010007c548
- (void)_showPostSignInRemoteUI;	// IMP=0x000000010007c494
- (void)_showPostSignInPage;	// IMP=0x000000010007bf5c
- (void)flowItemDone:(id)arg1 nextItemClass:(Class)arg2;	// IMP=0x000000010007bf50
- (void)flowItemDone:(id)arg1 nextItem:(id)arg2;	// IMP=0x000000010007bf10
- (void)flowItemDone:(id)arg1;	// IMP=0x000000010007bea0
- (void)showiCloudDrivePageIfNecessary;	// IMP=0x000000010007bbac
- (void)_vetHSAAuthToken:(id)arg1 fullMessage:(id)arg2 sourceAddress:(id)arg3 serviceID:(id)arg4;	// IMP=0x000000010007b814
- (void)_vetIfNeeded;	// IMP=0x000000010007b79c
- (void)buddyEmailSetupPage:(id)arg1 didEnterPassword:(id)arg2;	// IMP=0x000000010007b1fc
- (void)_showEmailSetupPage;	// IMP=0x000000010007b130
- (_Bool)_canAutoSetupEmail;	// IMP=0x000000010007b00c
- (_Bool)_needsEmailSetup;	// IMP=0x000000010007aee8
- (void)_vetEmail;	// IMP=0x000000010007adac
- (_Bool)_needsEmailVetting;	// IMP=0x000000010007ac60
- (void)_vettingCompleted;	// IMP=0x000000010007ac54
- (void)enableTouchIDForPurchasesIfNeededWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007aa94
- (void)_enableTouchIDForPurchasesIfNeeded;	// IMP=0x000000010007a368
- (void)_reallyCompleteEnablingCloudServices;	// IMP=0x000000010007a170
- (void)_reallyEnableBackupAndCloudServices;	// IMP=0x0000000100079e48
- (void)_enableBackupAndCloudServices;	// IMP=0x0000000100079bdc
- (void)_runFacetimeRegistration;	// IMP=0x0000000100079b88
- (id)iCloudRestoreSignInViewController;	// IMP=0x0000000100078f6c
- (id)signInViewController;	// IMP=0x0000000100078278
- (void)_showTwoAccountsiCloudSignInPage;	// IMP=0x00000001000777bc
- (void)_showTwoAccountsiTunesSignInPage;	// IMP=0x0000000100075fcc
- (void)enableCloudServices;	// IMP=0x0000000100075bf4
- (void)runFindMyPhoneFlow;	// IMP=0x0000000100075a3c
- (_Bool)shouldAllowStartOver;	// IMP=0x000000010007594c
- (void)dealloc;	// IMP=0x00000001000758b4
- (void)_showAboutPageErrorForError:(id)arg1;	// IMP=0x00000001000755b0
- (void)_showSignInFailure:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000752d4
- (void)_showPasswordFailureWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100075048
- (void)_showUpdateAppleIDFailure:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100074d6c
- (void)_showCreateAppleIDFailure:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100074aa0
- (void)_loadCreateAppleIDUI;	// IMP=0x00000001000748d4
- (void)_addHeadersToRequest:(id)arg1;	// IMP=0x0000000100074670
- (void)_showSpinnerPageWithIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100074540
- (void)_postSignInRemoteUIFinishedWithSuccess:(_Bool)arg1 error:(id)arg2 withSpinnerAction:(CDUnknownBlockType)arg3;	// IMP=0x00000001000740c0
- (void)createOrUpdateAccountWithDelegateSignIn:(_Bool)arg1;	// IMP=0x0000000100073840
- (void)appleIDFindMyPhoneAboutPressed;	// IMP=0x0000000100073824
- (void)showAboutAppleID;	// IMP=0x0000000100073808
- (void)_loadSkipDataWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100073528
- (void)skipAppleID;	// IMP=0x00000001000734fc
- (void)upgradeiCloudSignInPageDidSkip;	// IMP=0x00000001000733a8
- (void)_upgradeAccountWithPassword:(id)arg1 rawPassword:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100072310
- (void)upgradeAccountWithTokenAuth;	// IMP=0x0000000100071df0
- (void)_beginPostUpgradeAppleIDLoginWithUsername:(id)arg1 password:(id)arg2 continuationKey:(id)arg3 signInController:(id)arg4;	// IMP=0x00000001000717b8
- (void)_beginPostUpgradeAppleIDLoginWithUsername:(id)arg1 password:(id)arg2 signInController:(id)arg3;	// IMP=0x0000000100071748
- (id)silentUpgradeViewControllerWithLoginContext:(id)arg1;	// IMP=0x0000000100071400
- (id)upgradeAccountSignInViewController;	// IMP=0x0000000100070ed8
- (void)_loadUpgradeUIForResponseData:(id)arg1 proceedOnFailure:(_Bool)arg2;	// IMP=0x0000000100070a94
- (_Bool)isLoadingRemoteUI;	// IMP=0x0000000100070a64
- (void)showCreateAppleID;	// IMP=0x0000000100070094
- (void)showiForgot;	// IMP=0x0000000100070084
- (void)showiForgotWithLandingPage:(id)arg1;	// IMP=0x000000010006fa58
- (void)_pushNextViewController:(id)arg1;	// IMP=0x000000010006f93c
- (void)_tryShowingPane;	// IMP=0x000000010006f76c
- (void)_reallyTryShowingPane;	// IMP=0x000000010006f128
- (void)setExistingAccountType:(int)arg1;	// IMP=0x000000010006f0f8
- (void)_downloadURLConfigurationIfNeededCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010006ecb0
- (void)appleIDControllerFinished;	// IMP=0x000000010006eb74
- (id)init;	// IMP=0x000000010006eb64
- (id)initWithAccount:(id)arg1;	// IMP=0x000000010006e62c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

