//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BYLanguageLocaleController.h"

#import "BuddyLanguageController.h"

@class NSArray, NSDictionary, NSString;

@interface BuddyLanguageController : BYLanguageLocaleController <BuddyLanguageController>
{
    NSDictionary *_languageStrings;	// 8 = 0x8
    NSString *_selectedLanguage;	// 16 = 0x10
    _Bool _builtTable;	// 24 = 0x18
    _Bool _hasBeenDisplayed;	// 25 = 0x19
    id <BFFFlowItemDelegate> _delegate;	// 32 = 0x20
    NSArray *_languageCodes;	// 40 = 0x28
}

+ (id)cloudConfigSkipKey;	// IMP=0x0000000100038e8c
@property(retain, nonatomic) NSArray *languageCodes; // @synthesize languageCodes=_languageCodes;
@property(copy, nonatomic) NSString *selectedLanguage; // @synthesize selectedLanguage=_selectedLanguage;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool hasBeenDisplayed; // @synthesize hasBeenDisplayed=_hasBeenDisplayed;
- (void).cxx_destruct;	// IMP=0x0000000100039dc4
- (_Bool)shouldAllowStartOver;	// IMP=0x0000000100039d3c
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100039bb4
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100039a3c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000399f0
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000399e8
- (void)selectLanguage:(id)arg1;	// IMP=0x00000001000396a4
- (void)countryScanCompleted;	// IMP=0x0000000100039670
- (void)dealloc;	// IMP=0x00000001000395f8
- (void)loadView;	// IMP=0x00000001000394c8
- (id)init;	// IMP=0x0000000100039430
- (void)buildTable;	// IMP=0x0000000100038ef0
- (void)startOver;	// IMP=0x0000000100038ee4
- (void)reset;	// IMP=0x0000000100038e94

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

