//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddySimpleTCController.h"

@class BuddyCloudConfigController, NSArray, NSData;

@interface BuddyCloudConfigConsentViewController : BuddySimpleTCController
{
    BuddyCloudConfigController *_configController;	// 48 = 0x30
    NSData *_profileData;	// 56 = 0x38
    NSArray *_profileWarnings;	// 64 = 0x40
}

@property(retain, nonatomic) NSArray *profileWarnings; // @synthesize profileWarnings=_profileWarnings;
@property(retain, nonatomic) NSData *profileData; // @synthesize profileData=_profileData;
@property(nonatomic) __weak BuddyCloudConfigController *configController; // @synthesize configController=_configController;
- (void).cxx_destruct;	// IMP=0x00000001000dab48
- (void)agree:(id)arg1;	// IMP=0x00000001000daa24
- (void)disagree:(id)arg1;	// IMP=0x00000001000da9dc
- (id)titleString;	// IMP=0x00000001000da968
- (id)tcContent;	// IMP=0x00000001000da6c8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000da658

@end

