//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyPasscodeController.h"

@interface BuddyPasscodeMesaController : BuddyPasscodeController
{
}

+ (_Bool)controllerNeedsToRun;	// IMP=0x00000001000314d0
- (_Bool)passcodeViewControllerAllowSkip:(id)arg1;	// IMP=0x00000001000316a4
- (void)passcodeViewController:(id)arg1 didFinishWithPasscodeCreation:(id)arg2;	// IMP=0x00000001000315d8
- (id)passcodeViewControllerCustomFirstEntryInstructions:(id)arg1;	// IMP=0x00000001000315c4
- (_Bool)allowsSkip;	// IMP=0x00000001000315bc

@end

