//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddySimpleTCController.h"

@interface BuddyWarrantyTCController : BuddySimpleTCController
{
}

+ (id)warrantyFilePath;	// IMP=0x00000001000b9be0
- (id)titleString;	// IMP=0x00000001000b9c84
- (id)tcContent;	// IMP=0x00000001000b9be4

@end

