//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UILabel, UIScrollView;

@interface BuddyCloudConfigAboutConfigurationContainerController : UIViewController
{
    _Bool _isSupervised;	// 8 = 0x8
    UIScrollView *_containerView;	// 16 = 0x10
    UILabel *_descriptionLabel;	// 24 = 0x18
    NSString *_organizationName;	// 32 = 0x20
    NSString *_organizationDepartment;	// 40 = 0x28
    NSString *_organizationAddress;	// 48 = 0x30
    NSString *_organizationAddressLine1;	// 56 = 0x38
    NSString *_organizationAddressLine2;	// 64 = 0x40
    NSString *_organizationCity;	// 72 = 0x48
    NSString *_organizationRegion;	// 80 = 0x50
    NSString *_organizationZipCode;	// 88 = 0x58
    NSString *_organizationCountry;	// 96 = 0x60
    NSString *_organizationSupportPhone;	// 104 = 0x68
}

+ (id)defaultParagraphTextAttributes;	// IMP=0x00000001000d3148
@property(nonatomic) _Bool isSupervised; // @synthesize isSupervised=_isSupervised;
@property(copy, nonatomic) NSString *organizationSupportPhone; // @synthesize organizationSupportPhone=_organizationSupportPhone;
@property(copy, nonatomic) NSString *organizationCountry; // @synthesize organizationCountry=_organizationCountry;
@property(copy, nonatomic) NSString *organizationZipCode; // @synthesize organizationZipCode=_organizationZipCode;
@property(copy, nonatomic) NSString *organizationRegion; // @synthesize organizationRegion=_organizationRegion;
@property(copy, nonatomic) NSString *organizationCity; // @synthesize organizationCity=_organizationCity;
@property(copy, nonatomic) NSString *organizationAddressLine2; // @synthesize organizationAddressLine2=_organizationAddressLine2;
@property(copy, nonatomic) NSString *organizationAddressLine1; // @synthesize organizationAddressLine1=_organizationAddressLine1;
@property(copy, nonatomic) NSString *organizationAddress; // @synthesize organizationAddress=_organizationAddress;
@property(copy, nonatomic) NSString *organizationDepartment; // @synthesize organizationDepartment=_organizationDepartment;
@property(copy, nonatomic) NSString *organizationName; // @synthesize organizationName=_organizationName;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UIScrollView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;	// IMP=0x00000001000d42d4
- (id)_descriptionText;	// IMP=0x00000001000d38b4
- (void)controllerDone:(id)arg1;	// IMP=0x00000001000d38a0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000d3724
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000d35d8
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000d32bc

@end

