//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFFFlowItem.h"

@class BuddyAppleIDFindMyPhonePage, NSString;

@interface BuddyAppleIDFMiPUpdateController : NSObject <BFFFlowItem>
{
    BuddyAppleIDFindMyPhonePage *_findMyPhonePage;	// 8 = 0x8
    id <BFFFlowItemDelegate> _delegate;	// 16 = 0x10
}

+ (id)cloudConfigSkipKey;	// IMP=0x00000001000dc8bc
+ (_Bool)controllerNeedsToRun;	// IMP=0x00000001000dc8a8
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001000dca08
- (id)viewController;	// IMP=0x00000001000dc930
- (_Bool)shouldAllowStartOver;	// IMP=0x00000001000dc928
- (_Bool)controllerAllowsNavigatingBack;	// IMP=0x00000001000dc920
- (void)dealloc;	// IMP=0x00000001000dc8c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

