//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface BuddyAppleIDInfoIconView : UIView
{
    NSArray *_imageViews;	// 8 = 0x8
    struct UIEdgeInsets _margins;	// 16 = 0x10
}

+ (void)initialize;	// IMP=0x0000000100067a80
@property(nonatomic) struct UIEdgeInsets margins; // @synthesize margins=_margins;
- (void).cxx_destruct;	// IMP=0x0000000100068174
- (void)layoutSubviews;	// IMP=0x0000000100067f54
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100067d38
- (id)init;	// IMP=0x0000000100067abc

@end

