//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyTableViewController.h"

#import "BFFFlowItem.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MBManager, NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, NSTimer, RestorableBackupItem;

@interface RestoreFromBackupController : BuddyTableViewController <BFFFlowItem, UITableViewDataSource, UITableViewDelegate>
{
    MBManager *_backupManager;	// 8 = 0x8
    NSTimer *_refreshTimer;	// 16 = 0x10
    NSArray *_backupList;	// 24 = 0x18
    _Bool _initialFetchAttemptDone;	// 32 = 0x20
    NSArray *_similarRestorables;	// 40 = 0x28
    NSMutableArray *_visibleSimilarRestorables;	// 48 = 0x30
    NSMutableArray *_otherRestorables;	// 56 = 0x38
    NSMutableArray *_visibleOtherRestorables;	// 64 = 0x40
    int _listState;	// 72 = 0x48
    _Bool _showAllFooterPresent;	// 76 = 0x4c
    NSObject<OS_dispatch_queue> *_update_backup_list_queue;	// 80 = 0x50
    _Bool _appleAccountRemoved;	// 88 = 0x58
    int _compatibleRestoresState;	// 92 = 0x5c
    _Bool _scannedForUpdate;	// 96 = 0x60
    _Bool _scanningForUpdate;	// 97 = 0x61
    id <BFFFlowItemDelegate> _delegate;	// 104 = 0x68
    RestorableBackupItem *_selectedRestorable;	// 112 = 0x70
    NSString *_availableUpdateVersion;	// 120 = 0x78
}

+ (id)cloudConfigSkipKey;	// IMP=0x0000000100033170
@property(copy, nonatomic) NSString *availableUpdateVersion; // @synthesize availableUpdateVersion=_availableUpdateVersion;
@property(nonatomic) _Bool scanningForUpdate; // @synthesize scanningForUpdate=_scanningForUpdate;
@property(retain, nonatomic) RestorableBackupItem *selectedRestorable; // @synthesize selectedRestorable=_selectedRestorable;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100038cfc
- (void)handleDebugGesture;	// IMP=0x0000000100038938
- (void)showAllBackups;	// IMP=0x0000000100038928
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100038584
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100038438
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100037a88
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100037a14
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;	// IMP=0x0000000100037970
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;	// IMP=0x00000001000377b4
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;	// IMP=0x0000000100037488
- (long long)tableView:(id)arg1 titleAlignmentForFooterInSection:(long long)arg2;	// IMP=0x0000000100037454
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0000000100037114
- (long long)tableView:(id)arg1 titleAlignmentForHeaderInSection:(long long)arg2;	// IMP=0x00000001000370e8
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100036fdc
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100036f2c
- (id)restorableItemAtIndexPath:(id)arg1;	// IMP=0x0000000100036e38
- (void)showRestoreWarningsIfNeededForRestorable:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100036544
- (void)setupWithAlternateChoice:(id)arg1;	// IMP=0x000000010003619c
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100036104
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100035e84
- (void)setRefreshTimerToDuration:(double)arg1;	// IMP=0x0000000100035da4
- (void)scanForUpdateIfNecessaryForBackupList:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000358dc
- (void)cancelRestoreAndRemovePrimaryAppleAccount;	// IMP=0x0000000100035800
- (void)refreshBackupListFromTimer:(id)arg1;	// IMP=0x0000000100035784
- (void)updateBackupListCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100035138
- (id)filteredRestorableItemsFromBackupList:(id)arg1;	// IMP=0x0000000100034ec8
- (void)setBackupList:(id)arg1 forceReload:(_Bool)arg2 withError:(id)arg3;	// IMP=0x0000000100034df4
- (void)updateListStateWithReload:(_Bool)arg1;	// IMP=0x0000000100034cc4
- (void)setListState:(int)arg1;	// IMP=0x000000010003467c
- (void)updateVisibleSnapshots;	// IMP=0x0000000100033ee0
- (void)_updateTable:(id)arg1 toMatchArray:(id)arg2 withVisibleArray:(id)arg3 maxVisible:(unsigned long long)arg4 fromOldSection:(long long)arg5 toNewSection:(long long)arg6;	// IMP=0x0000000100033848
- (id)mostSimilarRestorablesInsertRemainingIntoArray:(id)arg1 getOtherUniqueDevicesCount:(unsigned long long *)arg2;	// IMP=0x00000001000334f4
- (void)significantTimeChange;	// IMP=0x000000010003341c
- (id)titleText;	// IMP=0x00000001000333a8
- (void)dealloc;	// IMP=0x0000000100033318
- (id)init;	// IMP=0x0000000100033178

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

