//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SiriUISnippetViewController.h"

@class SAUIButton, SVSBigButtonView;

@interface SVSBigButtonController : SiriUISnippetViewController
{
    SVSBigButtonView *_buttonView;	// 8 = 0x8
    SAUIButton *_buttonObject;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000836e0
- (void)_bigButtonHit:(id)arg1;	// IMP=0x000000010008365c
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x00000001000835f8
- (void)loadView;	// IMP=0x00000001000834b0
- (_Bool)usePlatterStyle;	// IMP=0x00000001000834a8
- (struct UIEdgeInsets)defaultViewInsets;	// IMP=0x0000000100083494
- (id)snippet;	// IMP=0x000000010008348c
- (void)setAceObject:(id)arg1;	// IMP=0x0000000100083428
- (void)dealloc;	// IMP=0x00000001000833a0

@end

