//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SiriUISnippetCollectionViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, SAGuidanceGuideDomainSnippet;

@interface SVSGuideDomainViewController : SiriUISnippetCollectionViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
}

- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x00000001000599b0
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000599a8
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;	// IMP=0x00000001000599a0
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100059794
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100059720
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100059714
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100059548
- (void)setSnippet:(id)arg1;	// IMP=0x00000001000594c4
- (id)_phraseForIndexPath:(id)arg1;	// IMP=0x00000001000593e4
- (_Bool)_showsCategoriesForSection:(unsigned long long)arg1;	// IMP=0x0000000100059394
- (id)_titleForSection:(unsigned long long)arg1;	// IMP=0x00000001000592ec
- (_Bool)usePlatterStyle;	// IMP=0x00000001000592e4
- (_Bool)wantsToManageBackgroundColor;	// IMP=0x00000001000592dc
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x0000000100059030
- (id)_utterancesForSection:(unsigned long long)arg1;	// IMP=0x0000000100058f88
- (long long)_numberOfSections;	// IMP=0x0000000100058f14
- (struct UIEdgeInsets)_headerViewEdgeInsets;	// IMP=0x0000000100058ef8
- (long long)_cellTypeForIndexPath:(id)arg1;	// IMP=0x0000000100058dec
- (double)desiredHeightForHeaderView;	// IMP=0x0000000100058ce0
- (void)configureReusableHeaderView:(id)arg1;	// IMP=0x0000000100058c30
- (Class)headerViewClass;	// IMP=0x0000000100058c1c
- (void)loadView;	// IMP=0x0000000100058a5c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000589c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SAGuidanceGuideDomainSnippet *snippet; // @dynamic snippet;
@property(readonly) Class superclass;

@end

