//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SVSPagerViewController, UIViewController;

@protocol SVSPagerViewControllerDelegate <NSObject>
- (void)pagerViewControllerDidChangeTransitionState:(SVSPagerViewController *)arg1;
- (void)pagerViewController:(SVSPagerViewController *)arg1 didActivatePageViewController:(UIViewController *)arg2 oldActivePageViewController:(UIViewController *)arg3;
@end

