//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVSStarkItemControllerDelegate.h"

@class NSArray, SVSStarkConfirmationSnippetController;

@protocol SVSStarkConfirmationSnippetControllerDelegate <SVSStarkItemControllerDelegate>
- (_Bool)isShowingGatekeeperHeader;
- (void)confirmationSnippetControllerRequestsDismissal:(SVSStarkConfirmationSnippetController *)arg1;
- (void)confirmationSnippetController:(SVSStarkConfirmationSnippetController *)arg1 performAceCommands:(NSArray *)arg2;
@end

