//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SVSSirilandView;

@protocol SVSSirilandViewDelegate <NSObject>
- (double)statusViewHeightForSirilandView:(SVSSirilandView *)arg1;
- (struct CGRect)statusBarFrameForSirilandView:(SVSSirilandView *)arg1;
@end

