//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface SVSStarkGatekeeperHeaderView : UIView
{
    id <SVSStarkGatekeeperHeaderViewDelegate> _delegate;	// 8 = 0x8
    NSString *_appBundleIdentifier;	// 16 = 0x10
}

+ (id)_starkTitleLabel;	// IMP=0x000000010003d824
+ (double)_headerViewSpacerDistance;	// IMP=0x000000010003d4b4
+ (id)gatekeeperForAceObject:(id)arg1;	// IMP=0x000000010003d2fc
+ (id)gatekeeperForRequestOptions:(id)arg1;	// IMP=0x000000010003d23c
@property(retain, nonatomic, getter=_appBundleIdentifier, setter=_setAppBundleIdentifier:) NSString *appBundleIdentifier; // @synthesize appBundleIdentifier=_appBundleIdentifier;
@property(nonatomic) __weak id <SVSStarkGatekeeperHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010003dc1c
- (unsigned long long)_gatekeeperTypeForBundleIdentifier:(id)arg1;	// IMP=0x000000010003db34
- (void)_logGatekeeperDismissedManually;	// IMP=0x000000010003d9b0
- (void)logGatekeeperAppeared;	// IMP=0x000000010003d82c
- (void)_updateForAppBundleIdentifier;	// IMP=0x000000010003d820
- (void)_dismissalButtonTapped:(id)arg1;	// IMP=0x000000010003d774
- (void)dealloc;	// IMP=0x000000010003d650
- (id)initWithAceObject:(id)arg1;	// IMP=0x000000010003d644
- (id)initWithRequestOptions:(id)arg1;	// IMP=0x000000010003d5b8
- (id)_init;	// IMP=0x000000010003d524

@end

