//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, NSObject, NSString, SVSStarkTableViewCell, UIColor;

@protocol SVSStarkTableViewControllerDelegate
- (UIColor *)backgroundColorForTableViewCells;
- (void)didPressShowMore;
- (void)didPressItem:(NSObject *)arg1 atIndex:(unsigned long long)arg2;
- (SVSStarkTableViewCell *)newShowMoreCellWithIdentifier:(NSString *)arg1;
- (Class)showMoreCellClass;
- (void)configureCell:(SVSStarkTableViewCell *)arg1 forItem:(NSObject *)arg2 atIndex:(unsigned long long)arg3;
- (SVSStarkTableViewCell *)newCellWithIdentifier:(NSString *)arg1 forItem:(NSObject *)arg2 atIndex:(unsigned long long)arg3;
- (NSString *)cellIdentifierForItem:(NSObject *)arg1 atIndex:(unsigned long long)arg2;
- (NSDictionary *)tableCellIdentifiersAndClasses;
@end

