//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SiriUIAceObjectViewController.h"

#import "SVSEditableTextViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class AFUserUtterance, NSArray, NSMutableArray, NSMutableDictionary, NSString, SAUIChangePrimaryUtterance, SVSEditableTextView, SVSUserUtteranceContainerView, SVSUserUtteranceView, SiriUICollectionViewFlowLayout, UICollectionView, UITapGestureRecognizer;

@interface SVSUserUtteranceViewController : SiriUIAceObjectViewController <SVSEditableTextViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    SVSUserUtteranceView *_utteranceView;	// 8 = 0x8
    _Bool _changeUtteranceShouldDisplay;	// 16 = 0x10
    UITapGestureRecognizer *_tapRecognizer;	// 24 = 0x18
    NSArray *_speechAlternativeDisplayList;	// 32 = 0x20
    NSMutableArray *_speechAlternativeList;	// 40 = 0x28
    NSMutableArray *_viewArray;	// 48 = 0x30
    SVSEditableTextView *_editableUtteranceView;	// 56 = 0x38
    UICollectionView *_speechAlternativeCollectionView;	// 64 = 0x40
    SiriUICollectionViewFlowLayout *_speechAlternativeCollectionViewLayout;	// 72 = 0x48
    _Bool _showSpeechAlternativeList;	// 80 = 0x50
    SVSUserUtteranceContainerView *_containerView;	// 88 = 0x58
    _Bool _startEditWhenShown;	// 96 = 0x60
    NSString *_speechAlternativeListTitle;	// 104 = 0x68
    NSMutableDictionary *_alternativeInfoMap;	// 112 = 0x70
    _Bool _showOnDeviceResults;	// 120 = 0x78
    NSString *_sessionId;	// 128 = 0x80
    NSString *_originalUtteranceText;	// 136 = 0x88
    NSString *_preCorrectionText;	// 144 = 0x90
    struct CGSize _currentTextSize;	// 152 = 0x98
    _Bool _textChanged;	// 168 = 0xa8
    SAUIChangePrimaryUtterance *_changeUtteranceCommand;	// 176 = 0xb0
    _Bool _newRequestSent;	// 184 = 0xb8
    struct CGSize _oldUtteranceViewSize;	// 192 = 0xc0
    struct CGRect _previousBounds;	// 208 = 0xd0
    _Bool _needsToInvalidateCollectionViewLayoutOnViewWillLayoutSubviews;	// 240 = 0xf0
    double _latestGivenWidth;	// 248 = 0xf8
    _Bool _receivedFinalRecognitionResult;	// 256 = 0x100
    long long _speechAlternativesStartIndex;	// 264 = 0x108
    AFUserUtterance *_userUtterance;	// 272 = 0x110
}

@property(retain, nonatomic, getter=_userUtterance, setter=_setUserUtterance:) AFUserUtterance *userUtterance; // @synthesize userUtterance=_userUtterance;
- (void).cxx_destruct;	// IMP=0x000000010005f798
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010005f5f4
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010005f558
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010005f0b4
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x000000010005f09c
- (id)userSelectionResults:(id)arg1;	// IMP=0x000000010005ed0c
- (void)handleSelectRow:(long long)arg1;	// IMP=0x000000010005e98c
- (id)_processUserUtterance:(id)arg1 isCombined:(_Bool)arg2 displayedText:(id)arg3 withScore:(_Bool)arg4;	// IMP=0x000000010005dd08
- (id)speechAlternativeHighlightListWithScore:(_Bool)arg1;	// IMP=0x000000010005d708
- (void)_createSpeechAlternativeViewsIfNecessary;	// IMP=0x000000010005d498
- (void)createViewArray;	// IMP=0x000000010005d208
- (void)restoreOriginalEditTextContents:(id)arg1;	// IMP=0x000000010005d120
- (void)editableTextViewTextDidResignFirstResponder:(id)arg1;	// IMP=0x000000010005d074
- (void)editableTextViewTextDidReceiveReturnKey:(id)arg1;	// IMP=0x000000010005d068
- (void)editableTextViewTextDidFinishCorrecting:(id)arg1;	// IMP=0x000000010005cc10
- (void)editableTextViewTextDidChange:(id)arg1;	// IMP=0x000000010005cad0
- (void)_checkUpdatedSizingForEditableTextView:(id)arg1;	// IMP=0x000000010005c9d8
- (void)editableTextViewTextWillBeginCorrecting:(id)arg1;	// IMP=0x000000010005c7f8
- (_Bool)editableTextViewTextShouldPreventCorrection:(id)arg1;	// IMP=0x000000010005c7a4
- (void)createEditableUtteranceView;	// IMP=0x000000010005c6b0
- (void)_hideEditableUtteranceView;	// IMP=0x000000010005c554
- (void)_utteranceViewDidSelect:(id)arg1;	// IMP=0x000000010005c40c
- (double)_insertionAnimatedZPosition;	// IMP=0x000000010005c3f8
- (long long)_replacementAnimation;	// IMP=0x000000010005c3d8
- (long long)_insertionAnimation;	// IMP=0x000000010005c3c0
- (long long)_pinAnimationType;	// IMP=0x000000010005c3b8
- (void)endEditingAndCorrectByTouchPoint:(struct CGPoint)arg1;	// IMP=0x000000010005c0e0
- (void)endEditingAndCorrect:(_Bool)arg1;	// IMP=0x000000010005c018
- (double)baselineOffsetFromBottom;	// IMP=0x000000010005c000
- (double)_scaledPaddingForPadding:(double)arg1;	// IMP=0x000000010005bf80
- (double)desiredPinnedTopPadding;	// IMP=0x000000010005bf2c
- (double)desiredTopPaddingBelowController:(id)arg1;	// IMP=0x000000010005bed8
- (void)setAceObject:(id)arg1;	// IMP=0x000000010005ba90
- (void)handleChangeUtteranceCommand:(id)arg1;	// IMP=0x000000010005b6f8
- (void)handleShowSpeechAlternativesCommand:(id)arg1;	// IMP=0x000000010005b644
- (void)handleAceCommand:(id)arg1;	// IMP=0x000000010005b56c
- (void)removeSpeechAlternativeViewAndUpdateUtteranceTextIfNecessary;	// IMP=0x000000010005b434
- (void)removeSpeechAlternatives;	// IMP=0x000000010005b3a4
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x000000010005b338
- (id)_correctionIdentifier;	// IMP=0x000000010005b2e4
@property(readonly, copy) NSString *description;
- (void)setUtteranceUserInteractionEnabled:(_Bool)arg1;	// IMP=0x000000010005b114
- (void)_updateViewWithChangeUtteranceIfNeeded:(id)arg1;	// IMP=0x000000010005b008
- (void)_updateViewWithUserUtterance:(id)arg1;	// IMP=0x000000010005ae7c
- (void)viewDidLayoutSubviews;	// IMP=0x000000010005ad70
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010005abcc
- (void)viewWillLayoutSubviews;	// IMP=0x000000010005aab8
- (void)loadView;	// IMP=0x000000010005a924

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

