//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SVSUserAttentionSignalProviderFactory : NSObject
{
    double _samplingInterval;	// 8 = 0x8
    double _attentionLossTimeout;	// 16 = 0x10
    unsigned long long _supportedAttentionAwarenessEvents;	// 24 = 0x18
}

+ (id)_attentionAwarenessConfigurationWithIdentifier:(id)arg1 eventMask:(unsigned long long)arg2 samplingInterval:(double)arg3 attentionLossTimeout:(double)arg4;	// IMP=0x00000001000495d4
- (unsigned long long)_touchAttentionAwarenessEventMask;	// IMP=0x00000001000495bc
- (unsigned long long)_faceAttentionAwarenessEventMask;	// IMP=0x00000001000495a4
- (id)wakeGestureManager;	// IMP=0x0000000100049590
- (id)touchAttentionAwarenessClient;	// IMP=0x00000001000494cc
- (id)faceAttentionAwarenessClient;	// IMP=0x00000001000493fc
- (id)initWithSamplingInterval:(double)arg1 attentionLossTimeout:(double)arg2 supportedAttentionAwarenessEvents:(unsigned long long)arg3;	// IMP=0x0000000100049384

@end

