//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint;

@interface GKSignInInputView : UIView
{
    NSLayoutConstraint *_topToSignInBaselineConstraint;	// 8 = 0x8
    NSLayoutConstraint *_signInBaselineToPromptTextTopConstraint;	// 16 = 0x10
    NSLayoutConstraint *_inputViewHeightConstraint;	// 24 = 0x18
    NSLayoutConstraint *_promptTextToProgressIndicatorTopConstraint;	// 32 = 0x20
    NSLayoutConstraint *_signInFormToSignInLabelTopConstraint;	// 40 = 0x28
}

@property(retain, nonatomic) NSLayoutConstraint *signInFormToSignInLabelTopConstraint; // @synthesize signInFormToSignInLabelTopConstraint=_signInFormToSignInLabelTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *promptTextToProgressIndicatorTopConstraint; // @synthesize promptTextToProgressIndicatorTopConstraint=_promptTextToProgressIndicatorTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *inputViewHeightConstraint; // @synthesize inputViewHeightConstraint=_inputViewHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *signInBaselineToPromptTextTopConstraint; // @synthesize signInBaselineToPromptTextTopConstraint=_signInBaselineToPromptTextTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topToSignInBaselineConstraint; // @synthesize topToSignInBaselineConstraint=_topToSignInBaselineConstraint;
- (void)dealloc;	// IMP=0x000000010001c3a4
- (id)allVariableConstraints;	// IMP=0x000000010001c2f4
- (void)setupConstraintConstantsForOrientation:(long long)arg1;	// IMP=0x000000010001bf78

@end

