//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SUAccountViewController.h"

#import "SUStorePageViewControllerResponder.h"
#import "ServiceAccountPageEmbedded.h"

@class NSString;

@interface ServiceSUAccountViewController : SUAccountViewController <SUStorePageViewControllerResponder, ServiceAccountPageEmbedded>
{
    id <ServiceAccountPageEmbeddedParent> _embeddedParent;	// 24 = 0x18
}

@property(nonatomic) __weak id <ServiceAccountPageEmbeddedParent> embeddedParent; // @synthesize embeddedParent=_embeddedParent;
- (void).cxx_destruct;	// IMP=0x0000000100009dbc
- (void)storePage:(id)arg1 finishedWithSuccess:(_Bool)arg2;	// IMP=0x0000000100009d70
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100009cd4
- (void)dismissAnimated:(_Bool)arg1;	// IMP=0x0000000100009c58

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

