//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SKTermsPageViewController;

@protocol SKTermsPageViewControllerDelegate <NSObject>

@optional
- (void)termsPageViewControllerDidFinish:(SKTermsPageViewController *)arg1 withAcceptance:(_Bool)arg2;
- (void)termsPageViewControllerDidFinish:(SKTermsPageViewController *)arg1;
@end

