//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface ChevronView : UIView
{
    unsigned long long _state;	// 8 = 0x8
    UIView *_leftView;	// 16 = 0x10
    UIView *_rightView;	// 24 = 0x18
    UIView *_contentView;	// 32 = 0x20
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) UIView *leftView; // @synthesize leftView=_leftView;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;	// IMP=0x000000010007b420
- (void)tintColorDidChange;	// IMP=0x000000010007b1cc
- (void)updateForPercent:(double)arg1;	// IMP=0x000000010007b0d8
- (void)update;	// IMP=0x000000010007af44
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010007af38
- (struct CGSize)intrinsicContentSize;	// IMP=0x000000010007af28
- (id)createChevron;	// IMP=0x000000010007ae68
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010007a740

@end

