//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMViewController.h"

@class NSLayoutConstraint, UIView;

@interface DynamicContentViewController : FMViewController
{
    UIView *_dynamicContentView;	// 8 = 0x8
    NSLayoutConstraint *_dynamicContentViewBottomConstraint;	// 16 = 0x10
}

@property(retain, nonatomic) NSLayoutConstraint *dynamicContentViewBottomConstraint; // @synthesize dynamicContentViewBottomConstraint=_dynamicContentViewBottomConstraint;
@property(retain, nonatomic) UIView *dynamicContentView; // @synthesize dynamicContentView=_dynamicContentView;
- (void).cxx_destruct;	// IMP=0x00000001000832ac
- (void)dismissKeyboard:(id)arg1;	// IMP=0x0000000100083208
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0000000100083200
- (void)decodeRestorableStateWithCoder:(id)arg1;	// IMP=0x0000000100083110
- (void)encodeRestorableStateWithCoder:(id)arg1;	// IMP=0x0000000100083060
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100082b60
- (void)viewDidLoad;	// IMP=0x0000000100082b2c

@end

