//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContact, NSDictionary, NSString, UIImage;

@protocol FMAppShortcutItem <NSObject>
@property(readonly, copy) NSString *shortcutTitle;
@property(readonly, copy) NSString *shortcutType;
@property(readonly, copy) NSString *shortcutIdentifier;

@optional
@property(readonly) UIImage *shortcutIconImage;
@property(readonly, copy) NSString *shortcutIconImageName;
@property(readonly, copy) CNContact *shortcutIconContact;
@property(readonly, copy) NSDictionary *shortcutUserInfo;
@property(readonly, copy) NSString *shortcutSubTitle;
@end

