//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMIPEntity.h"

@class FMIPDevice, NSArray, NSDate, NSDictionary, NSNumber, NSSet, NSString, Session;

@interface FMIPAccount : FMIPEntity
{
    _Bool showSllNow;	// 8 = 0x8
    NSArray *_orderedDevices;	// 16 = 0x10
    FMIPDevice *_selectedDevice;	// 24 = 0x18
    Session *_session;	// 32 = 0x20
    unsigned long long _deviceLoadStatus;	// 40 = 0x28
    NSDictionary *_userInfoDetails;	// 48 = 0x30
}

@property(nonatomic) unsigned long long deviceLoadStatus; // @synthesize deviceLoadStatus=_deviceLoadStatus;
@property(nonatomic) __weak Session *session; // @synthesize session=_session;
@property(retain, nonatomic) FMIPDevice *selectedDevice; // @synthesize selectedDevice=_selectedDevice;
@property(retain, nonatomic) NSArray *orderedDevices; // @synthesize orderedDevices=_orderedDevices;
@property(nonatomic) _Bool showSllNow; // @synthesize showSllNow;
- (void).cxx_destruct;	// IMP=0x000000010001fd50
@property(readonly, nonatomic) NSString *formattedUsername;
- (_Bool)isMakoAccount;	// IMP=0x000000010001fba8
- (_Bool)isFamilyMemberHSAEnabled:(id)arg1;	// IMP=0x000000010001fac4
@property(retain, nonatomic) NSDictionary *userInfoDetails; // @synthesize userInfoDetails=_userInfoDetails;
- (id)formattedAppleIdForPersonId:(id)arg1;	// IMP=0x000000010001f60c
- (id)appleIdForPersonId:(id)arg1;	// IMP=0x000000010001f528
- (_Bool)isMakoFamilyAccount:(id)arg1;	// IMP=0x000000010001f4c8
- (id)familyMemberShortNameForPersonId:(id)arg1;	// IMP=0x000000010001f324
- (id)familyMemberNameForPersonId:(id)arg1;	// IMP=0x000000010001f14c
@property(readonly, copy, nonatomic) NSDictionary *familyMemberDetails;
@property(readonly, nonatomic, getter=isFamilyMember) _Bool familyMember;
@property(readonly, copy, nonatomic) NSString *fullName;
- (id)fullNameFormatter;	// IMP=0x000000010001ede4
@property(readonly, copy, nonatomic) NSString *firstName;
- (void)removeDevice:(id)arg1;	// IMP=0x000000010001ea18
- (void)removeFamilyDevice:(id)arg1 withDoneCompletion:(CDUnknownBlockType)arg2 withCancelCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001dc38
- (void)removeDevice:(id)arg1 withDoneCompletion:(CDUnknownBlockType)arg2 withCancelCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001d47c
- (void)selectDevice:(id)arg1;	// IMP=0x000000010001d0d4
- (void)flushOrderedDevices;	// IMP=0x000000010001d07c
- (id)deviceWithId:(id)arg1;	// IMP=0x000000010001cb88
@property(retain, nonatomic) NSString *authToken; // @dynamic authToken;

// Remaining properties
@property(retain, nonatomic) NSSet *devices; // @dynamic devices;
@property(nonatomic) _Bool isHighSecurityAccount; // @dynamic isHighSecurityAccount;
@property(retain, nonatomic) NSDate *lastSllTimestamp; // @dynamic lastSllTimestamp;
@property(retain, nonatomic) NSString *password; // @dynamic password;
@property(retain, nonatomic) NSNumber *personID; // @dynamic personID;
@property(retain, nonatomic) NSString *realmRedirectedHost; // @dynamic realmRedirectedHost;
@property(retain, nonatomic) NSString *selectedDeviceURI; // @dynamic selectedDeviceURI;
@property(retain, nonatomic) NSNumber *showSllCount; // @dynamic showSllCount;
@property(nonatomic) _Bool turnBluetoothAlertOnShown; // @dynamic turnBluetoothAlertOnShown;
@property(retain, nonatomic) NSDictionary *userInfo; // @dynamic userInfo;
@property(retain, nonatomic) NSString *username; // @dynamic username;

@end

