//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSLayoutConstraint, NSMutableDictionary, NSString, SpacerView, UIColor, UIFontDescriptor, UIImage, UILabel, UIStackView, UIView, WrapperView;

@interface FMIPButton : UIControl
{
    _Bool _textOnlyButton;	// 8 = 0x8
    UIColor *_normalColor;	// 16 = 0x10
    UIColor *_highlightColor;	// 24 = 0x18
    UIColor *_borderColor;	// 32 = 0x20
    double _borderWidth;	// 40 = 0x28
    double _cornerRadius;	// 48 = 0x30
    double _continuousCornerRadius;	// 56 = 0x38
    UIFontDescriptor *_fontDescriptor;	// 64 = 0x40
    UIImage *_placeholderImage;	// 72 = 0x48
    UIImage *_axImage;	// 80 = 0x50
    UIStackView *_stackView;	// 88 = 0x58
    WrapperView *_imageWrapperView;	// 96 = 0x60
    UIView *_imageView;	// 104 = 0x68
    UILabel *_labelView;	// 112 = 0x70
    SpacerView *_labelSpacerView;	// 120 = 0x78
    unsigned long long _customState;	// 128 = 0x80
    NSLayoutConstraint *_topConstraint;	// 136 = 0x88
    NSMutableDictionary *_modeViews;	// 144 = 0x90
}

@property(retain, nonatomic) NSMutableDictionary *modeViews; // @synthesize modeViews=_modeViews;
@property(retain, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(nonatomic) unsigned long long customState; // @synthesize customState=_customState;
@property(retain, nonatomic) SpacerView *labelSpacerView; // @synthesize labelSpacerView=_labelSpacerView;
@property(retain, nonatomic) UILabel *labelView; // @synthesize labelView=_labelView;
@property(retain, nonatomic) UIView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) WrapperView *imageWrapperView; // @synthesize imageWrapperView=_imageWrapperView;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) _Bool textOnlyButton; // @synthesize textOnlyButton=_textOnlyButton;
@property(retain, nonatomic) UIImage *axImage; // @synthesize axImage=_axImage;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(retain, nonatomic) UIFontDescriptor *fontDescriptor; // @synthesize fontDescriptor=_fontDescriptor;
@property(nonatomic) double continuousCornerRadius; // @synthesize continuousCornerRadius=_continuousCornerRadius;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(retain, nonatomic) UIColor *normalColor; // @synthesize normalColor=_normalColor;
- (void).cxx_destruct;	// IMP=0x000000010005f094
- (unsigned long long)accessibilityTraits;	// IMP=0x000000010005eddc
- (_Bool)isAccessibilityElement;	// IMP=0x000000010005edd4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010005eab8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010005e810
- (void)_switchtoViewForMode:(unsigned char)arg1;	// IMP=0x000000010005e574
- (void)_commonConfiguration;	// IMP=0x000000010005e37c
- (void)createStackViewIfNeeded;	// IMP=0x000000010005de88
- (id)viewForMode:(unsigned char)arg1;	// IMP=0x000000010005ddf8
- (void)setView:(id)arg1 forMode:(unsigned char)arg2;	// IMP=0x000000010005dc58
@property(nonatomic) unsigned char mode;
@property(retain, nonatomic) NSString *label;
- (unsigned long long)state;	// IMP=0x000000010005d3d4
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x000000010005d29c
- (void)setEnabled:(_Bool)arg1;	// IMP=0x000000010005d074
- (void)tintColorDidChange;	// IMP=0x000000010005ce34
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010005cdd0
- (void)configureButton;	// IMP=0x000000010005c784
- (struct CGSize)intrinsicContentSize;	// IMP=0x000000010005c728
- (void)prepareForInterfaceBuilder;	// IMP=0x000000010005c6d8
- (void)awakeFromNib;	// IMP=0x000000010005c688
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010005c630

@end

