//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMViewController.h"

#import "FMIPCommandProcessingProtocol.h"

@class FMIPCommandContext, NSLayoutConstraint, NSString;

@interface FMIPCommandViewController : FMViewController <FMIPCommandProcessingProtocol>
{
    _Bool _needsRightNavBarButton;	// 8 = 0x8
    _Bool _needsStepperInTitle;	// 9 = 0x9
    _Bool _isStepIncremented;	// 10 = 0xa
    FMIPCommandContext *commandContext;	// 16 = 0x10
    NSLayoutConstraint *_lastElementBottomBufferConstraint;	// 24 = 0x18
}

@property(nonatomic) _Bool isStepIncremented; // @synthesize isStepIncremented=_isStepIncremented;
@property(nonatomic) _Bool needsStepperInTitle; // @synthesize needsStepperInTitle=_needsStepperInTitle;
@property(nonatomic) _Bool needsRightNavBarButton; // @synthesize needsRightNavBarButton=_needsRightNavBarButton;
@property(retain, nonatomic) NSLayoutConstraint *lastElementBottomBufferConstraint; // @synthesize lastElementBottomBufferConstraint=_lastElementBottomBufferConstraint;
@property(retain, nonatomic) FMIPCommandContext *commandContext; // @synthesize commandContext;
- (void).cxx_destruct;	// IMP=0x0000000100082aec
- (void)modalFlowDone:(id)arg1;	// IMP=0x000000010008296c
- (void)modalFlowCancel:(id)arg1;	// IMP=0x00000001000828b4
- (void)dismissKeyboard:(id)arg1;	// IMP=0x0000000100082858
- (void)performNextAction;	// IMP=0x00000001000827e0
- (void)performDoneAction;	// IMP=0x00000001000826d4
- (void)updateNavBarDetails;	// IMP=0x00000001000822e8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100081c34
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;	// IMP=0x0000000100081a98
- (void)viewDidLoad;	// IMP=0x0000000100081a30

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

