//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DynamicContentViewController.h"

#import "AKAppleIDAuthenticationDelegate.h"
#import "AKInlineSignInViewControllerDelegate.h"

@class AKAppleIDAuthenticationInAppContext, AKInlineSignInViewController, NSString, NSTimer, UIView;

@interface LoginViewController : DynamicContentViewController <AKInlineSignInViewControllerDelegate, AKAppleIDAuthenticationDelegate>
{
    _Bool _doNotAnimateKeyboardWillShow;	// 8 = 0x8
    _Bool _previousAnimationState;	// 9 = 0x9
    UIView *_stackView;	// 16 = 0x10
    UIView *_contentView;	// 24 = 0x18
    UIView *_statusBarBlurView;	// 32 = 0x20
    UIView *_containerView;	// 40 = 0x28
    AKInlineSignInViewController *_childViewController;	// 48 = 0x30
    NSTimer *_delayedKeyboardTimer;	// 56 = 0x38
    AKAppleIDAuthenticationInAppContext *_authContext;	// 64 = 0x40
}

@property(retain, nonatomic) AKAppleIDAuthenticationInAppContext *authContext; // @synthesize authContext=_authContext;
@property(retain, nonatomic) NSTimer *delayedKeyboardTimer; // @synthesize delayedKeyboardTimer=_delayedKeyboardTimer;
@property(retain, nonatomic) AKInlineSignInViewController *childViewController; // @synthesize childViewController=_childViewController;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *statusBarBlurView; // @synthesize statusBarBlurView=_statusBarBlurView;
@property(nonatomic) _Bool previousAnimationState; // @synthesize previousAnimationState=_previousAnimationState;
@property(nonatomic) _Bool doNotAnimateKeyboardWillShow; // @synthesize doNotAnimateKeyboardWillShow=_doNotAnimateKeyboardWillShow;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *stackView; // @synthesize stackView=_stackView;
- (void).cxx_destruct;	// IMP=0x00000001000565d0
- (_Bool)authenticationController:(id)arg1 shouldContinueWithAuthenticationResults:(id)arg2 error:(id)arg3 forContext:(id)arg4;	// IMP=0x00000001000563fc
- (void)signInViewController:(id)arg1 didAuthenticateWithResults:(id)arg2 error:(id)arg3;	// IMP=0x000000010005615c
- (void)installContentViewController:(id)arg1 animateAlongside:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100055a14
- (void)switchToAuthKitModule;	// IMP=0x00000001000555e4
- (void)iForgot:(id)arg1;	// IMP=0x0000000100055438
- (void)setupInstructions:(id)arg1;	// IMP=0x0000000100055218
- (void)loginWithUsername:(id)arg1 password:(id)arg2;	// IMP=0x0000000100054ee0
- (void)loginAsOwner;	// IMP=0x0000000100054db8
- (id)defaultUsername;	// IMP=0x0000000100054cc4
- (void)updateStatusBarBlur;	// IMP=0x0000000100054bc0
- (void)configureStatusBarBlur;	// IMP=0x0000000100054a14
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000549c4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100054598
- (void)viewDidLoad;	// IMP=0x00000001000544d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

