//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface PreloadContext : NSObject
{
    NSURL *_url;	// 8 = 0x8
    NSString *_deviceClass;	// 16 = 0x10
    NSString *_model;	// 24 = 0x18
    NSString *_deviceColor;	// 32 = 0x20
    long long _size;	// 40 = 0x28
    long long _variant;	// 48 = 0x30
}

@property(nonatomic) long long variant; // @synthesize variant=_variant;
@property(nonatomic) long long size; // @synthesize size=_size;
@property(copy, nonatomic) NSString *deviceColor; // @synthesize deviceColor=_deviceColor;
@property(copy, nonatomic) NSString *model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *deviceClass; // @synthesize deviceClass=_deviceClass;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;	// IMP=0x00000001000585e0
- (id)description;	// IMP=0x0000000100058498
- (unsigned long long)hash;	// IMP=0x000000010005844c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000583ac
- (id)initWithDevice:(id)arg1 size:(long long)arg2 variant:(long long)arg3;	// IMP=0x0000000100058174

@end

