//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMIPViewController.h"

@class UIScrollView, UIView;

@interface SiteDownViewController : FMIPViewController
{
    UIScrollView *_scrollView;	// 8 = 0x8
    UIView *_contentView;	// 16 = 0x10
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;	// IMP=0x000000010008d0dc
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010008cf7c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010008cf48
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010008ced8
- (void)retry:(id)arg1;	// IMP=0x000000010008cd80
- (void)viewDidLoad;	// IMP=0x000000010008cd0c

@end

