//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivityIndicatorView.h"

@interface TintedActivityIndicatorView : UIActivityIndicatorView
{
}

- (void)tintColorDidChange;	// IMP=0x0000000100078b1c
- (void)awakeFromNib;	// IMP=0x0000000100078aa4

@end

