//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Base.h"

@interface ActiveSet : Base
{
}

- (void)updateWithData:(id)arg1 logCode:(int)arg2;	// IMP=0x000000010000a5e4
- (id)getSectionName;	// IMP=0x000000010000a5d8
- (id)getLogCodeArray;	// IMP=0x000000010000a578
- (id)initWithDict:(id)arg1 codeDict:(id)arg2;	// IMP=0x000000010000a4e4

@end

