//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Base : NSObject
{
    NSObject *sectionRef;	// 8 = 0x8
}

+ (short)lookUpECNO:(unsigned int)arg1;	// IMP=0x0000000100013458
- (void)replaceArray:(id)arg1 With:(id)arg2;	// IMP=0x00000001000133ec
- (void)clearElementsInArray:(id)arg1;	// IMP=0x00000001000133a0
- (void)updateLogCodeDict:(id)arg1;	// IMP=0x0000000100013250
- (id)getLogCodeArray;	// IMP=0x0000000100013228
- (id)getSectionName;	// IMP=0x0000000100013200
- (void)updateWithData:(id)arg1 logCode:(int)arg2;	// IMP=0x00000001000131ec
- (void)updateSectionRef:(id)arg1;	// IMP=0x000000010001319c
- (id)init;	// IMP=0x0000000100013158

@end

