//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EURLogGenerator2.h"

@interface EUR_GSMLogGenerator : EURLogGenerator2
{
}

+ (id)generator;	// IMP=0x0000000100004e00
- (void)dealloc;	// IMP=0x0000000100004ee4
- (id)init;	// IMP=0x0000000100004e38

@end

