//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FieldTestModelNode.h"

@class NSString;

@interface FieldTestModelLeafNode : FieldTestModelNode
{
    NSString *_string;	// 16 = 0x10
}

- (id)value;	// IMP=0x0000000100004354
- (void)dealloc;	// IMP=0x00000001000042fc
- (id)initWithName:(id)arg1 withValue:(id)arg2;	// IMP=0x000000010000426c

@end

