//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, SBUIAppleLogoView, UILabel;

@interface PBADataRecoveryProgressViewController : UIViewController
{
    SBUIAppleLogoView *_appleLogoView;	// 8 = 0x8
    UILabel *_statusLabel;	// 16 = 0x10
    NSString *_statusText;	// 24 = 0x18
    double _progress;	// 32 = 0x20
}

@property(copy, nonatomic) NSString *statusText; // @synthesize statusText=_statusText;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;	// IMP=0x0000000100006494
- (void)didReceiveMemoryWarning;	// IMP=0x00000001000063bc
- (void)viewDidLoad;	// IMP=0x0000000100006330
- (void)loadView;	// IMP=0x0000000100005a0c

@end

