//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BKSHIDEventRouter, NSArray;

@interface PBAHIDEventController : NSObject
{
    BKSHIDEventRouter *_eventRouter;	// 8 = 0x8
    NSArray *_savedEventRouters;	// 16 = 0x10
}

+ (id)sharedController;	// IMP=0x0000000100003c54
@property(copy, nonatomic) NSArray *savedEventRouters; // @synthesize savedEventRouters=_savedEventRouters;
@property(retain, nonatomic) BKSHIDEventRouter *eventRouter; // @synthesize eventRouter=_eventRouter;
- (void).cxx_destruct;	// IMP=0x00000001000041fc
- (void)stopReceivingEvents;	// IMP=0x0000000100004150
- (void)startReceivingEvents;	// IMP=0x0000000100003e94
- (id)init;	// IMP=0x0000000100003cd4

@end

