//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSPowerMonitorObserver.h"

@class NSString;

@interface PBAIdleSleepController : NSObject <BSPowerMonitorObserver>
{
    _Bool _displayDim;	// 8 = 0x8
    _Bool _allowIdleTimerToBeReset;	// 9 = 0x9
}

+ (id)sharedController;	// IMP=0x000000010000c780
@property(nonatomic) _Bool allowIdleTimerToBeReset; // @synthesize allowIdleTimerToBeReset=_allowIdleTimerToBeReset;
@property(nonatomic, getter=isDisplayDim) _Bool displayDim; // @synthesize displayDim=_displayDim;
- (void)powerMonitorSystemDidWakeFromSleep:(id)arg1;	// IMP=0x000000010000d6a4
- (void)powerMonitorSystemWillWakeFromSleep:(id)arg1;	// IMP=0x000000010000d62c
- (void)powerMonitorSystemWillSleep:(id)arg1;	// IMP=0x000000010000d5b4
- (void)powerMonitorSystemSleepRequestAborted:(id)arg1;	// IMP=0x000000010000d53c
- (_Bool)powerMonitorSystemSleepRequested:(id)arg1;	// IMP=0x000000010000d4c0
- (void)_startAllowingIdleTimer;	// IMP=0x000000010000d4a0
- (void)_requestedUserEventNotificationOccurred;	// IMP=0x000000010000d49c
- (void)_userEventPresenceTimerExpired;	// IMP=0x000000010000d498
- (void)_userEventOccurred;	// IMP=0x000000010000d488
- (void)_userEventsDidIdle;	// IMP=0x000000010000d47c
- (void)resetIdleTimerAndUndim:(_Bool)arg1;	// IMP=0x000000010000d2f8
- (double)_nextLockTimeDuration;	// IMP=0x000000010000d2b4
- (void)setPreventIdleSleep:(_Bool)arg1 forReason:(id)arg2;	// IMP=0x000000010000d23c
- (void)_preventIdleSleepForNumberOfSeconds:(float)arg1;	// IMP=0x000000010000d14c
- (void)_preventIdleSleep;	// IMP=0x000000010000d0f4
- (void)_allowIdleSleep;	// IMP=0x000000010000d09c
- (void)dimDisplay;	// IMP=0x000000010000cf14
- (void)undimDisplay;	// IMP=0x000000010000cef4
- (void)_undimDisplayForce;	// IMP=0x000000010000cd94
- (void)_setHIDUILockedState:(_Bool)arg1;	// IMP=0x000000010000cd50
- (id)init;	// IMP=0x000000010000c800

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

