//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PUPhotosGridViewControllerSpec, PUTabbedLibraryViewControllerSpec;

@interface PhotosAppSpec : NSObject
{
}

+ (id)specForIdiom:(long long)arg1;	// IMP=0x000000010000351c
@property(readonly, nonatomic) PUPhotosGridViewControllerSpec *importViewControllerSpec;
@property(readonly, nonatomic) PUTabbedLibraryViewControllerSpec *libraryContentControllerSpec;
- (_Bool)messageUISupportsOrientation:(long long)arg1;	// IMP=0x0000000100003574
@property(readonly, nonatomic) unsigned long long interfaceEnvironment;

@end

