//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HUServiceGridItemManager.h"

#import "HFAccessoryBrowsingObserver.h"

@class HFAccessoryBrowsingManager, NSString;

@interface HSDiscoveredAccessoryGridContentItemManager : HUServiceGridItemManager <HFAccessoryBrowsingObserver>
{
    HFAccessoryBrowsingManager *_accessoryBrowsingManager;	// 8 = 0x8
}

@property(readonly, nonatomic) HFAccessoryBrowsingManager *accessoryBrowsingManager; // @synthesize accessoryBrowsingManager=_accessoryBrowsingManager;
- (void).cxx_destruct;	// IMP=0x000000010002b8c0
- (void)_reloadDiscoveredAccessoryItemProviderWithSenderSelector:(SEL)arg1;	// IMP=0x000000010002b734
- (void)accessoryBrowsingManager:(id)arg1 didRemoveNewSharingDevice:(id)arg2;	// IMP=0x000000010002b720
- (void)accessoryBrowsingManager:(id)arg1 didFindNewSharingDevice:(id)arg2;	// IMP=0x000000010002b70c
- (void)accessoryBrowsingManager:(id)arg1 didRemoveNewAccessory:(id)arg2;	// IMP=0x000000010002b6f8
- (void)accessoryBrowsingManager:(id)arg1 didFindNewAccessory:(id)arg2;	// IMP=0x000000010002b6e4
- (CDUnknownBlockType)_comparatorForSectionIdentifier:(id)arg1;	// IMP=0x000000010002b428
- (void)_unregisterForExternalUpdates;	// IMP=0x000000010002b3b4
- (void)_registerForExternalUpdates;	// IMP=0x000000010002b340
- (id)initWithAccessoryBrowsingManager:(id)arg1 delegate:(id)arg2 discoveredAccessoryFilter:(id)arg3;	// IMP=0x000000010002b090
- (id)initWithDelegate:(id)arg1 shouldGroupByRoom:(_Bool)arg2 itemProvidersCreator:(CDUnknownBlockType)arg3;	// IMP=0x000000010002af80

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

