//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HFItemManager.h"

@class HULinkedApplicationItemProvider;

@interface HSSetupBridgedAccessoryItemManager : HFItemManager
{
    HULinkedApplicationItemProvider *_appItemProvider;	// 8 = 0x8
}

@property(retain, nonatomic) HULinkedApplicationItemProvider *appItemProvider; // @synthesize appItemProvider=_appItemProvider;
- (void).cxx_destruct;	// IMP=0x0000000100008c08
- (id)sectionIdentifiers;	// IMP=0x0000000100008a94
- (id)_titleForSectionWithIdentifier:(id)arg1;	// IMP=0x00000001000089f8
- (id)_sectionIdentifierForItem:(id)arg1;	// IMP=0x000000010000888c
- (id)_identifierForSection:(unsigned long long)arg1;	// IMP=0x00000001000087c8
- (unsigned long long)_numberOfSections;	// IMP=0x000000010000877c
- (id)_buildItemProvidersForHome:(id)arg1;	// IMP=0x0000000100008430

@end

