//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HSSetupTroubleshootingTipItem.h"

@interface HSSetupManuallyEnterCodeTroubleshootingTipItem : HSSetupTroubleshootingTipItem
{
}

- (id)init;	// IMP=0x0000000100011c90

@end

