//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSString, UILabel;

@interface HSTitleAndDescriptionView : UIView
{
    NSString *_titleText;	// 8 = 0x8
    NSString *_descriptionText;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    UILabel *_descriptionLabel;	// 32 = 0x20
    NSArray *_constraints;	// 40 = 0x28
}

+ (_Bool)requiresConstraintBasedLayout;	// IMP=0x0000000100008c1c
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
- (void).cxx_destruct;	// IMP=0x0000000100009608
- (id)viewForLastBaselineLayout;	// IMP=0x0000000100009480
- (id)viewForFirstBaselineLayout;	// IMP=0x0000000100009474
- (void)updateConstraints;	// IMP=0x0000000100008e8c
- (id)init;	// IMP=0x0000000100008c24

@end

